### ISSUE TITLE
Some people who have Signal installed cannot contact each other

### ISSUE THREAD

**Issue by charlyromero** [signalapp/Signal-Android#10059]
Bug description
Hello, I am a Signal user on Android. I detected a problem, it is that Signal does not detect some contacts as Signal users. I already searched for this error in Google, and what it suggests is that you go to Settings (android) / Accounts / Signal and delete it so that it can be created again later. This I already did and it does not correct it. I also wrote an email to support, but have not received a response yet. It happened to me with a friend who installed the app. And both he and I are not visible to each other to start a conversation in the app. Today I also installed Signal for someone in my family, having both cell phones in hand, and the same thing happened to me. We cannot write or contact each other through the app. I tried with both cell phones, the solution to go to Accounts and delete it so that it is recreated. And nothing. It has happened to me to date with more than 5 people. It would be nice if they can solve it, since the idea of this app is surprising. A greeting!

By the way, I checked this post: https://github.com/signalapp/Signal-Android/issues/8639 But there are times that the solutions presented there work and others that do not

Device info
**Device:** Samsung S5
**Android version:** 6.0.1
**Signal version:** 4.72.5

**Comment by Genis-Sage** [comment]
hey @charlyromero 

please use the full bug issue template

also, the title is misleading
the title should be similar to "some Signal users are not detected"

also, did you try if you can add them manually?
1) pencil icon
2) press the numpad in the top bar
3) enter their number manually

also, from what country are you?
did you save the contacts with leading country code or with a 0?
did you register yourself with a different country code than you are using right now?
what language settings do you use?

for example, some country (i guess it was Mexico) changed their country code
and because you have saved the contact with a different country code than they have registered in Signal, you could not detect them

**Comment by charlyromero** [comment]
Hello @Genis-Sage 

I already tried adding them manually, but they appear to me to send insecure SMS

I am from Argentina

My contacts have their area code, with the respective country as well.

I use the Spanish language.

It's happening to me with a lot of people, to whom I recommend Signal. We cannot detect ourselves to start a conversation through the app. I have tried with two phones, trying to communicate with those contacts, and it has been impossible. Like the article I cited in my first post, there are many people who do the same.

**Comment by greyson-signal** [comment]
When you add them manually, are you entering their number exactly as they entered it when they signed up? A good way to check would be to have them go to their in-app settings. Under their name, it should show their number.

**Comment by charlyromero** [comment]
Thank you so much @greyson-signal 

The problem is already identified. I was able to solve it with three people who happened to me. I proceed to explain: In Argentina, the country code prefix +54 or +549 is used, both cases mean the same thing. For example whatsapp detects it even if you write it in either of the two ways. In my case. It had them scheduled as +549, and when I scheduled them as only +54, it detected it. Although anyway, I am currently communicating with people by signal that I have scheduled with +549, but in the case of these 3 specific people I did not detect it previously. You can close the thread. It would be good if they implement the detection in the app for Argentina of +54 or +549, that both cases correspond to a contact.

**Comment by greyson-signal** [comment]
Ah, glad it was resolved! Happy chatting :)
(I'll think more about the phone number formats)

**Comment by SexyPantz** [comment]
> Thank you so much @greyson-signal
> 
> The problem is already identified. I was able to solve it with three people who happened to me. I proceed to explain: In Argentina, the country code prefix +54 or +549 is used, both cases mean the same thing. For example whatsapp detects it even if you write it in either of the two ways. In my case. It had them scheduled as +549, and when I scheduled them as only +54, it detected it. Although anyway, I am currently communicating with people by signal that I have scheduled with +549, but in the case of these 3 specific people I did not detect it previously. You can close the thread. It would be good if they implement the detection in the app for Argentina of +54 or +549, that both cases correspond to a contact.

Tried that fix, not working. Signal still won't recognise other signal contacts, and will only send them SMS messages.
