### ISSUE TITLE
Backup generates no backup file (Nextcloud)

### ISSUE THREAD

**Issue by mueslo** [signalapp/Signal-Android#10258]
For external storage I chose a folder in Nextcloud. This results in the storage location being displayed as "" and the backup failing with "Renaming temporary backup file failed!"

**Comment by Lion-box** [comment]
for debugging purposes, did you try to keep Nextcloud disabled while Signal performs the whole backup operation?
it feels like some kind of conflict happening when Signal renames the .tmp file, which should be excluded from syncing in Nextcloud default config , but appears not to be ignored in your setup.
I think the .tmp file should not start to upload until it is complete and renamed to .backup

Feels like a misconfiguration in Nextcloud instead of a problem with Signal

**Comment by mueslo** [comment]
> for debugging purposes, did you try to keep Nextcloud disabled while Signal performs the whole backup operation?
> it feels like some kind of conflict happening when Signal renames the .tmp file, which should be excluded from syncing in Nextcloud default config , but appears not to be ignored in your setup.
> I think the .tmp file should not start to upload until it is complete and renamed to .backup
> 
> Feels like a misconfiguration in Nextcloud instead of a problem with Signal

You cannot configure this behaviour in the Nextcloud Android app, so it can't be a misconfiguration of Nextcloud.

**Comment by Lion-box** [comment]
> ...since it is not a regular file system destination.

which could easily be the reason why Signal appears not to be able to properly rename the file.
I'd suggest to try to backup to a "regular" folder and add that folder to Nextcloud Files

**Comment by mueslo** [comment]
You seem to have a misunderstanding of how Nextcloud on Android works. It doesn't just synchronize the underlying file system like on Android, it only synchronizes on demand. So if I save it there, it won't be automatically synchronized to Nextcloud.

Signal supports selecting Nextcloud as a backup target via some sort of special purpose FS. So it should be fixed (or not supported in the first place). Telling me to just save it to a regular file system location is pointless, as that is what this issue is exactly NOT about.

**Comment by dnr** [comment]
Good timing, I _just_ ran into this. I set up Nextcloud on my own server, and checked that it works with the android Nextcloud app. I also successfully saved a file from another unrelated app using the Nextcloud SAF provider. When I tried to make a Signal backup manually, I saw:
- Signal started counting up messages (presumably it's writing to a local file managed by the Nextcloud app)
- Nextcloud popped up a notification saying that it was uploading the file
- Very quickly, the notification disappeared, no error was displayed, but the Signal app said no backup was made. This happened faster than the file could plausibly have been uploaded.
- No files are present in Nextcloud. The Signal debug logs contain a message `LocalBackupJobApi29: Backup failed. Deleted temp file`.

The Nextcloud server logs have:
```
"PROPFIND /remote.php/webdav/Signal/ HTTP/1.1" 207 1421 "-"
"PROPFIND /remote.php/webdav/Signal/ HTTP/1.1" 207 1648 "-"
"PUT /remote.php/webdav/Signal/.backupaeb93825-ebe5-456f-a881-15030cc55490.tmp HTTP/1.1" 201 872 "-"
"PROPFIND /remote.php/webdav/Signal/ HTTP/1.1" 207 1421 "-"
"PROPFIND /remote.php/webdav/Signal/ HTTP/1.1" 207 2595 "-"
"GET /remote.php/webdav/Signal/.backupaeb93825-ebe5-456f-a881-15030cc55490.tmp HTTP/1.1" 200 835 "-"
"GET /index.php/204 HTTP/1.1" 204 1172 "-"
"HEAD /remote.php/webdav/Signal/signal-2020-12-07-16-03-00.backup HTTP/1.1" 404 537 "-"
"HEAD /remote.php/webdav/Signal/.backupaeb93825-ebe5-456f-a881-15030cc55490.tmp HTTP/1.1" 200 816 "»
"MOVE /remote.php/webdav/Signal/.backupaeb93825-ebe5-456f-a881-15030cc55490.tmp HTTP/1.1" 201 668 "»
"MKCOL /remote.php/dav/uploads/nc/6a3655c4ed783baa83f4f1f438593ae4 HTTP/1.1" 201 548 "-"
"PROPFIND /remote.php/dav/uploads/nc/6a3655c4ed783baa83f4f1f438593ae4 HTTP/1.1" 207 1481 "-"
"DELETE /remote.php/webdav/Signal/signal-2020-12-07-16-03-00.backup HTTP/1.1" 204 492 "-"
```

Watching the filesystem on the server, it looks like the file never actually gets uploaded.

My Nextcloud "activity log" looks roughly like the one that @mueslo posted.

So it does look like Signal is incorrectly determining that the backup failed, and then deleting the file, before it can get uploaded to Nextcloud. It seems like this might be due to incorrect usage of the storage access framework, perhaps assuming a level of consistency that's true for the local filesystem but not for remote SAF providers?


Nextcloud version 3.14.1
Signal version 4.79.3

**Comment by greyson-signal** [comment]
We really need debuglogs from Signal to do anything. FWIW all we do is write a file to the location specified. If we're aborting, it means we're getting an IOException during write. Logs would let us know specifically what's happening.

**Comment by mueslo** [comment]
https://debuglogs.org/a51d3459bd49963909b4d21fe41d9b2e6384a38f3271ca4ef891c90258964ed6

**Comment by greyson-signal** [comment]
Looks like we aren't properly logging the specific exception :facepalm: I've added additional logging to 5.0.3, apologies. That should be going to beta later today, and to production later this week. Once you get that release, if you could post another log after a backup fails, that'd be very much appreciated. Thanks again!

**Comment by mueslo** [comment]
Will do.

**Comment by mueslo** [comment]
@greyson-signal here is the same log on signal 5.0.4: https://debuglogs.org/899dfc8d5c5bc502a11c16c211050301c2dd44eca7713f6f6a4c4869a9fa2a57

Doesn't seem more verbose to me, though.

**Comment by haarp** [comment]
Running into the same issue. Occasionally, empty `.backupfoobarbaz.tmp` files end up being uploaded, which to me strongly points towards the temporary-file-dance being the culprit here.

**Comment by SubhrajyotiSen** [comment]
Ran into the same issue here. Seems like NextCloud starts uploading the file before Signal app finishes writing it. I will try compilng from source and adding extra logs to debug this

**Comment by haarp** [comment]
I've encountered other apps encountering the same bug with Nextcloud's SAF, which indicates it is a bug within Nextcloud. I have opened nextcloud/android#7846 for this.

**Comment by sercxanto** [comment]
There was an issue in nextcloud android client 3.14.1 which prevented files being upload. It was fixed with [3.14.2](https://github.com/nextcloud/android/releases/tag/stable-3.14.2) (released on 2021-01-13): "Fix Crash Sharing files to Nextcloud via Android Apps".

Is the issue reproducible also with 3.14.2 ?

**Comment by mueslo** [comment]
Yes, for me the issue persists with Nextcloud 3.14.3 + Signal 5.2.3

**Comment by major-mayer** [comment]
I'm experiencing the same problem on Nextcloud 3.15 RC1 and with the same Signal version.
Temporary files get uploaded and later deleted, but not the final backup file.

**Comment by polizz** [comment]
Just chiming in, also seeing this.

NC 3.14.1
Signal 5.2.3

**Comment by flokno** [comment]
Same on Pixel 2, Android 11
Nextcloud 4.15.0 RC1
Signal 5.3.10

**Comment by Kalytis** [comment]
I've been running into this for months and it continues.

OnePlus 7T Pro, Android 10
Nextcloud Dev 20210130
Signal 5.3.12

**Comment by polizz** [comment]
Pardon my intrusion, I've looked at none of the code, but can see why this would happen. While a working temporary file being written to the backup location is probably not a horrible thing to do with many backing stores, in this case, the Nextcloud client **is** going to want to transfer a file it sees as new and **not changing**.

Why not avoid this entire issue - can't you write to the temp file somewhere else, say your own working area and THEN move the file when it's completely done processing. Nextcloud would most likely wait for that large file copy to finish and then start uploading like it normally does for all files. I can't see how this would adversely affect any current backup strategies/destinations either.

**Comment by Ark74** [comment]
This is a web server issue, you might want to check your nginx or apache configuration.
Most of the times files with a dot are not allowed by the web server.

On nginx look for,

```
        location ~ /\. {
                       deny all;
        }
```

And comment those out.

**Comment by polizz** [comment]
In my case they are, I've got seedvault backups uploading from the same phone to the same server with dot files.

**Comment by adrienlacombe** [comment]
Hi, I am facing this issue with Signal 5.10.8

**Comment by julianfairfax** [comment]
I'm also having this problem

**Comment by Cubevoid** [comment]
I am facing the same issue on Android 10, Signal 5.20.4, Nextcloud Android 3.16.1. I have found a (imperfect) workaround by adding a local folder on my device to the Nextcloud auto-uploads. However this means that old backups aren't deleted so it ends up taking a lot of storage space in NC.

**Comment by Lion-box** [comment]
> However this means that old backups aren't deleted so it ends up taking a lot of storage space in NC.

NC configuration can be modified to enable automatic deletion of files according to rules and tags that could be set automatically.
Have a look at the Files Retention NC app.
[This page](https://docs.nextcloud.com/server/19/admin_manual/file_workflows/retention.html), and those linked in the article, could be helpful.

**Comment by Cubevoid** [comment]
> > However this means that old backups aren't deleted so it ends up taking a lot of storage space in NC.
> 
> NC configuration can be modified to enable automatic deletion of files according to rules and tags that could be set automatically.
> Have a look at the Files Retention NC app.
> [This page](https://docs.nextcloud.com/server/19/admin_manual/file_workflows/retention.html), and those linked in the article, could be helpful.

Thanks, that was very helpful! I've used a combination of automated tagging and the file retention and it seems to work.

**Comment by Whisprin** [comment]
Dear stale bot, the issue is still relevant.

It seems to be related to how Signals treats Androids Storage Access Framework (SAF) and the assumptions it makes about it. 
Maybe creating the .tmp file in a temporary location and moving it to the final, user selected location upon completion could be a reliable, generic solution?

@UserX404 What's the reason for creating the .tmp file at all? Is this a workaround for SAF not locking files with open writes or just a way to determine incomplete backups? If the .tmp file is not used at all and the backup is written to the final destination and name .backup directly DocumentProviders would work as expected.

**Comment by wagnerflo** [comment]
Yes, still relevant. At least for me, who wants to backup his Signal chats to a WebDAV share mounted on his phone.

**Comment by haarp** [comment]
[Stale bots](https://blog.benwinding.com/github-stale-bots/) [are bad](https://news.ycombinator.com/item?id=25821517) [and discourage contribution](https://news.ycombinator.com/item?id=21388079).

**Comment by cody-signal** [comment]
While I recognize this as a valid use case, it's not something we actively support (backing up via a cloud service). To be open and honest, I don't see us taking this on. However if someone wants to come up with a solution and make a PR please feel free to tag me on it.

**Comment by TinfoilSubmarine** [comment]
So this isn't a complete alternative solution, but it does handle the automatic upload...

Nextcloud has a setting hidden away in Settings called "Auto Upload". This is set up by default to automatically detect picture/video folders and ask if you would like for them to be automatically uploaded to Nextcloud. If you go into this screen in settings though (Nextcloud -> Settings -> Auto Upload) there is an option to "Set up a custom folder" if you tap the triple dot button at the top. You can then add whatever local folder you want and have Signal store backups there.

This does not solve old backup cleanup however.

**Comment by stephanlachnit** [comment]
Would it be possible to write the tmp file to a different directory than the final backup? I think this would solve all issue, since the final backup file would just be moved to the cloud synced folder, no temporary files that get deleted or files being written to.

**Comment by bjo81** [comment]
I'm getting now strange issues when writing the backup to a folder where it get's uploaded by the Nextcloud Client and afterwards deleted. Signal tries to verify the file, does not find it and recreates a new backup. This is repeated for 2 times, so I got 3 backup files at the end.

But this solution worked for several years, so something seems to have changed.

Using Nextcloud as direct storage for the backup does not work, the backup file in Nextcloud remains at 0 bytes and I get a .backup-xyz.tmp file which has approximately half of the size of the whole backup.

**Comment by UserX404** [comment]
@bjo81
See https://github.com/signalapp/Signal-Android/issues/13559

**Comment by keponk** [comment]
could the solution simply be to create the backup (`.tmp`) file in signal's own app storage and only when it's done move it to the user's chosen folder?
