### ISSUE TITLE
Images are not displaying when trying to send someone. 

### ISSUE THREAD

**Issue by DroidNinja** [signalapp/Signal-Android#10394]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Images are not displaying when trying to send someone. 

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Images are not displaying when trying to send someone. 
**Expected result:** It should display all images.

### Screenshots

![ErNoqmvVQAI8wCe](https://user-images.githubusercontent.com/889201/104088918-4cab6000-5290-11eb-892a-7733810266ad.jpeg)

### Device info

**Device:** Oneplus 5
**Android version:** Android 10
**Signal version:** 5.0.8

### Link to debug log
https://debuglogs.org/f223ff8ca8b9c475bd4fe3fceec70fb0d6c59ebcd9a87fca5550c3998d5362de

**Comment by mmatiaschek** [comment]
I have the same issue as this and #10452 on Huawei P30 Pro, also with Android 10 and Signal 5.0.8

It's quite annoying, a guy would be great!

**Comment by gluszczykd** [comment]
Same on Signal 5.0.9 with Huawei P30 Pro Android 10

**Comment by Rutvik1999** [comment]
Same issue on Signal 5.0.9 on OnePlus 5 Android 10. Unable to view or select any image form gallery.

**Comment by blaueente** [comment]
Same on 5.0.8. on bq aquaris x2 pro Android 10. Note: I have lots of images stored in a comparably flat directory structure, and on an SD card, which might be not so fast. It is not consistent. Sometimes it works, but only for 2 images on the initial preview below the entry field. If one presses it, the editor is shown, but it is black. Then back.
Then, when switching to another app and back, no images gets loaded, and when pressing on the gallery button, every image in the gallery is black, but then suddenly after a few seconds, all images show again. In other tries, even killing and restarting signal brought the images back. But restarting the phone did bring them back. And, even when images are black, I don't have problems with other apps accessing my images.

**Comment by paulverbeke** [comment]
Same on Signal 5.1.8, Oneplus 5T, Android 10

**Comment by opdich** [comment]
Ditto Signal 5.3.7.1, Galaxy S9, Android 10

**Comment by syntron** [comment]
Is this connected to #10603 ?

I just mentioned there that I have the same issue.

Samsung S5 / LinageOS 17.1 / Android 10 / Signal 5.3.7 via Google Play Store

**Comment by Tom-Archer** [comment]
Ditto Signal 5.3.7.1, Nokia 7 Plus, Android 10

**Comment by groer99** [comment]
Same here on Signal 5.3.12, motorola one, Android 10

It works fine after a fresh restart of the phone. After some time pictures are not showing anymore - or load extremely slow. Stopping Signal and clearing cache doesn't help.

**Comment by syntron** [comment]
> It works fine after a fresh restart of the phone. After some time pictures are not showing anymore - or load extremely slow. Stopping Signal and clearing cache doesn't help.

I can confirm this; after a restart it is working for a time; my current work-around: use 'notice to myself' to check if its working (several tries needed) and if its works, forward the message (with the image)

**Comment by LeSpocky** [comment]
Looks like with Signal 5.3.12 on LineageOS 17.1 on fp2. Does not matter if I try to send an image from within Signal or share it from some other app. In the first case there are no thumbnails, those are all black. In the second case when sharing from another app a spinner is spinning indefinetly.

**Comment by agademer** [comment]
Same as @LeSpocky (Signal 5.3.12 / LineageOS 17.1 on FP2). Identical symptom. I tested after a reboot and the preview finished to appear after some times (but not for all pictures). Trying to send the image that had a preview worked.

**Comment by snajlcz** [comment]
`ThumbnailView: Not re-loading slide content://org.thoughtcrime.securesms/part/16139932xxxxx/xxl`

`FixedSizePagingController: onDataNeededAroundIndex(10) Invalidated! At beginning of load task.`

**Comment by Tom-Archer** [comment]
This seems to have improved on 5.4.8 - some of the images still appear black as you scroll around, but after a moment they do eventually load.

**Comment by syntron** [comment]
Any update on this?

**Comment by snajlcz** [comment]
On update emui 11 problem solved
P30pro

**Comment by syntron** [comment]
Could this be related to energy saving options? I noted that if I deactivate all energy saving options it works at least a little bit faster ...

**Comment by DaleBCooper** [comment]
Still an issue in latest version 5.5.5
Android 10

**Comment by Susticle** [comment]
Same problem very often on Nokia 7 plus with Android 10 and Signal 5.5.5.

**Comment by mtsokol** [comment]
Same problem on Xiaomi mi a2 lite with Android 10 and Signal 5.5.5. It basically takes a really long time (over 40 seconds) to load a gallery. After swiping up or down loading starts again.

Screenshot:
 <img src="https://i.imgur.com/JKfK0ce.png" height="500">
Logs: https://debuglogs.org/192129e4d0cd18945be6a5785442e7de8ea86066ecb0c69228b3fc80d0657acc

**Comment by syntron** [comment]
It seems to work now - however, I'm not aware of any changes which could have been the reason. Thus I will continue to observe this.

Version: 5.6.4

**Comment by Tom-Archer** [comment]
Version 5.8.6 here, definitely still not working.

**Comment by syntron** [comment]
> Version 5.8.6 here, definitely still not working.

Quite right; it is something like an on/off hopping. Today it did *not* work; a restart helps; sometimes it depends which gallery was used before ...

A real solution would be quite nice!

**Comment by jenslam** [comment]
Xiaomi 9T Pro, Same issue

**Comment by codekoenig** [comment]
Same issue here on Huawei P20, Android 10. 

Although I have to say there are a lot of performance and stability issues with other apps on P20 too since Android 10, so I fear this is an Android (v10) related issue. And Huawei is not releasing any updates anymore for those devices so we might be doomed.

**Comment by rileyrg** [comment]
@mmatiaschek same issue p30 pro.

**Comment by x-wolverine-x** [comment]
Same on Huawei P30.
Android 10
Signal 5.9.5

**Comment by mcmuller** [comment]
Same on a Nokia 5
Android 10
Signal 5.9.5

...resolves after a reboot, but problem returns after taking a photo with the Camera-app

**Comment by yausern** [comment]
Same on Lenovo P2 (P2a42)
Lineage OS 17.1
Android 10
Signal 5.9.7

Occasionally works, but usually just black...

**Comment by greyson-signal** [comment]
Hi there, reminder that the most useful thing you can provide is a debuglog. Thanks!

**Comment by yausern** [comment]
> 
> 
> Hi there, reminder that the most useful thing you can provide is a debuglog. Thanks!

Sorry about that!  Didn't know how this works.  Here is mine
https://debuglogs.org/f1577f1fcd186cefa386604882f1a031531cda8a0382b15b53cb7d6f62403120

**Comment by Tom-Archer** [comment]
And mine: https://debuglogs.org/9085c95ce4831d792283270bb430ae8d55d6ca3fa01ef260beddace07ee4890c

**Comment by groer99** [comment]
Here's mine: 

https://debuglogs.org/d1d9e95f220ea5bb72840e9e8293d5170e6915c5eb4987267f71d4dfaf7fcb06

There are a few lines with:
skia    : --- Failed to create image decoder with message 'unimplemented
Is that related?

**Comment by groer99** [comment]
This issue seems to be related with reading the EXIF tags of the pictures. I have tried deleting EXIF information from the pictures and in that case all thumbnails load instantly. As soon as EXIF data is included, thumbnails show up with a long delay. Please find attached two pictures: One with EXIF, one without.

![IMG_20210511_083550 - exif removed](https://user-images.githubusercontent.com/20140359/117770098-d403e280-b234-11eb-803b-8724042439fa.jpg)

![IMG_20210511_083550](https://user-images.githubusercontent.com/20140359/117770102-d5cda600-b234-11eb-8f76-d8a6269c8331.jpg)

**Comment by kowi4** [comment]
same here: https://debuglogs.org/50dd743e99e9da5ece44617fd8c61fd9f2bb61d56416e26e9f2c5f9c43b42b88

**Comment by DarkoVeberic** [comment]
not only the attachment preview or the gallery are full of empty thumbnails, also attaching one of such photos (sometimes) results in a grayed-out tile, like eg this
![Screenshot_20210611-164024](https://user-images.githubusercontent.com/7278812/124466211-b0719a00-dd96-11eb-842b-0db86ab4a006.png)

**Comment by sieira** [comment]
same in one plus 6, it works sometimes, although I couldn't identify on which conditions it does...

**Comment by DaleBCooper** [comment]
> same in one plus 6, it works sometimes, although I couldn't identify on which conditions it does...

It works for some time after a reboot.

**Comment by DarkoVeberic** [comment]
attaching images has become a real pain since the in-app preview and the gallery are completely dark. one has to go into the android photos app and share images with signal from there, although the sent image still appears grayed out after sending and appears correctly in the chat only after some time..

**Comment by DarkoVeberic** [comment]
sometimes just waiting a few minutes with the preview or gallery open in the app, renders them finally, so it seems like some kind of thumbnailing problem..? but it's extremely annoying and made me send a sensitive photo to a WRONG PERSON since i was just trying to  guess at which position in the preview it might be...

**Comment by DarkoVeberic** [comment]
confirmed: ifi use android "files" app to delete all "junk files" (i assume this deletes the thumbnails), i get in signal completely black image attach preview and completely black signal gallery view. leaving it open for a while (long while since my phone is not really fast) the images eventually appear. my impression is that the thumbnails are created in the wrong order: preview and gallery show most recent images first, while the thumbnailer is creating the thumbnails oldest first and therefore it takes time to reach the latest ones. this might explain why not more people are complaining, they probably have faster phones or phones with faster storage or simply their version of android does not purge thumbnails so often. is there a way you can make thumbnailer do the images shown in the preview and gallery first?

**Comment by Glasses8448** [comment]
Hi, Im here from duplicate "gallery is only partly loaded. #11435"
It seams, that "DarkoVeberic" and I have different problems, since he can send images, when selecting them from his file app and than shareing it with signal. That doesnt work in my case. When I select the picture over files-app or gallery-app and "share" it with somebody on signal, the preview picture in signal is still black (green in screenshot
), and after sending the black picture appers in the chat, with exclamation mark (!) "sending failed" [translated: orignial "Versand gescheitert"]

![signal-2021-07-06-151543](https://user-images.githubusercontent.com/53970121/124606513-42e46d00-de6d-11eb-932a-50fdd93e9e3d.png)

**Comment by Glasses8448** [comment]
https://debuglogs.org/3ba120b25d9088417d0f1742e4abd8f9ed0bf7462172046e68b9e4eb2a21574c

**Comment by DarkoVeberic** [comment]
i take it back, it's probably not the (android) thumbnailer since attaching/sharing images in any other messenger app (threema, telegram, duo, gmail chat, hangouts) everything works fine. in the gallery view i just get the top folders shown but if i enter say camera then the all-black tiles appear and, no matter how long i wait, they do not get rendered. as observed by others, a reboot of the phone makes signal work flawlessly and even more snappier as, for example, a phone with an uptime of several days. is it possible that something in signal piles up so much crap somewhere that there is then an O(n^2) or worse dependency right before imaging functions? is there some stupid caching going on which after some time makes things slower instead of faster?

**Comment by DarkoVeberic** [comment]
Issues #11244 #10603 #11212 #9082 #10624 are all related and with the same symptoms. If one could pull all these threads together it would be the most commented issue on the signal github...

**Comment by Glasses8448** [comment]
> i take it back, it's probably not the (android) thumbnailer since attaching/sharing images in any other messenger app (threema, telegram, duo, gmail chat, hangouts) everything works fine. in the gallery view i just get the top folders shown but if i enter say camera then the all-black tiles appear and, no matter how long i wait, they do not get rendered. as observed by others, a reboot of the phone makes signal work flawlessly and even more snappier as, for example, a phone with an uptime of several days. is it possible that something in signal piles up so much crap somewhere that there is then an O(n^2) or worse dependency right before imaging functions? is there some stupid caching going on which after some time makes things slower instead of faster?

I cant confirm that. On my phone the behaivour doesnt change at all, when I restart.

**Comment by codekoenig** [comment]
I still think this is Andorid 10 & derivates related. Does anyone have this issue on other major versions of Android?

**Comment by zied777** [comment]
Not cleaning cache directory can produce such behavior. Sent from my Huawei phone-------- Original message --------From: Glasses8448 ***@***.***>Date: Wed, Jul 7, 2021, 11:21 AMTo: signalapp/Signal-Android ***@***.***>Cc: Subscribed ***@***.***>Subject: Re: [signalapp/Signal-Android] Images are not displaying when trying to send someone.  (#10394)

i take it back, it's probably not the (android) thumbnailer since attaching/sharing images in any other messenger app (threema, telegram, duo, gmail chat, hangouts) everything works fine. in the gallery view i just get the top folders shown but if i enter say camera then the all-black tiles appear and, no matter how long i wait, they do not get rendered. as observed by others, a reboot of the phone makes signal work flawlessly and even more snappier as, for example, a phone with an uptime of several days. is it possible that something in signal piles up so much crap somewhere that there is then an O(n^2) or worse dependency right before imaging functions? is there some stupid caching going on which after some time makes things slower instead of faster?

I cant confirm that. On my phone the behaivour doesnt change at all, when I restart.

**Comment by groer99** [comment]
> Not cleaning cache directory can produce such behavior. Sent from my Huawei phone-------- 

No, that's not true. Cleaning cache or  reinstalling the app doesn't help.

**Comment by polaralex** [comment]
I have the same problem on an OnePlus 5 with Android 10. Happens once in a while, and I have to restart the device to make the photos show up again.

**Comment by ElucGeek** [comment]
Hi, same issue here on Mi Mix 2 chiron LineageOS18.1 Android 11 Signal 5.17.3. I use a third party gallery app of that matter (Camera roll from F-Droid). I have the issue as well if I open the image from the gallery app and share it to Signal, the picture is black and cannot be sent. Thus if I screenshot the picture I can share the screenshot. Also videos seam not affected by the bug and loaf properly. Very strange.

**Comment by narayaana** [comment]
> Issues #11244 #10603 #11212 #9082 #10624 are all related and with the same symptoms as this #10394. If one could pull all these threads together it would be the most commented issue on the signal github...

hum... so many and so many logs sent, for such a long time, and still noone assigned.

**Comment by groer99** [comment]
There are other reports of issues loading thumbnails/pictures in Android 10 using the Glide library - which I think is used here as well, isn't it?

Is this one related? https://github.com/bumptech/glide/issues/3896

Would be great if one of the developers could take this on as many (if not all) Android 10 users are affected of this.

**Comment by groer99** [comment]
As described in https://github.com/bumptech/glide/issues/3896 I have now added 

android:requestLegacyExternalStorage="true"

to the application tag, recompiled the app and the delay and black pictures are gone. Seems to work well. 

Can a developer please look into this - seems like a very easy workaround, but no idea if this would break other things.

**Comment by alex-signal** [comment]
Hi guys! We are looking into this.

> hum... so many and so many logs sent, for such a long time, and still noone assigned.

We don't assign people to issues directly on Github

> seems like a very easy workaround, but no idea if this would break other things.

The issue with the fix is that it's a stop-gap solution. However, it looks like it could be a good enough solution until we properly fix the scoped storage implementation.

**Comment by DaleBCooper** [comment]
> The issue with the fix is that it's a stop-gap solution. However, it looks like it could be a good enough solution until we properly fix the scoped storage implementation.

Yes, please give it a try until a better fix is available.
Thanks in advance!

**Comment by amicitas** [comment]
Same issue. Must restart phone to get preview back.

**Comment by yausern** [comment]
The issue persists for me.  It appears to affect images taken with the phone camera much more than downloaded or saved images from other sources.  Also, when the preview does not display in Signal, trying to share from a gallery app takes an extremely long time to load.  If the image manages to load, the attached image appears blank or as a single color in the chat.  However the receiver appears to get the image correctly.  Here is a recent debug log.

https://debuglogs.org/ad8f05f27c1ff01306127a36ef0a777c84fc86e97f4d40efa1a9fa79dc21a996

**Comment by julliannailluj** [comment]
Same issue on Huawei p30 pro, Android 10, Signal 5.22.7. It makes it usually impossible to share pictures and videos, except very small size pictures or one by one. If I give it a few minutes it will sometimes work.

**Comment by dnel** [comment]
Same, very very slow to preview photos, can work if you have patience to wait several minutes but forget about trying to send more than one photo. It's been like this for a long time.

Signal 5.25.7
Xiaomi A2
Android 10

**Comment by tbart** [comment]
Take a look at https://github.com/signalapp/Signal-Android/issues/11244#issuecomment-926976240, update your lineageos (if you use it). Also, see whether the exiftool command I mentioned there fixes it for you. This is a very strong indicator that it's an OS issue.
It'll help the devs most if you can rule out the OS/ROM.
For details, see https://gitlab.com/LineageOS/issues/android/-/issues/4000.
If this is the root cause for all these issues here, there won't be a fix if your ROM vendor does not fix the broken FUSE implementation in AOSP 11. It's not signal's fault, then.
I can only say that - apart from signal issues themselves, as I don't use signal :) - I've seen all other issues mentioned here on my LOS 18.1 device (broken or black images, crashing apps when sharing, slow gallery and image lists, etc.) and it's definitely fixed with yesterday's nightly for my device. For all apps.

**Comment by ElucGeek** [comment]
I have updated my LineageOS to latest (18.11.2021 build of 18.1) and it looks solved. It was strange that only Signal (as far as I found) was affected but at least everything looks working fine now. Thanks for all person involved in this support.

**Comment by alexandervlpl** [comment]
Months later, sharing from another gallery app (like Google Photos) is still the only solution for me. :cry:

**Comment by tbart** [comment]
And it won't change unless your ROM provider updates your existing release by backporting the fix or updates your device to Android 12.
Tell your vendor your ROM (as well as AOSP 11, which it is based upon) is broken or change to a free OS that backports the fix, like lineage for example.
Your ROM breaks your images in the sharing process, it will be really hard for signal to fix the broken images after that, so make sure your ROM gets it right in the first place.
IANAD, but I wouldn't expect any workaround from the signal devs for this issue which clearly is a (documented, fixable) bug in another product.

**Comment by clementin-bonneau-riera** [comment]
I have not seen this bug for some weeks. Seems to be fixed for me.

**Comment by q-wertz** [comment]
Still having the bug but this does not seem to be a Signal issue so maybe it can be closed

**Comment by codekoenig** [comment]
Agreed with @q-wertz this seems to be an Android 10 issue and was fixed in later versions, I don't know if at this point it is still worth investigating for a workaround. 10 is still on ~ 25 % of devices but share is declining quickly. Yet most of those still using it are likely stuck with it and are not able to get any more OS updates ... 

I personally moved on from Android to IOS because I had enough of all those update issues, but YMMV ofc.

**Comment by tbart** [comment]
This is an Android 11 (and not 10) issue, as stated above, read my comment please. FUSE has only been introduced in 11.
You don't even use Android, so please don't update issues and provide wrong info (but instead ads for other commercial products).
The more elegant solution is to choose a free OS that gets proper updates instead. People confirmed this fixes it for them.
This is an issue about Signal on *Android*, so the solution is definitely not to switch to a different architecture (you could provide this "fix" to about every OS-related bug).

**Comment by Tom-Archer** [comment]
I was experiencing this on Android 10 on the Nokia 7 plus. So it definitely was an issue on Android 10. The Nokia 7 plus long ago stopped getting OS updates and also has a locked bootloader so "upgrade to a better OS" isn't really an option.

Having said that I haven't come across the issue in a while and thumbnail loading speed does seem improved.

**Comment by q-wertz** [comment]
> I was experiencing this on Android 10 on the Nokia 7 plus. So it definitely was an issue on Android 10. The Nokia 7 plus long ago stopped getting OS updates and also has a locked bootloader so "upgrade to a better OS" isn't really an option.

Also Nokia 7 with Android 10 :+1: 
so same problems.

@tbart so either there are two (or more) issues or your assumption that the issue comes from FUSE is wrong…

Nevertheless I do not expect a fix for an outdated platform so I am kind of "fine".

**Comment by codekoenig** [comment]
> This is an Android 11 (and not 10) issue, as stated above, read my comment please. FUSE has only been introduced in 11. You don't even use Android, so please don't update issues and provide wrong info (but instead ads for other commercial products). 

For someone attacking others for posting "wrong info" and not "reading comments" you clearly seem to have missed 100s of postings here that describe this issue for Android 10. Not getting further into your rabbit hole, I just want to reiterate that this is absolutely (and foremost) an Android 10 issue and the issues users have should not be hijacked by dismissing this because might have a similar yet more nuanced issue on Android 11 too.

**Comment by Shekelmaster** [comment]
I just had this issue on a Huawei p30 Pro. Getting so tired or it that it makes me want to switch back to WhatsApp. This issue has existed for so long...

**Comment by ultimate** [comment]
Same problem here: Honor 20 Pro, Android 10, Magic-UI 4.0.0

And I agree: it's really annoying, so that I sometime use WhatsApp instead to send pictures. And the issue exists for so long (wasn't an issue when I first installed Signal but occurred first after a few months...) 😒

The only thing that helps is a phone reboot. Then, the media access works at least for a while. An app restart only fixes the problem once in a while...

**Comment by computman007** [comment]
Same issue here.

There is no explanation. Some are missing, some are not. Impossible to send the one not showing a thumbnail

Using a Samsung S21 Ultra. HEIC format enabled

![Screenshot_20220801-154809_Signal](https://user-images.githubusercontent.com/25824896/182162799-df8f7848-3716-4807-960b-7bc6844cb788.jpg)

**Comment by rajkk1** [comment]
> Same issue here.
> 
> There is no explanation. Some are missing, some are not. Impossible to send the one not showing a thumbnail
> 
> Signal 5.44.3 Using a Samsung S21 Ultra. One UI 4.1 HEIC format enabled Android 12
> 
> https://debuglogs.org/android/5.44.3/e1fdb36b9132484582453ac35a55fd11881f448cb3714e711b37bf768bed5b56
> 
> ![2022-08-01 15_55_12-182162799-df8f7848-3716-4807-960b-7bc6844cb788](https://user-images.githubusercontent.com/25824896/182164192-da4d2cc3-1f68-4a27-929b-6ca32d7f6784.png)

Same problem here! Using Signal 6.21.3 on Android 13 One UI 5.1 Samsung Galaxy S21 5G. I noticed that all the files with the missing thumbnails were greater than 5mb and all the files that were visible were less than 5mb. However this is not a problem on my friend's phone (identical Signal, Android and One UI version but on a Samsung Note20 Ultra 5G)

**Comment by alex-signal** [comment]
Are the specific images HEIC encoded? It's possible that Glide just has terrible HEIC support. I'm seeing some errors suggesting that:

```
[5.44.3] [main ] 2022-08-01 15:58:01.636 GMT+02:00 W FileViewHolder          Failed to load media.
[5.44.3] [main ] 2022-08-01 15:58:01.636 GMT+02:00 W FileViewHolder          class com.bumptech.glide.load.engine.GlideException: Failed to load resource
[5.44.3] [main ] 2022-08-01 15:58:01.636 GMT+02:00 W FileViewHolder          There were 2 causes:
[5.44.3] [main ] 2022-08-01 15:58:01.636 GMT+02:00 W FileViewHolder          com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream$InvalidMarkException(Mark has been invalidated, pos: 266189 markLimit: 5242880)
[5.44.3] [main ] 2022-08-01 15:58:01.636 GMT+02:00 W FileViewHolder          com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream$InvalidMarkException(Mark has been invalidated, pos: 266189 markLimit: 5242880)
[5.44.3] [main ] 2022-08-01 15:58:01.636 GMT+02:00 W FileViewHolder           call GlideException#logRootCauses(String) for more detail
[5.44.3] [main ] 2022-08-01 15:58:01.636 GMT+02:00 W FileViewHolder            Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{AutoCloseInputStream->Object->Drawable}, LOCAL
[5.44.3] [main ] 2022-08-01 15:58:01.636 GMT+02:00 W FileViewHolder          There were 2 causes:
[5.44.3] [main ] 2022-08-01 15:58:01.636 GMT+02:00 W FileViewHolder          com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream$InvalidMarkException(Mark has been invalidated, pos: 266189 markLimit: 5242880)
[5.44.3] [main ] 2022-08-01 15:58:01.636 GMT+02:00 W FileViewHolder          com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream$InvalidMarkException(Mark has been invalidated, pos: 266189 markLimit: 5242880)
[5.44.3] [main ] 2022-08-01 15:58:01.636 GMT+02:00 W FileViewHolder           call GlideException#logRootCauses(String) for more detail
[5.44.3] [main ] 2022-08-01 15:58:01.636 GMT+02:00 W FileViewHolder              Cause (1 of 4): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{AutoCloseInputStream->APNGDecoder->Drawable}
[5.44.3] [main ] 2022-08-01 15:58:01.636 GMT+02:00 W FileViewHolder              Cause (2 of 4): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{AutoCloseInputStream->GifDrawable->Drawable}
[5.44.3] [main ] 2022-08-01 15:58:01.636 GMT+02:00 W FileViewHolder              Cause (3 of 4): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{AutoCloseInputStream->Bitmap->Drawable}
[5.44.3] [main ] 2022-08-01 15:58:01.636 GMT+02:00 W FileViewHolder          There was 1 cause:
[5.44.3] [main ] 2022-08-01 15:58:01.636 GMT+02:00 W FileViewHolder          com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream$InvalidMarkException(Mark has been invalidated, pos: 266189 markLimit: 5242880)
[5.44.3] [main ] 2022-08-01 15:58:01.636 GMT+02:00 W FileViewHolder           call GlideException#logRootCauses(String) for more detail
[5.44.3] [main ] 2022-08-01 15:58:01.636 GMT+02:00 W FileViewHolder                Cause (1 of 1): class com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream$InvalidMarkException: Mark has been invalidated, pos: 266189 markLimit: 5242880
[5.44.3] [main ] 2022-08-01 15:58:01.636 GMT+02:00 W FileViewHolder              Cause (4 of 4): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{AutoCloseInputStream->BitmapDrawable->Drawable}
[5.44.3] [main ] 2022-08-01 15:58:01.636 GMT+02:00 W FileViewHolder          There was 1 cause:
[5.44.3] [main ] 2022-08-01 15:58:01.636 GMT+02:00 W FileViewHolder          com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream$InvalidMarkException(Mark has been invalidated, pos: 266189 markLimit: 5242880)
[5.44.3] [main ] 2022-08-01 15:58:01.636 GMT+02:00 W FileViewHolder           call GlideException#logRootCauses(String) for more detail
[5.44.3] [main ] 2022-08-01 15:58:01.636 GMT+02:00 W FileViewHolder                Cause (1 of 1): class com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream$InvalidMarkException: Mark has been invalidated, pos: 266189 markLimit: 5242880
[5.44.3] [main ] 2022-08-01 15:58:01.636 GMT+02:00 W FileViewHolder          
```

**Comment by kaefxx** [comment]
Same issue.

https://debuglogs.org/android/6.29.2/ee8c85465b7cd78fb1feb4a40d878a699618965b145e5f51edac880b43e4a267

![Screenshot_20230823_101513_org thoughtcrime securesms](https://github.com/signalapp/Signal-Android/assets/48955211/a5c1b0d1-4457-418a-929e-d63710c7c4f4)

**Comment by cody-signal** [comment]
Thanks @kaefxx , this is a slightly different issue and we are actively looking into it.

**Comment by kaefxx** [comment]
> Thanks @kaefxx , this is a slightly different issue and we are actively looking into it.

In my case it occurres when sending images which previews failed to load, so I think it is somehow connected.

**Comment by candice10x** [comment]
I had this issue with Signal App previously. In the app, I tap the (+) mark and get the message; "Once you've taken photos, you'll be able to send your recents here."    

I take my photos with my phone. Then usually I can tap the (+) mark and scroll to the right where it would say, change photos. I would tap that and then be in my photos from my phone. I could change the photos, then be able to touch to photo icon within Signal which included the new selected photos from my phone. I know how to create the photo collages but when the (+) mark gives that message mentioned above, I can't get back to the correct process.

Last time this happened, support responded and somehow all of a sudden the (+) mark started working again. Not sure how that's possible unless it's a permission related issue. But most likely user error, however I just can't figure it out. 

I was able to go into the photo albums and select photos than share with Signal. However, sometimes it works, sometimes I can add messages and other times I try sending 4-5 times without success. I was able to turn off my phone this evening and share photos without any words or messages. Just don't understand. 

Any assistance would be so very appreciated. Thank you,

**Comment by uhkeller** [comment]
This is quite frustrating. It seems to happen with HEIC images larger than about 5MB. They don't show up in the image selection dialog and can't be sent from other apps either.
I assume that this is indeed a Glide problem, see here: https://github.com/bumptech/glide/issues/4608. Maybe Signal has a timeout for image loading? Though the issue (from 2021…) also mentions some images never loading at all.

**Comment by alex-signal** [comment]
If this is an image decoding issue, I'm not sure how much we can do outside of keeping up to date on Glide. HEIC has always been hit or miss. I can check whether we have some sort of timeout set.

**Comment by uhkeller** [comment]
Maybe give the Glide devs a poke by commenting in the issue? It might boost their perception of the importance of this issue if they know how it affects Signal.
The thing is, most of your users will not care about this being due to a bug in an external library. They will just see that it doesn't work and complain that "Signal can't even send images", as people have told me to whom I have recommended the app.

**Comment by mmatiaschek** [comment]
I didn't have much problems with this anymore in the last months, even years?
However since [7.6.2](https://github.com/signalapp/Signal-Android/releases/tag/v7.6.2) released to google playstore on 1st of May it has become so bad, i basically cannot attach images anymore. I'm almost always suffering from some black images or thumbnails, often seeing nothing at all.

Could someone check what happened between 7.5 and 7.6?

[mmatiaschek](https://github.com/mmatiaschek) commented [on Jan 11, 2021](https://github.com/signalapp/Signal-Android/issues/10394#issuecomment-757584936)
> I have the same issue as this and #10452 on Huawei P30 Pro, also with Android 10 and Signal 5.0.8
> 
> It's quite annoying, a guy would be great!

i meant fix, damn autocorrect ;)

**Comment by strank** [comment]
Similar issue for me: I can select images in the gallery view (previously I also had black squares there), but the image is not displaying afterwards, before sending. It seems to depend on the image size, a 22MB image has the issue, a cropped 3MB version is fine.

**Comment by jeffrey-signal** [comment]
This issue _should_ be fixed in 7.53 (upcoming). Once it's available, please update and let us know if the problem persists! 🙂

**Comment by jeffrey-signal** [comment]
Resolved in v7.55
