### ISSUE TITLE
Personalised notification settings in groups are not working properly

### ISSUE THREAD

**Issue by error401de** [signalapp/Signal-Android#10831]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

### Bug description
I'm using the German UI so I hope I translate the settings correctly.
"Personalised notifications" setting in groups are not working properly. "Vibration" is turned off in UI, still the phone vibrates when messages are coming in. The only alternative is to mute the full group bun in that case you won't receive any notifications.

### Steps to reproduce
- Open a group (i tested with a group of the new type)
- Navigat to "Group Settings"
- Navigate to "Personalised notification"
- Activate them
- Per default "Notification tone" is set to "Standard" and "Vibration" is turned off
- Turn off display
- Receive a message in that group
- Phone still vibrates

**Actual result:** Phones vibrates
**Expected result:** It shouldn't

### Device info
**Device:** Samsung Galaxy S9
**Android version:** 10
**Signal version:** 5.2.3

**Comment by fumiakiy** [comment]
I was able to "kind of" reproduce the issue and I believe it's not a bug in Signal. But I might be looking at something different from what @error401de  was seeing/feeling, in which case just ignore.

**What I did:**

I turned **on** the vibration in the group settings > custom notifications, then turned off the phone screen. When I received a message to the group, the phone vibrated in a standard pattern. So far so good.

I opened Signal, went to the same group settings > custom notifications and turned **off** the vibration this time. I turned off the phone screen again. When I received a message to the group again, the phone *did vibrate*, but in a different, more subtle way. This might be what @error401de  is seeing/feeling. If it was not, apologies; ignore my comment here.

It turned out that I was able to turn off the subtle vibration by going to the Android settings > Accessibility > Vibration & haptic strength. My phone doesn't vibrate any more when I receive a message to the group after I turned off the vibration there.

**My Device:**

Essential PH-1
Android 10
Signal 5.3.6

**Comment by bluumb** [comment]
Hi @alan-signal,

I have the exact same issue as @error401de. Debuglogs are attached. I tested it with a group around 22:45 - 23:00 o'clock.

**Comment by a-d-collins** [comment]
Quick disclaimer: I'm new to this codebase.

My, not yet tested, theory is that AbstractNotificationBuilder.setAlarms() is related to this behavior. https://github.com/signalapp/Signal-Android/blob/e95bb9cb0fe8c463db723e5fa21ea9b164a87a24/app/src/main/java/org/thoughtcrime/securesms/notifications/AbstractNotificationBuilder.java#L50

setAlarms() is responsible for setting the ringtone and vibration for a specific notification, and, in its current iteration, it does not seem to properly handle the case when vibration is disabled by the user in the group settings page.

From what I can tell, setAlarms() will set vibrations to the default when vibrations are:

1. enabled by user in the group settings or
2. set to default in the group settings.

However, there is no logic for expressly disabling vibrations. If the AbstractNotificationBuilder, or some related class in the notification pipeline, disabled vibrations by default, then the current logic would work fine.

I will test this to confirm my theory.

@alan-signal what are your thoughts?

**Comment by error401de** [comment]
Hi @greyson-signal / @alan-signal,
is there any chance you could check @a-d-collins approach?
Thanks!

**Comment by cody-signal** [comment]
Hope to have a fix for this in 5.14, thanks for your patience and sorry for the radio silence from our end.

**Comment by error401de** [comment]
Hi @cody-signal,
currently running 5.14.5, issue still persists.

**Comment by error401de** [comment]
@greyson-signal / @alan-signal any update on this?

**Comment by cody-signal** [comment]
We pushed a follow up fix to this a few releases ago, is it still happening? If so, can you provide a fresh debug log?

**Comment by error401de** [comment]
@cody-signal I just rechecked and it's not even possible anymore to toggle the switch for vibration off.

- Open a group
- Open settings
- Sounds & Notifications
- Personalised  notifications
- Activate it
- Vibration will be set to "on" automatically
- Turn vibration off
- Go back to previous screen
- Open settings again
- You will see vibration is turn on again

I was able to replicate this behaviour from 2 different phones (Galaxy S9 & S6)

**Comment by cody-signal** [comment]
Thanks for the bump, thought this was fixed, but yeah, it's obviously not for the UI.

Does the notification still vibrate though? When I turn it on and then off for a group, and leave, I no longer get vibrates on the group.

**Comment by error401de** [comment]
Oh, true, it's only the UI! Seems like after the actual fix the default setting was set to vibrate, which is why I still saw the behaviour. If i switch it off it actually doesn't vibrate, no matter what the UI says.

**Comment by error401de** [comment]
@cody-signal / @alan-signal  / @greyson-signal I just recognized the issue is fully back. "Vibration" toggle is off for some groups, still phone is vibrating on notifications.
I was able to reproduce it on my Samsung Galaxy S21 with Signal 5.27.13

**Comment by cody-signal** [comment]
Please provide an updated debuglog.

**Comment by error401de** [comment]
Thanks for following up @cody-signal ! Is there any possibility to send you the log without sharing it here publicly?

**Comment by cody-signal** [comment]
You can email me at cody@signal.org

**Comment by error401de** [comment]
Done, thank you so much!

**Comment by error401de** [comment]
Hi @cody-signal,
did you already have a chance to look at this?
Thx!

**Comment by error401de** [comment]
Yes, this is still relevant and I did not hear back from Signal.

**Comment by error401de** [comment]
Still open, still no answer from @cody-signal to my logs.

**Comment by alex-signal** [comment]
There's a beta out now that should be directing Android 11/12 users to the device notification settings for a given conversation rather than using the in-app settings, which should resolve this issue.

**Comment by error401de** [comment]
Hi @alex-signal,
thanks for the response! Can you estimate when it will be released for the stable channel?
Also: Is it possible to opt in and later out of the beta channel without reinstalling the app and therefore losing my message history?

**Comment by cody-signal** [comment]
Yes, you can opt-in and then out of the beta, you'll still have the beta apk until a later prod version is pushed. As in, beta is 5.38.2, so you can temporarily switch to that, but you won't be able to then switch right back to current prod, you'll have to wait until some version of 5.38.2+ is promoted to production to be as if you never left the stable channel.

**Comment by error401de** [comment]
It's working in the beta, thanks a lot!
