### ISSUE TITLE
App crash after opening an old conversation from a person who was on Signal, left Signal, and re-joined.

### ISSUE THREAD

**Issue by alexrelis** [signalapp/Signal-Android#11259]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

### Bug description
The app crashes when I open an old conversation from a person who was on Signal, left Signal, and re-joined. The crash began after I was composing a message to said person in the old conversation at the exact same time she re-registered her Signal account.

### Steps to reproduce
- Person A and Person B become Signal users, Person A uses an Android 11 device, while Person B uses an iOS device (though B's device may or may not matter in this situation).
- Person B unregisters Signal account later on, as a result, Person A uses SMS to communicate to person B (still through the Signal app).
- While Person A composes a message to Person B through SMS, Person B decided to register for Signal again. As a result, Person A is kicked out of the conversation and sees a new conversation with a message like "Session reset".
- If Person A taps on the old conversation, the app immediately crashes.

**Actual result:** App crashes
**Expected result:** The conversation should load and you should be able to view the messages

### Device info
**Device:** Oneplus 7T
**Android version:** 11
**Signal version:** 5.9.5 (Bug occurred in previous version as well)

### Link to debug log
https://debuglogs.org/1d256b8108a8ba66119c7ae4dee512ed7d68d57a013fb045c87cb1812ccf6519

### Other things to note
The old conversation loads fine on Signal Desktop (flatpak, GNU/Linux), just without the SMS messages of course.

**Comment by cody-signal** [comment]
Should be fixed on in latest beta. You can get it via https://support.signal.org/hc/en-us/articles/360007318471-Signal-Beta or wait for it to come to production.

Thanks for reporting.

**Comment by alexrelis** [comment]
I've updated to 5.9.6 in the stable channel and that did not fix the issue at. Can you reference the bug that was fixed?

**Comment by greyson-signal** [comment]
@alexrelis It was fixed in 5.10.3. This release is still in beta.
