### ISSUE TITLE
Crash when exporting Media

### ISSUE THREAD

**Issue by Nisc3d** [signalapp/Signal-Android#11870]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I want to export Pictures and Videos from a group. It tells me it's 3710 files (3,3GB). After exporting about 80 files it crashes every time. I have enough free space (over 100GB).

### Steps to reproduce
- mark all images/videos in the media tab
- tap save
- after a few seconds signal crashes

**Actual result:** Signal crashes
**Expected result:** It should export all images and videos

### Device info
**Device:** Asus Zenfone 8
**Android version:** 11
**Signal version:** 5.28.5

### Link to debug log
https://debuglogs.org/20fdddbf1850393fa697f221e71902b4803315570b7ebdeb0ae2c235275036c9

**Comment by greyson-signal** [comment]
This was addressed in 5.28.7, currently in beta. Thanks!

**Comment by Nisc3d** [comment]
@greyson-signal sadly it still crashes on 5.28.10.
New debug log: https://debuglogs.org/1301c4047c804070dff30c8cd1354ea4324b42169b3c2d7ca28f5cd7383398c3
