### ISSUE TITLE
Silent crash when restoring a large backup

### ISSUE THREAD

**Issue by janvlug** [signalapp/Signal-Android#11952]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I try to restore a 3 days old 7.7GB backup file.
Signal asks me for the pin and starts restoring. Around message 7500 Signal crashes.

### Link to debug log
Unfortunately, it looks like it is not possible to provide a debug log when Signal is not fully set up yet. If it can be done, please let me know.

**Comment by UserX404** [comment]
You should be able to get a debug log by tapping the display 8 times quickly on its welcome screen.

**Comment by janvlug** [comment]
Thanks.
Here is a debug log:
https://debuglogs.org/fffc8669d58222fc7b5b9e887bfc842cbbdaf9dca20d2fd3391c872339118ac5

**Comment by janvlug** [comment]
Snippet from the log
```
[5.30.5] [1108 ] 2022-02-02 22:03:40.212 GMT+01:00 W FullBackupImporter: Bad MAC for attachment 1587401836685! Can't restore it.
[5.30.5] [1108 ] 2022-02-02 22:03:40.212 GMT+01:00 W FullBackupImporter: org.thoughtcrime.securesms.backup.FullBackupImporter$BadMacException
[5.30.5] [1108 ] 2022-02-02 22:03:40.212 GMT+01:00 W FullBackupImporter: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readAttachmentTo(FullBackupImporter.java:374)
[5.30.5] [1108 ] 2022-02-02 22:03:40.212 GMT+01:00 W FullBackupImporter: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.processAttachment(FullBackupImporter.java:171)
[5.30.5] [1108 ] 2022-02-02 22:03:40.212 GMT+01:00 W FullBackupImporter: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:104)
[5.30.5] [1108 ] 2022-02-02 22:03:40.212 GMT+01:00 W FullBackupImporter: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:76)
[5.30.5] [1108 ] 2022-02-02 22:03:40.212 GMT+01:00 W FullBackupImporter: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:263)
[5.30.5] [1108 ] 2022-02-02 22:03:40.212 GMT+01:00 W FullBackupImporter: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:254)
[5.30.5] [1108 ] 2022-02-02 22:03:40.212 GMT+01:00 W FullBackupImporter: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
[5.30.5] [1108 ] 2022-02-02 22:03:40.212 GMT+01:00 W FullBackupImporter: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[5.30.5] [1108 ] 2022-02-02 22:03:40.212 GMT+01:00 W FullBackupImporter: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
[5.30.5] [1108 ] 2022-02-02 22:03:40.212 GMT+01:00 W FullBackupImporter: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[5.30.5] [1108 ] 2022-02-02 22:03:40.212 GMT+01:00 W FullBackupImporter: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[5.30.5] [1108 ] 2022-02-02 22:03:40.212 GMT+01:00 W FullBackupImporter: 	at java.lang.Thread.run(Thread.java:923)
[5.30.5] [1108 ] 2022-02-02 22:03:40.212 GMT+01:00 W FullBackupImporter: 
[5.30.5] [1108 ] 2022-02-02 22:03:40.242 GMT+01:00 E SignalUncaughtException: 
[5.30.5] [1108 ] 2022-02-02 22:03:40.242 GMT+01:00 E SignalUncaughtException: java.lang.RuntimeException: An error occurred while executing doInBackground()
[5.30.5] [1108 ] 2022-02-02 22:03:40.242 GMT+01:00 E SignalUncaughtException: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
[5.30.5] [1108 ] 2022-02-02 22:03:40.242 GMT+01:00 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
[5.30.5] [1108 ] 2022-02-02 22:03:40.242 GMT+01:00 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
[5.30.5] [1108 ] 2022-02-02 22:03:40.242 GMT+01:00 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
[5.30.5] [1108 ] 2022-02-02 22:03:40.242 GMT+01:00 E SignalUncaughtException: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
[5.30.5] [1108 ] 2022-02-02 22:03:40.242 GMT+01:00 E SignalUncaughtException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[5.30.5] [1108 ] 2022-02-02 22:03:40.242 GMT+01:00 E SignalUncaughtException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[5.30.5] [1108 ] 2022-02-02 22:03:40.242 GMT+01:00 E SignalUncaughtException: 	at java.lang.Thread.run(Thread.java:923)
[5.30.5] [1108 ] 2022-02-02 22:03:40.242 GMT+01:00 E SignalUncaughtException: Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=0 srcPos=-10 dst.length=10 dstPos=0 length=10
[5.30.5] [1108 ] 2022-02-02 22:03:40.242 GMT+01:00 E SignalUncaughtException: 	at java.lang.System.arraycopy(System.java:524)
[5.30.5] [1108 ] 2022-02-02 22:03:40.242 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:390)
[5.30.5] [1108 ] 2022-02-02 22:03:40.242 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:330)
[5.30.5] [1108 ] 2022-02-02 22:03:40.242 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:97)
[5.30.5] [1108 ] 2022-02-02 22:03:40.242 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:76)
[5.30.5] [1108 ] 2022-02-02 22:03:40.242 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:263)
[5.30.5] [1108 ] 2022-02-02 22:03:40.242 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:254)
[5.30.5] [1108 ] 2022-02-02 22:03:40.242 GMT+01:00 E SignalUncaughtException: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
[5.30.5] [1108 ] 2022-02-02 22:03:40.242 GMT+01:00 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[5.30.5] [1108 ] 2022-02-02 22:03:40.242 GMT+01:00 E SignalUncaughtException: 	... 4 more
[5.30.5] [1108 ] 2022-02-02 22:03:40.242 GMT+01:00 E SignalUncaughtException: 
```

**Comment by janvlug** [comment]
See also #8355 and #9791.

**Comment by cody-signal** [comment]
Sorry about that @axatbhardwaj 

We're tracking a couple tickets around backup creation and importing. The snippet above by @janvlug is an corrupted backup file that can't be recovered in app.

We are planning to add some backup creation verification to help with this kind of thing.

**Comment by axatbhardwaj** [comment]
Thank you for replying apparently my friend is also facing the same issue, his backup stuck after restoring 6000 messages and now he can't restore 

this was just FYI, keep up the good work :smile:

**Comment by skickar** [comment]
Also having this issue restoring a 65gb backup, crashes around message 5k,

**Comment by skickar** [comment]
This also occurs when using the "transfer from Android device" option. The entire process completes, and then Signal silently crashes. When I open it again, it starts like I've never opened it before and the transfer or backup has to start from scratch.

That means both "restore from backup" and "transfer from Android device" options silently crash after transferring/loading the entire backup file or transferring the database.

I have reinstalled signal multiple times. There seems to be no way to reasonably transfer a backup.

I've have wasted about 10 hours trying to transfer this backup, so some idea of what's going on would be helpful.

Debug log: https://debuglogs.org/android/5.34.4/d262fb417e4030109718da4d74769b693c5d8708d209f519cca73027b9fb474a

**Comment by skickar** [comment]
Just an update, I noticed there was a signal update and can confirm it fixed the Android Account Transfer feature. Didn't test the restore from backup, but the crash on the account transfer doesn't occur anymore.

**Comment by alex-signal** [comment]
@skickar I see there's a separate ticket open for that double space issue you mentioned, so I'm going to close this one out.

**Comment by alex-signal** [comment]
reopening because I bothered to go back and read the original issue.

**Comment by hfirdaus** [comment]
Also having the same issue, with a 2.3 gb backup that crashes when restoring from file at 3500 messages each time. The debug log looks identical to the one posted in the snippet above. Have tried reinstalling, clearing caches, etc., to no avail. I don't know what the Signal version was when I created my backup, but the version where I am restoring it is 5.36.3. Would really love to get 3 years worth of messages and media back, so any help is appreciated!

**Comment by rflexor** [comment]
Same here, 4 Gig, crashes reliably at msg 6700. signal version 5.36.6, Pixel 4 with Sec Update March as well as with May.
Backup was taken on same device without errors/interruptions. Did a factory reset between backup and restore attempt.

```
05-13 08:53:47.934 26284 26313 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
05-13 08:53:47.934 26284 26313 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 26284
05-13 08:53:47.934 26284 26313 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
05-13 08:53:47.934 26284 26313 E AndroidRuntime:        at android.os.AsyncTask$4.done(AsyncTask.java:415)
05-13 08:53:47.934 26284 26313 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
05-13 08:53:47.934 26284 26313 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
05-13 08:53:47.934 26284 26313 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
05-13 08:53:47.934 26284 26313 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
05-13 08:53:47.934 26284 26313 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-13 08:53:47.934 26284 26313 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-13 08:53:47.934 26284 26313 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:920)
05-13 08:53:47.934 26284 26313 E AndroidRuntime: Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=0 srcPos=-10 dst.length=10 dstPos=0 length=10
05-13 08:53:47.934 26284 26313 E AndroidRuntime:        at java.lang.System.arraycopy(Native Method)
05-13 08:53:47.934 26284 26313 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImpor
ter.java:419)
05-13 08:53:47.934 26284 26313 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImpor
ter.java:359)
05-13 08:53:47.934 26284 26313 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:110)
05-13 08:53:47.934 26284 26313 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:89)
05-13 08:53:47.934 26284 26313 E AndroidRuntime:        at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackup
Fragment.java:291)
05-13 08:53:47.934 26284 26313 E AndroidRuntime:        at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackup
Fragment.java:282)
05-13 08:53:47.934 26284 26313 E AndroidRuntime:        at android.os.AsyncTask$3.call(AsyncTask.java:394)
05-13 08:53:47.934 26284 26313 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-13 08:53:47.934 26284 26313 E AndroidRuntime:        ... 4 more
```

**Comment by rostmodern** [comment]
Can confirm. Tried to import a lager backup from my old phone. 
New phone displayed a "wrong key" message & after starting the processing for for the first 5000 messages died on me.

possible work around:
Tried different backup files, finally it worked with a slighty different version of the backup file(if you have your old phone w/ signal running, you can create backups in settings).

Not sure if this fully works, just my 2 cents.
archive size was about 7 GB. Importing device was a new Pixel phone w/ signal version 5.37.4 

> Same here, 4 Gig, crashes reliably at msg 6700. signal version 5.36.6, Pixel 4 with Sec Update March as well as with May. Backup was taken on same device without errors/interruptions. Did a factory reset between backup and restore attempt.
> 
> ```

> **EDIT^2**: I am trying https://github.com/bepaald/signalbackup-tools to fix the issue. That gave me:
> 
> ```
> Reading backup file...
> FRAME 6772 (077.4%)... Failed to read next frame (0 bytes at filepos 3355726448)
> Starting bruteforcing offset to next valid frame... starting after: 3355726448
> ```
> 
> This will take some time though, until the remaining 700MB are bruteforced. **EDIT^3**: but it ultimately worked and I could import the backup.

dont know how this relates, maybe some corruption issue?
anyways, i'm shure that working backups are top priority for the developers.

btw: the phone2phone conect(WiFi-Direct?) also didnt work for me.

**Comment by janvlug** [comment]
Someone, to whom I recommended (pushed) to use Signal, is now also running into this issue when switching to a new phone. She has a backup of 2.03 gb. Here is the [debug log](https://debuglogs.org/android/5.41.11/3bd1ae7e29fe5ac08f55e1bb4ce7ed32657a4c7a515e497eebc2a7b39d7ea8f0). Both transferring the backup, and the [transfer](https://support.signal.org/hc/en-us/articles/360007059752-Backup-and-Restore-Messages#android_transfer) method do not work.

For me it is kind of embarrassing that someone whom I kind of pushed to use Signal is loosing all her history now, especially because she kind of decided to stay on Android instead of moving to iOS to have a smart transfer of apps (of which Signal history is particular important).

@cody-signal, @alex-signal: Is there anything we can do to try to help fixing this issue and saving the history? Not only for this specific case, but also for other people that might run into this issue, but who do not report it here.

**Comment by janvlug** [comment]
I forgot to mention that the SIM card was still in the old phone when trying to do the transfer and attempt to import the backup.

**Comment by janvlug** [comment]
Thanks for the tip. She will try to make a new backup in airplane mode, and try to transfer it. I will let know the results later.

Here some screenshots of a previous attempt to restore the backup:
![image](https://user-images.githubusercontent.com/5903208/176744709-f56621ed-b701-4e3c-bc00-be08a71d7d40.png) ![image](https://user-images.githubusercontent.com/5903208/176744749-2776cc4a-9120-468b-afd8-4f703e18ecfe.png)

> Can you get the two devices connected and have them show a code to verify?

She said: No, they see each other (because she has to give allowance for access on one of the phones), but they do not proceed further than something like: "looking for devices".

**Comment by janvlug** [comment]
> She will try to make a new backup in airplane mode, and try to transfer it. I will let know the results later.

The transfer of the backup made in airplane mode worked. Thanks a lot for this tip @cody-signal, you made two people happy today!

**Comment by turlyyy** [comment]
I got same error today when I tried restore my backup

```
type: crash
osVersion: google/oriole/oriole:13/...:user/release-keys
package: org.thoughtcrime.securesms:111502
process: org.thoughtcrime.securesms

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	at [[ ↑↑ Original Trace ↑↑ ]].(:0)
	at [[ ↓↓ Exception Message ↓↓ ]].(:0)
	at An error occurred while executing doInBackground().(:0)
Caused by: net.zetetic.database.sqlcipher.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
	at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at net.zetetic.database.sqlcipher.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:767)
	at net.zetetic.database.sqlcipher.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:758)
	at net.zetetic.database.sqlcipher.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:70)
	at net.zetetic.database.sqlcipher.SQLiteDatabase.executeSql(SQLiteDatabase.java:1994)
	at net.zetetic.database.sqlcipher.SQLiteDatabase.execSQL(SQLiteDatabase.java:1951)
	at org.thoughtcrime.securesms.backup.FullBackupImporter.processStatement(FullBackupImporter.java:155)
	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:99)
	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:73)
	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:288)
	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:279)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by zachpetersen** [comment]
I'm experiencing the same issue currently while attempting to transfer and/or restore backup to a new Pixel 7 Pro. Really not looking forward to losing all my history again as this is the second time this has happened for me.

@cody-signal I've tried with Airplane Mode on the old device and creating a new backup under those conditions. No joy. Error is the same as shown above. I've tried with the SIM in both devices.

**Comment by zachpetersen** [comment]
> valid

@alex-signal @cody-signal any possibility of getting someone to review this? I also have a support email going but haven't gotten any traction. Thanks!

**Comment by greyson-signal** [comment]
As far as I'm aware, these classes of issues (foreign keys and bad streams) should be fixed moving forward.

**Comment by wavemobileDev** [comment]
I am seeing issues moving to a Pixel7 from a 6a. I culled my backup, rekeyed it and tried the flight mode suggestion. Nothing works.

**Comment by alex-signal** [comment]
Hi! Unfortunately without a debug log there's not much we can investigate. You can submit one from registration here: https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports

As greyson mentioned, this should be fixed on newer versions of Signal

**Comment by lukect** [comment]
Still happening version 6.11.2:
```
--------- beginning of crash
02-09 13:50:09.232  7907  7987 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
02-09 13:50:09.232  7907  7987 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 7907
02-09 13:50:09.232  7907  7987 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
02-09 13:50:09.232  7907  7987 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
02-09 13:50:09.232  7907  7987 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
02-09 13:50:09.232  7907  7987 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
02-09 13:50:09.232  7907  7987 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
02-09 13:50:09.232  7907  7987 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
02-09 13:50:09.232  7907  7987 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
02-09 13:50:09.232  7907  7987 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
02-09 13:50:09.232  7907  7987 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
02-09 13:50:09.232  7907  7987 E AndroidRuntime: Caused by: net.zetetic.database.sqlcipher.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
02-09 13:50:09.232  7907  7987 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
02-09 13:50:09.232  7907  7987 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:767)
02-09 13:50:09.232  7907  7987 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:758)
02-09 13:50:09.232  7907  7987 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:70)
02-09 13:50:09.232  7907  7987 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.executeSql(SQLiteDatabase.java:1994)
02-09 13:50:09.232  7907  7987 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.execSQL(SQLiteDatabase.java:1951)
02-09 13:50:09.232  7907  7987 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.processStatement(FullBackupImporter.java:149)
02-09 13:50:09.232  7907  7987 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:94)
02-09 13:50:09.232  7907  7987 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:68)
02-09 13:50:09.232  7907  7987 E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:288)
02-09 13:50:09.232  7907  7987 E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:279)
02-09 13:50:09.232  7907  7987 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
02-09 13:50:09.232  7907  7987 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
02-09 13:50:09.232  7907  7987 E AndroidRuntime: 	... 4 more
```

How can I repair the backup or at least recover the media?

**Comment by TheGorf** [comment]
So just today I have this error. Mine won't even open the backup that I made moments before resetting my phone. So I'm completely screwed on restoring my signal data.

https://debuglogs.org/android/6.28.6/28e738b2a48a4e1e6c7791abb8c22d263bc6b2bfcafb0aa20d64c7d212231933

**Comment by cody-signal** [comment]
HI @TheGorf it seems you are encounter a related "negative array size" crash. We're looking into it

**Comment by Huii** [comment]
I ran into the same issue today. Everything was working fine but suddenly Signal stopped working out of the blue. Now, it wants me to restore a backup. The current backup was made today but importing it simply stops the app.

I use eOs, which is a fork of LineageOs. You can find the log file attached. The backup is roughly 2.3 GB large. Thank you very much for your help in advance.
[log.txt](https://github.com/signalapp/Signal-Android/files/12527741/log.txt)

**Comment by muteNut** [comment]
Hey, I encountered the same problem as well. The backup is roughly 2.3 GB and I thought it might be a good idea to reinstall Signal, as it kept crashing while trying to reply in group chats (#13167). After trying to import the backup file, I got a similar error:

```
--------- beginning of crash
09-12 12:32:33.417  6802 13210 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
09-12 12:32:33.417  6802 13210 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 6802
09-12 12:32:33.417  6802 13210 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
09-12 12:32:33.417  6802 13210 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
09-12 12:32:33.417  6802 13210 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
09-12 12:32:33.417  6802 13210 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
09-12 12:32:33.417  6802 13210 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
09-12 12:32:33.417  6802 13210 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
09-12 12:32:33.417  6802 13210 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
09-12 12:32:33.417  6802 13210 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
09-12 12:32:33.417  6802 13210 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
09-12 12:32:33.417  6802 13210 E AndroidRuntime: Caused by: java.lang.NegativeArraySizeException: -1580913911
09-12 12:32:33.417  6802 13210 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.BackupRecordInputStream.readFrame(BackupRecordInputStream.java:164)
09-12 12:32:33.417  6802 13210 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.BackupRecordInputStream.readFrame(BackupRecordInputStream.java:92)
09-12 12:32:33.417  6802 13210 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:93)
09-12 12:32:33.417  6802 13210 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:71)
09-12 12:32:33.417  6802 13210 E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:292)
09-12 12:32:33.417  6802 13210 E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:282)
09-12 12:32:33.417  6802 13210 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
09-12 12:32:33.417  6802 13210 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
09-12 12:32:33.417  6802 13210 E AndroidRuntime: 	... 4 more
09-12 12:32:33.417  6802 13210 E SignalUncaughtException: java.lang.RuntimeException: An error occurred while executing doInBackground()
09-12 12:32:33.417  6802 13210 E SignalUncaughtException: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
09-12 12:32:33.417  6802 13210 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
09-12 12:32:33.417  6802 13210 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
09-12 12:32:33.417  6802 13210 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
09-12 12:32:33.417  6802 13210 E SignalUncaughtException: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
09-12 12:32:33.417  6802 13210 E SignalUncaughtException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
09-12 12:32:33.417  6802 13210 E SignalUncaughtException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
09-12 12:32:33.417  6802 13210 E SignalUncaughtException: 	at java.lang.Thread.run(Thread.java:1012)
09-12 12:32:33.417  6802 13210 E SignalUncaughtException: Caused by: java.lang.NegativeArraySizeException: -1580913911
09-12 12:32:33.417  6802 13210 E SignalUncaughtException: 	at org.thoughtcrime.securesms.backup.BackupRecordInputStream.readFrame(BackupRecordInputStream.java:164)
09-12 12:32:33.417  6802 13210 E SignalUncaughtException: 	at org.thoughtcrime.securesms.backup.BackupRecordInputStream.readFrame(BackupRecordInputStream.java:92)
09-12 12:32:33.417  6802 13210 E SignalUncaughtException: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:93)
09-12 12:32:33.417  6802 13210 E SignalUncaughtException: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:71)
09-12 12:32:33.417  6802 13210 E SignalUncaughtException: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:292)
09-12 12:32:33.417  6802 13210 E SignalUncaughtException: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:282)
09-12 12:32:33.417  6802 13210 E SignalUncaughtException: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
09-12 12:32:33.417  6802 13210 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
09-12 12:32:33.417  6802 13210 E SignalUncaughtException: 	... 4 more
```

**Comment by andreas-hartmann** [comment]
Same issue here for 5GB backup. Is there a workaround?

**Comment by andreas-hartmann** [comment]
Here's what I learned from debugging: If you enter an incorrect backup passphrase you may get a negative backup frame size which will result in NegativeArraySizeException: https://github.com/andreas-hartmann/Signal-Android/blob/0a6c3baf241a0b04bc7c871b951a8d63e250219a/app/src/main/java/org/thoughtcrime/securesms/backup/BackupRecordInputStream.java#L164
This isn't really a bug in itself but it causes the app to hard crash. Instead this should be caught more gracefully and sooner.
However, if you do enter the correct passphrase the app will still crash because it runs out of heap space if your backup is too large:
`09-13 16:16:54.423  8474  8648 E SignalUncaughtException: Caused by: java.lang.OutOfMemoryError: Failed to allocate a 2049405832 byte allocation with 35158560 free bytes and 500MB until OOM, target footprint 46878080, growth limit 536870912
09-13 16:16:54.423  8474  8648 E SignalUncaughtException:       at org.thoughtcrime.securesms.backup.BackupRecordInputStream.readFrame(BackupRecordInputStream.java:164)
09-13 16:16:54.423  8474  8648 E SignalUncaughtException:       at org.thoughtcrime.securesms.backup.BackupRecordInputStream.readFrame(BackupRecordInputStream.java:92)
09-13 16:16:54.423  8474  8648 E SignalUncaughtException:       at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:93)
09-13 16:16:54.423  8474  8648 E SignalUncaughtException:       at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:71)
09-13 16:16:54.423  8474  8648 E SignalUncaughtException:       at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:292)
09-13 16:16:54.423  8474  8648 E SignalUncaughtException:       at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:282)
09-13 16:16:54.423  8474  8648 E SignalUncaughtException:       at android.os.AsyncTask$3.call(AsyncTask.java:394)
09-13 16:16:54.423  8474  8648 E SignalUncaughtException:       at java.util.concurrent.FutureTask.run(FutureTask.java:264)
09-13 16:16:54.423  8474  8648 E SignalUncaughtException:       ... 4 more
`

LargeHeap is already enabled, so this needs to be rebuilt to stream the frame in smaller chunks, but IMO the deeper issue is that the frame is backed up with such big sizes in the first place. So changing that should resolve the underlying issue, but won't help those who are already affected (Which is basically any average Signal user, so this issue should get some priority imo)

**Comment by andreas-hartmann** [comment]
Ok I did some digging and debugging. If anyone is getting this error or a hard crash when restoring a backup regardless of size, you probably are entering the wrong passphrase. THIS IS NOT YOUR SIGNAL PIN, YOU HAVE TO ENTER YOUR BACKUP PASSPHRASE. It's 30-digit and formatted like: "11111 11111 11111 11111 11111 11111". If you enter an incorrect passphrase, Signal won't even know the size of the chunks of data in the backup and it will basically use an incorrectly decrypted chunk to determine the size of it. There's a 50% chance that number is negative, and another very high chance that it is way to large to fit into the limited heap size of the app. IDK what happens if by coincidence a reasonable chunk size is determined, but it certainly won't be able to decrypt your data correctly and will probably crash somewhere else. I propose the follwing:

1. The text should be adjusted to remind the user that the 30-digit backup passphrase is required. I forgot this, and many users will forget it, thus entering the Signal PIN or something else, causing confusion.
2. The error should be caught properly. If the chunk size is unreasonable, immediately display a message stating that the passphrase isn't correct, or just catch any exception with a reasonable message. This would be a quick fix to prevent crashes and confusion.
3. When activating backups the passphrase is shown. IIRC you just have to check a box that you wrote it down. I think it would be better to have the user write it back. Maybe using words would be more memorable, too. Given the number of people who are reporting here, a lot of users may have forgotten the passphrase, so UX improvements may be necessary.
4. Review if it makes sense or is necessary to even encrypt the chunk size. Can it not be in plain in the file header or be a fixed value?
5. It should be more clear how to change the passphrase. When I switch my phone I may remember to check if I have a recent backup and look at the Chat Backup menu. If I then realize I don't have the passphrase anymore, it's not immediately clear how to proceed.

**Comment by muteNut** [comment]
Thanks for your effort Andreas, seems like I might have saved the old passphrase instead of the new one :-(
signalbackup-tools outputs

```
Reading backup file...
FRAME 0 (000.0%)... Failed to read next frame (2714053385 bytes at filepos 60)
 *** NOTE : IT IS LIKELY AN INCORRECT PASSPHRASE WAS PROVIDED ***

done!
WARNING EndFrame was not read: backup is probably incomplete
Database version: 4294967295
```

**Comment by janvlug** [comment]
>     3. When activating backups the passphrase is shown. IIRC you just have to check a box that you wrote it down. I think it would be better to have the user write it back. Maybe using words would be more memorable, too. Given the number of people who are reporting here, a lot of users may have forgotten the passphrase, so UX improvements may be necessary.

An (optional) reminder to test to check 30-digit backup passphrase like checking the Signal PIN might be useful too.

>     5. It should be more clear how to change the passphrase. When I switch my phone I may remember to check if I have a recent backup and look at the Chat Backup menu. If I then realize I don't have the passphrase anymore, it's not immediately clear how to proceed.

:+1: Is it even possible to change the 30-digit backup passphrase? I could not find where to do that.

**Comment by f0k** [comment]
> Is it even possible to change the 30-digit backup passphrase? I could not find where to do that.

You need to deactivate the backup and then activate it again. This will give you a *new* random passphrase. (Also not always obvious: I've once changed the backup location and was not aware this results in a changed passphrase that needs to be noted down.)

**Comment by cody-signal** [comment]
A change to backups broke the passphrase validation, and we fixed it back in October. Should now be alerted instead of crashes if passphrase is incorrect.
