### ISSUE TITLE
Transfer between old and new device fails 

### ISSUE THREAD

**Issue by jnns** [signalapp/Signal-Android#12048]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I'm trying to transfer my data / account from an old to a new device. Device pairing seems to work fine. The pairing code is identical and the transfer could start. But as soon as a progress indicator should appear, the transfer fails. I'm even seeing "0.1%" for split second.

### Steps to reproduce
- follow instructions on how to transfer data in Signals knowledge base

- I enabled wifi, Bluetooth, location. 
- both devices have been restarted
- both devices received new wifi direct identifiers.

### Screenshots

![Screenshot_20220309-183352](https://user-images.githubusercontent.com/206281/157498295-5582086d-207f-454f-b612-1f66fdb5602e.png)

### Device info

**Device:** Google Pixel 1 and Google Pixel 4a
**Android version:** 10 and 12
**Signal version:** 5.33.1 and 5.33.1

### Link to debug log
https://debuglogs.org/android/5.33.1/e43db0f05582bb1608393adb11a482e173e3e20d2c7bfa54d2faf5923885f3df

**Comment by jnns** [comment]
Interestingly I cannot restore from a file backup either. I copied the data over to the new phone and while checking the file Signal crashes completely. I don't know how to get hold of the debug log on the crashing Signal because I can only access the welcome screen.

**Comment by jnns** [comment]
After opting out of the beta test and downgrading the target device to current stable, the passphrase check is performed correctly. On 5.33.1 the restore failed no matter if the phrase was correct or not. 

Sadly, the backup can still not be restored because the file was created from a newer version.

**Comment by elitistphoenix** [comment]
I have the same issue. Both on the transfer and restore. Using 5.33.1 too.

**Comment by ubergeek77** [comment]
Yeah I'm seeing this issue too. Seems to be widespread. Same Signal version.

Does anyone know a safe way of downgrading Signal without losing messages? I absolutely cannot afford to lose these messages.

I suppose I could wait, too, but I would like to get this new phone set up as soon as I can.

**Comment by jnns** [comment]
When I retried to restore yet another fresh backup with `adb logcat` running on the target device, I saw that this is in deed the `SQLiteConstraintException` that @elitistphoenix mentioned:

```
03-10 08:08:35.455  3811  3811 I GoogleInputMethodService: GoogleInputMethodService.updateDeviceLockedStatus():2099 checkRepeatedly = true, unlocked = true
03-10 08:08:35.464  4017  4032 I MediaProvider: Open with lower FS for /storage/emulated/0/Signal/Backups/signal-2022-03-10-06-55-04.backup. Uid: 10058
03-10 08:08:36.035 18190 18259 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #2                 
03-10 08:08:36.035 18190 18259 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 18190                                                                                              
03-10 08:08:36.035 18190 18259 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
03-10 08:08:36.035 18190 18259 E AndroidRuntime:        at android.os.AsyncTask$4.done(AsyncTask.java:415)                                                                                    
03-10 08:08:36.035 18190 18259 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
03-10 08:08:36.035 18190 18259 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
03-10 08:08:36.035 18190 18259 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:271)                                                                           
03-10 08:08:36.035 18190 18259 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)                                                                      
03-10 08:08:36.035 18190 18259 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-10 08:08:36.035 18190 18259 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-10 08:08:36.035 18190 18259 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:920)                                                                                              
03-10 08:08:36.035 18190 18259 E AndroidRuntime: Caused by: net.zetetic.database.sqlcipher.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
03-10 08:08:36.035 18190 18259 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
03-10 08:08:36.035 18190 18259 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:767)
03-10 08:08:36.035 18190 18259 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:758)
03-10 08:08:36.035 18190 18259 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:70)
03-10 08:08:36.035 18190 18259 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteDatabase.executeSql(SQLiteDatabase.java:1994)
03-10 08:08:36.035 18190 18259 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteDatabase.execSQL(SQLiteDatabase.java:1901)
03-10 08:08:36.035 18190 18259 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter.dropAllTables(FullBackupImporter.java:281)
03-10 08:08:36.035 18190 18259 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:94)
03-10 08:08:36.035 18190 18259 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:77)
03-10 08:08:36.035 18190 18259 E AndroidRuntime:        at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:291)
03-10 08:08:36.035 18190 18259 E AndroidRuntime:        at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:282)
03-10 08:08:36.035 18190 18259 E AndroidRuntime:        at android.os.AsyncTask$3.call(AsyncTask.java:394)                                                                                    
03-10 08:08:36.035 18190 18259 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                           
03-10 08:08:36.035 18190 18259 E AndroidRuntime:        ... 4 more                             
03-10 08:08:36.035 18190 18259 E SignalUncaughtException: java.lang.RuntimeException: An error occurred while executing doInBackground()
03-10 08:08:36.035 18190 18259 E SignalUncaughtException:       at android.os.AsyncTask$4.done(AsyncTask.java:415)                                                                            
03-10 08:08:36.035 18190 18259 E SignalUncaughtException:       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)

```

**Comment by cody-signal** [comment]
Thanks, looking into this now, hope to have a fix our shortly.

**Comment by elitistphoenix** [comment]
Fixed in 5.33.2. Only was able to test transfer between two devices though and not restore of backup. Thank you!!

**Comment by jnns** [comment]
Thank you @cody-signal. The backup file was successfully restored.

**Comment by TheLastGimbus** [comment]
It still crashes for my backup ;_;

Tho it crashes for my big-ass 1.7gb one. When i try with new fresh one, works fine...

Another FOREIGN KEY constraint failed, this time at: https://github.com/signalapp/Signal-Android/blob/fa384e93dcd4f09e9b44ba73309d6d4b7838d22f/app/src/main/java/org/thoughtcrime/securesms/backup/FullBackupImporter.java#L170

**Comment by ubergeek77** [comment]
@TheLastGimbus The fix applied in 5.33.2 worked fine for me, and my backup was approaching 5GB, much larger.

Though I did have my old phone, so I ended up doing the WiFi transfer method instead of importing a backup file. I can't say for sure if the latter is fixed since I didn't use it.

**Comment by TheLastGimbus** [comment]
After messing it for another HOURS, here is what I did:

1. I downaloded and **complied Signal myself**
2. I added this line before line 170: 
    ```java
    Log.d(TAG, statement.getStatement() + " : " + parameters.toString());`
    ```
    It logs ALL sql commands and their args
3. I imported backup *on my debug version* and checed what statement was logged *before* crash - here it is: `D/FullBackupImporter: INSERT INTO msl_message VALUES (?,?,?,?) : [39655, 34916, 42278, 0]`
4. I expored the backup with https://github.com/bepaald/signalbackup-tools/ (thank you very much @bepaald for creating this :pray:):
    ```bash
    signalbackup-tools signal-2022-03-09-21-47-45.backup "12345 44855 83659 83350 25054 47936" --output dir1/
    ```
5. I manually examined this one fellow msl_message row with `sqlite3`:
    ```sql
    SELECT * FROM msl_message WHERE _id = 39655;
    ```
    I found that this table has a forgein key with `msl_payload`, and this particular one didn't match.
    Double checked it:
    ```sql
    SELECT *
    FROM msl_message
             LEFT JOIN msl_payload ON msl_payload._id = msl_message.payload_id
    WHERE msl_payload._id IS NULL;
    -- Yep, there was *only one* such
    ```
    and just deleted this damn message:
    ```sql
    DELETE FROM msl_message WHERE _id = 39655;
    -- this could probably be fit into nicer statement without _id hard-coded, but i don't care now
    ```
6. Put db back to `.backup`:
    ```bash
    signalbackup-tools dir1/ --output probably-fixed.backup --opassword "12345 44855 83659 83350 25054 47936"
    ```

AND NOW IT WORKED

This wasted me ~2 days of my life

It would be very nice if it didn't 

Hope this guide helps someone :pray: 


Ps. My detailed crash:
```java
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: org.thoughtcrime.securesms, PID: 14566
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:415)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: net.zetetic.database.sqlcipher.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
        at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
        at net.zetetic.database.sqlcipher.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:767)
        at net.zetetic.database.sqlcipher.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:758)
        at net.zetetic.database.sqlcipher.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:70)
        at net.zetetic.database.sqlcipher.SQLiteDatabase.executeSql(SQLiteDatabase.java:1994)
        at net.zetetic.database.sqlcipher.SQLiteDatabase.execSQL(SQLiteDatabase.java:1951)
        at org.thoughtcrime.securesms.backup.FullBackupImporter.processStatement(FullBackupImporter.java:171)
        at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:114)
        at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:88)
        at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:291)
        at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:282)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
E/SignalUncaughtException: java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:415)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: net.zetetic.database.sqlcipher.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
        at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
        at net.zetetic.database.sqlcipher.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:767)
        at net.zetetic.database.sqlcipher.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:758)
        at net.zetetic.database.sqlcipher.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:70)
        at net.zetetic.database.sqlcipher.SQLiteDatabase.executeSql(SQLiteDatabase.java:1994)
        at net.zetetic.database.sqlcipher.SQLiteDatabase.execSQL(SQLiteDatabase.java:1951)
        at org.thoughtcrime.securesms.backup.FullBackupImporter.processStatement(FullBackupImporter.java:171)
        at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:114)
        at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:88)
        at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:291)
        at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:282)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
```

**Comment by bepaald** [comment]
@TheLastGimbus Glad my tool was of assistance. You used it very cleverly. I just wanted to add that what you experienced in 5.33.2 is a different (though somewhat related) problem, that would probably warrant opening a new issue.

**Comment by cody-signal** [comment]
@TheLastGimbus Sorry you had this issue. If you're on the beta, I highly recommend checking the beta threads associated with the release. We are more active there and there are posts about when things get fixed. Clever use of @bepaald 's tool.
