### ISSUE TITLE
in-app camera - photo does not match preview and is blurry

### ISSUE THREAD

**Issue by corobin** [signalapp/Signal-Android#12431]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
there are two observations which appears to be related to one root cause, however if i am wrong about that then this should probably be two issue reports

1. The photo that is taken has a much wider field of view than the preview image. this affects both the front facing and main camera

2. The photo is much blurrier and obviously smoothed out compared to the preview image. this appears to only affect the front facing camera. it also appears to be most obvious with a selfie of the face in low light

### Steps to reproduce
- open signal app
- press the camera button on the bottom right corner of the contract list. alternatively: open a chat and press the camera button in the text field
- switch to the main camera 
- observe the preview
- take a photo
- observe the photo taken
- switch to the front facing camera
- observe the preview
- take a photo
- observe the photo taken

**Actual result:** 

1. The photo field of view is much wider than the preview

2. The photo is much blurrier / smoothed compared to the preview - *appears* to only apply to front facing camera especially when taking photo of face

**Expected result:** 

the photo taken should match what is seen in the preview 

### Screenshots
since it is most obvious with a selfie i am sorry i will not upload a screenshot

### Device info

**Device:** pixel 4
**Android version:** Android 13 August patch
**Signal version:** 5.48.3 - the immediately previous version did not have these problems

### other

i found issue #12030 about blurriness, however the sample images there are not even close to as blurry or noticeable as i am seeing now. i do not suspect that issue to be the same cause. The photos I'm seeing now look like they've been put through a really bad smoothing filter.

**Comment by alex-signal** [comment]
Hello, this should be fixed in 8bd89d1e6 which is included in the 5.49 beta cycle.

**Comment by corobin** [comment]
hi there, i just got the 5.49.4 update.

The viewport/photo size issue has been resolved.

unfortunately, the blurry/smoothed out photo issue still remains.

it appears to still be most evident on the selfie camera in somewhat low light. it _looks like_ undesired post processing.

for comparison, iirc the release version just before 5.48 had no issues.

thanks!

**Comment by alex-signal** [comment]
I just started dailying a Pixel 4 yesterday, and can definitely repro this. I'll take a look today, because yeah, that's unuseable.

**Comment by corobin** [comment]
thanks for identifying the issue so quickly!

**Comment by corobin** [comment]
The update 5.25.5 looks to have fixed it. thanks!

**Comment by break6700** [comment]
I am having this same issue on the Pixel 4 XL. If this is as simple a fix of adding a device to list, please add this one.

I am running Signal 6.1.4

**Comment by alex-signal** [comment]
> I am having this same issue on the Pixel 4 XL. If this is as simple a fix of adding a device to list, please add this one.

Hi! Can do. Do you mind posting a debug log so I can ensure I add the correct model number?

**Comment by break6700** [comment]
As requested: [signal-log-1668723852876.zip](https://github.com/signalapp/Signal-Android/files/10036209/signal-log-1668723852876.zip)

**Comment by D3llon** [comment]
Hello, I was having this same issue (blurry front-facing pictures taken with the in-app camera) on my old Samsung Galaxy S21 and it persists on my recently bought Galaxy S23. I am also attaching debug log if requried: 
[signal-log-1684537058114.zip](https://github.com/signalapp/Signal-Android/files/11521021/signal-log-1684537058114.zip)

**Comment by dirtdiver99** [comment]
I'm also having the same issue on a Samsung Galaxy Z Fold 4. Interestingly, the outside screen selfie camera doesn't produce a smoothed / blurry result but if I open the phone the selfie camera does produce a blurry / smoothed result.  I am able to reproduce it repeatedly. I did test with the phone's camera app and the results using the inside selfie camera are night and day between the camera app and the camera within Signal.

**Comment by ImJustToNy** [comment]
Hi, also having issue on my S23, debuglog here: https://debuglogs.org/android/6.40.4/9c9a6fb3c467a4eff8758ac91c5aaa7ea903bca1fa40fb40073276591d9fcb66

**Comment by DidierLoiseau** [comment]
I am also noticing the same issue with the field of view on the Pixel 8. @alex-signal, should I report it as a new bug? (not sure whether the last 3 comments were taken into account or not)

[Here is my debug log](https://debuglogs.org/android/7.6.2/43badd2dabdd2c349508764a68ebbcf5d9bbb33cc8003c57e1e3cb4722e6c907)

**Comment by mmueller-kaffeeschluerfercom** [comment]
I have v 7.32.3 running on Pixel 5a. The preview field of view does still not match the photo taken. After every photo I take, I have to manually crop it because the photo is much larger than the preview.
