### ISSUE TITLE
SMS export fails for disk space and recipient list

### ISSUE THREAD

**Issue by noobish** [signalapp/Signal-Android#12778]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On 6.10.8 I am experiencing the following problems with export:

- initial export stops at 614 messages remaining out of 35 thousand and complains that I need about 34 more MB free on the device. Google's storage settings page shows 444 GB free. Is the export file limited to an arbitrary file size limit?
- Retrying results in an attempt to re-export the remaining 614 messages, but that fails with a general error message. See screenshot. From the log, it seems like every message failed with:
> Failed to get thread id for export
> Java.lang.IllegalStateException: expected non-empty recipient list
- After incoming SMS messages come in to the phone and an export is re-attempted, it successfully exports the new message, and fails on the remaining 614. So perhaps there is something else wrong with the messages itself rather than disk space. Is there a way for me to inspect the remaining messages on disk?

### Steps to reproduce
- Have 35 thousand SMS messages in your app (because you've used signal for everything since day one and "soon" won't be able to)
- Set signal up as default SMS messaging app
- Start export of SMS messages

**Actual result:** Export fails and will not progress further than the remaining 614 messages.

**Expected result:** Export to complete all SMS exports.

### Screenshots
![Screenshot_20230208-134908](https://user-images.githubusercontent.com/637552/217638129-7c0838cd-65df-44d3-9764-1a63938792aa.png)

I have only twice seen the original error message that tells me I need more space freed. I will keep trying to get it again to capture a screenshot and debug log. The attached debug log is after the generic failure message in the above screenshot.

### Device info
**Device:** Pixel 6 Pro
**Android version:** 13
**kernel version:** 5.10.107
**Signal version:** 6.10.8

### Link to debug log
https://debuglogs.org/android/6.10.8/29b5fcfc5e7b2bf12ab326707a5332e49d2e779c2e3f998f4a3e5bb9d5871436

Also, please please please do not remove the SMS messaging support until all of these export bugs are fixed.

**Comment by noobish** [comment]
For added fun I suspect that the export attempt has somehow merged incoming MMS group texts with very old groups (where none of the recipients are the same except for me). If I can figure out the behavior I will post a separate issue for this.

**Comment by alex-signal** [comment]
Hi! I believe there was a bug in how we got MMS groups that was resolved today in a hotfix. That might not fix this issue, but I'd ask that you retry after installing the hotfix.

**Comment by noobish** [comment]
The issue remains on 6.10.9. I captured a log after the free space error:
https://debuglogs.org/android/6.10.9/a084592d5ca5a656a45ddabbd615499038b6659254a3152d6ad0edfd384ee860

It also includes another export attempt afterwards which should match the original log. It also has a bunch of connection errors due to poor cellular reception.

![Screenshot_20230214-120335](https://user-images.githubusercontent.com/637552/218871191-43745f65-0868-4046-a6d7-21e7782b2bd2.png)

**Comment by cody-signal** [comment]
Are you still encountering this issue on 6.11.x or 6.12.x.? It's not space related, as the trouble shoot screen is just generic steps that could help.

**Comment by noobish** [comment]
Yes, the issue is still present on 6.11.7 (I'm installing through google). Debug log from 6.11.7:

https://debuglogs.org/android/6.11.7/1d45692098a1bcc97160bcb044a8574c8ccbc874d9f1a6f3e8b9f32bdea5b80f

What was curious to me was the specific amount of space it was saying it needed. It made.me think it was working within a fixed container.

**Comment by cody-signal** [comment]
The export seems be barfing on trying to create the thread ids for the remaining messages. I'll look into it.

Regarding the space, the value is a guestimate we make based on the remaining messages that need to be exported and any media that remains to be exported.

**Comment by noobish** [comment]
That makes sense. Thank you.

**Comment by noobish** [comment]
If the recipient list cannot be reconstructed, I can't really make a smart decision on how to export meaningful information. Messages just wouldn't be that meaningful without the user context. And I imagine you don't desire to create an unknown recipient.

I suppose these messages should just die a blackhole death.

**Comment by noobish** [comment]
Well I didn't mean to close the issue, but I'm ok if it remains closed.
