### ISSUE TITLE
Wrong from/to displayed in group texts

### ISSUE THREAD

**Issue by asdf23** [signalapp/Signal-Android#12785]
I am seeing the wrong contacts displayed in group texts. This should never happen. Sending a message to the group sends it to the original participants when the group was created. Messages received come from the original participants, but the members displayed are not in the group.
Anyway I understand that your removing SMS entirely, I along with the other 99% of your users, in a short-sighted business move. So we probably won't see this get fixed. Too bad. Signal was a nice platform while it lasted.

**Comment by cody-signal** [comment]
This should be fixed in the latest app version. Which version are you using?

**Comment by asdf23** [comment]
I'm using 6.10.8. I thought I was on latest. I take it I could update with losing the ability to use sms...?

**Comment by asdf23** [comment]
Also seeing this problem in 6.10.9 (or it didn't resolve past incorrect texts)

**Comment by cody-signal** [comment]
It won't resolve past texts, but should address future ones.

**Comment by asdf23** [comment]
Is this code going to be picked up by someone else? Does signal intend to exist in the future? If signal corp discovers that they lost 99% of users .. Is there a fallback plan?
If I were you I'd have an apology email/html written up. Then start a plan to focus on sms and finding a way to embrace iphone users somehow.
