### ISSUE TITLE
Robotic Voice in Voice-Message Xiaomi

### ISSUE THREAD

**Issue by MichaelFranziskus** [signalapp/Signal-Android#12847]
### Bug description
When I send a voice message the message sounds like a robotic voice. 
At other apps it is normal. Calls also

Xiaomi Mi 9T 
miui 12.0.5

Also mentioned here: https://www.reddit.com/r/signal/comments/kupbtx/robotic_voice_message/

### Steps to reproduce
Send a voice message and liste it on you or the other phone

**Comment by cody-signal** [comment]
This seems to be device specific, hoping to look into it once the 9T gets delivered.

**Comment by nicholas-signal** [comment]
For posterity: this was addressed in 2256c8591a98d4f55ef1ac97d40fb890ed7832c8

**Comment by rchaucha** [comment]
I still have this exact problem on my Mi 9T Pro (MIUI 12.5.1) as of today.
I just realized it now since nobody ever told me but I listened to old voice message which also had the problem so this is not new.
As stated in the original post, only voice messages are affected, video audio is fine.

I see that the commit supposed to solve the problem checks for 9T only:
`if ("Xiaomi".equals(Build.MANUFACTURER) && "Mi 9T".equals(Build.MODEL))`
I guess 9T Pro should also be added?

**Comment by MichaelFranziskus** [comment]
Hi, I'm not sure, I think I have had a Mi 9T and not the pro version. Maybe this is the difference.

With fixing this Issue for me it was directly fine.
Maybe the fix does not actually include the Mi 9T Pro.

Unfortunately I can not check if it still works for me.
