### ISSUE TITLE
Signal crashes with log error "No UUID or phone number"

### ISSUE THREAD

**Issue by AriESQ** [signalapp/Signal-Android#12918]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When opening the app, I can see the screen for a moment and then the app closes. I will still get incoming notifications. If I turn on airplane mode I can access the app. If I compose a message while in airplane mode, the message will be sent when I turn off airplane mode. I believe the background sync process is running, but the Android user app is crashing.

On signal desktop I have persistently had 5 unread notifications in the task bar. Recently I went into the "filtered by unread" screen on Android, accessed by swiping down on the main screen / conversation view. And I used the three dot menu to "mark all as read", because there were many random unreads, such as for SMS 2FA codes. I'm not sure if this is related. Now signal desktop has 99+ unread notificaitons :/

This appears related: https://github.com/signalapp/Signal-Android/issues/11228

I believe the error that is killing my app is  
`AndroidRuntime: java.lang.AssertionError: RecipientId::1032 - No UUID or phone number!`

I have browsed through my contacts (while in airplane mode) and I don't see contacts that are obviously incorrect. To access contacts I go to "compose" by pressing the pen icon, and I can scroll through contacts to add to a message. I don't see an obvious way to delete a contact.

### Steps to reproduce
Open the app, immediate crash.

### Device info

**Device:** Pixel 5a
**Android version:** Android 13 w/ April 2023 security patch
**Signal version:** Google Play: 6.18.4
### Link to debug log
```
The relevant portion of the debug log, pulled from ADB.

--------- beginning of crash
AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-1
AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 4334
AndroidRuntime: java.lang.AssertionError: RecipientId::1032 - No UUID or phone number!
AndroidRuntime:  at org.thoughtcrime.securesms.recipients.RecipientUtil.toSignalServiceAddress(Recipient
AndroidRuntime:  at org.thoughtcrime.securesms.jobs.SendReadReceiptJob.onRun(SendReadReceiptJob.java:182
AndroidRuntime:  at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
AndroidRuntime:  at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
AndroidRuntime:  at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-2
AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 4334
AndroidRuntime: java.lang.AssertionError: RecipientId::1032 - No UUID or phone number!
AndroidRuntime:  at org.thoughtcrime.securesms.recipients.RecipientUtil.toSignalServiceAddress(Recipient
AndroidRuntime:  at org.thoughtcrime.securesms.recipients.RecipientUtil.getOrFetchServiceId(RecipientUti
AndroidRuntime:  at org.thoughtcrime.securesms.jobs.MultiDeviceReadUpdateJob.onRun(MultiDeviceReadUpdate
AndroidRuntime:  at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
AndroidRuntime:  at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
AndroidRuntime:  at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
```

**Comment by AriESQ** [comment]
Error references this code, I believe:
https://github.com/signalapp/Signal-Android/blob/main/app/src/main/java/org/thoughtcrime/securesms/recipients/RecipientUtil.java#L66

**Comment by AriESQ** [comment]
Fixed itself after 1 day, I have no idea :shrug:

**Comment by TylerRick** [comment]
I ran into the same problem today.

Could you please reopen this, @AriESQ? This is a serious bug, and it still exists in the latest Signal version 6.19.8!!

> When opening the app, I can see the screen for a moment and then the app closes. I will still get incoming notifications.

Same for me, although I only see my list of contacts about 10% of the time. Most of the time it crashes too quickly without even getting to that screen.

> If I turn on airplane mode I can access the app.

Thanks for that workaround! At least this lets me search and view my old chats (and create a current backup, which gives me a little peace of mind)...

> If I compose a message while in airplane mode, the message will be sent when I turn off airplane mode.

This did not work for me. When I turned Internet back on, the message did not get sent and did not appear in my Signal Desktop client. And when I turned Internet off again so that I could view the status of the message, it still shows the spinner, indicating that it is still unsent.

> On signal desktop I have persistently had 5 unread notifications in the task bar. Recently I went into the "filtered by unread" screen on Android, accessed by swiping down on the main screen / conversation view. And I used the three dot menu to "mark all as read", because there were many random unreads, such as for SMS 2FA codes. I'm not sure if this is related. Now signal desktop has 99+ unread notifications :/

I ended up in this broken state in a similar manner (though nothing related to Signal Desktop for me): I accidentally found myself on the "filtered by unread" screen on Android and was manually clicking on each one to mark it as read (hadn't found the "mark all as read" menu item yet!). It was while doing this that the app crashed and I haven't been able to get back in.

I did have one related issue with Signal Desktop, however: Since Signal Android is currently not usable for me, I started using Signal Desktop to send messages. This worked perfectly... However, now, more than an hour later, all those messages that I sent on Signal Desktop have vanished!! Why this happen?? Where did those messages go?? Now I'm nervous to even keep using the desktop Signal!

It's almost like it received a status update from the Android background app, which apparently _doesn't_ have a copy of those messages composed on Desktop, and it replaced its message list with the list from Andrdoid (??). (I don't actually know how the syncing works. Just surmising...)

> I believe the error that is killing my app is `AndroidRuntime: java.lang.AssertionError: RecipientId::1032 - No UUID or phone number!`

Yes, that's the same error that I found using `adb logcat --buffer=crash`:
```
RecipientId::159 - No UUID or phone number!
```

> I have browsed through my contacts (while in airplane mode) and I don't see contacts that are obviously incorrect. To access contacts I go to "compose" by pressing the pen icon, and I can scroll through contacts to add to a message. I don't see an obvious way to delete a contact.

Indeed. Is there a (easy) way we can query the local Signal database, find whatever recipient record is missing these properties, and add the missing properties to it? Just as a workaround to fix this error for now...

But in any case, it seems like the app should be fixed so that it won't crash _even if_ some recipient ends up with no UUID or phone number for no apparent. Would this be possible, please?

> Fixed itself after 1 day, I have no idea shrug

Hopefully it will do the same for me!! (Though I have no reason yet to believe that it will...) Will let you know after 24 hours...

**Comment by cody-signal** [comment]
@TylerRick it seems like you can access the app in airplane mode, could you go to the submit debuglog screen but use the 3-dot menu to download the log instead of submitting it. You can then send me the zip directly via email/sharing service. You can reach me at cody dot signal dot org

**Comment by TylerRick** [comment]
Hi @cody-signal, I just sent you the logs. Hopefully something helpful is (still) contained therein. But...

To my surprise (just like @AriESQ predicted—sorry to be a skeptic), the crashing problem has gone away when I tried it again this morning. I guess I didn't even have to wait 24 hours, just until the next calendar day! (But why/how??)

I am not able to reproduce it now, fortunately/unfortunately...

**Comment by neuter4106-star** [comment]
This is still an issue in version 7.68.5 after blocking a phone contact. The issue didn't show up immediately when blocking, but rather overnight after doing so. Aside from using airplane mode, there is nothing else I can do to get the app to open, including a full uninstall. It occurs due to line 188 of the localToRemoteContact function in StorageSyncModels.kt. 

Anything that can be done to resolve this is greatly appreciated, even if it's just a temporary workaround provided, as this is a near complete outage for me.

**Comment by neuter4106-star** [comment]
Hi, is there any update on this one, at least for a workaround I can try? I hate to be a bother but this is much more than a minor inconvenience, as I can hardly use the app at all in this state. I've reached out on here and via a ticket through the website and haven't received any response back. Any help would greatly appreciated! 

Thanks.

**Comment by neuter4106-star** [comment]
For anyone else this may be affecting, reboots somehow seem to be helping today where they weren't before. The problem has still come back at least once but it at least gives me some usable time with the app until I have to reboot again.

**Comment by mtang-signal** [comment]
Hi, do you think you'll be able to also grab a [debug log](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug) (while on airplane mode or while Signal is still usable)? Thanks for specifying what you did because I don't think we were ever able to reproduce this. A bit vague but is the phone number of the blocked contact anything particularly special?

**Comment by encrypt344** [comment]
@mtang-signal this is neuter4106-star. I had to recreate my Github account. I did already submit a debug log via the website many days ago and have never heard back. Also, the contact I blocked on my phone and in Signal has a standard phone number. Nothing special that I can note. 

Please be aware that the reboot temp workaround I posted about earlier today is no longer working. It may have been a quirk of the WiFi at the particular hotel I was staying at. I'm back to this being a near complete outage for me. Happy to help however I can to resolve this, as I could really use a fix having gone more than a week with this issue now.

**Comment by mtang-signal** [comment]
@encrypt344 Thanks for the log. I'll try and put a potential fix into 7.70 which will hit beta this week. Although I am still confused as to how your database ended up as such - before you blocked the contact, had you ever exchanged messages? And then how exactly did you block them (I assume the New message > Long press on contact > Block)?

**Comment by encrypt344** [comment]
Thanks @mtang-signal. Is there a way I can force install this beta when it's released? 

Yes, we had exchanged many messages. I don't remember exactly how I blocked them within Signal, but I did block them as a contact on my phone first. Not sure if that contributed to the bug.

**Comment by mtang-signal** [comment]
If you are using Google Play Store, you'd have to sign up for our beta program to get 7.70 earlier. Takes about 24 hours for it to be uploaded. Note that if you do that, and then go back to the production version, you will likely lose your data so please make sure to create a backup. Alternatively, if you use other means (eg Github), it'll be ready on the same day it's released.
