### ISSUE TITLE
Unable to send a contact via Signal

### ISSUE THREAD

**Issue by kangaroo72** [signalapp/Signal-Android#13090]
- [x] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
While sending a contact from my addressbook, there's now arrow, that it's been sent. It's not going out.

### Steps to reproduce
try to send a contact
it will not be delivered

**Actual result:** Contact will not be sent
**Expected result:** Contact should be sent

### Device info
<img width="289" alt="SCR-20230805-bgtm" src="https://github.com/signalapp/Signal-Android/assets/6906390/5f9594b9-300e-4794-9b51-4c6317c1287f">

**Device:** Samsung Galaxy S23 Ultra
**Android version:** 13
**Signal version:** 6.27.10

### Link to debug log
https://debuglogs.org/android/6.26.5/0a2f1daa872855bf01f87b352403020e304696eb7f5c477bfaca00b2d99f58f3

**Comment by gkarthikreddi** [comment]
It's only happening on android devices. On IOS it seems to be working fine.

**Comment by kangaroo72** [comment]
I have various Android-Devices and can check another one... but I also think, it's an android issue....

**Comment by alex-signal** [comment]
Hi! Turns out there was a bug in some new code we introduced a few releases ago. This is fixed in 6.28.2 which is rolling out to production over the next few days.

**Comment by major-mayer** [comment]
I am on 6.31.2 and sending contacts still doesn't work for me.
The loading spinner just stays there forever.

**Comment by kangaroo72** [comment]
I'm also on 6.31.2 and for me it works right now.
@major-mayer  which Android-Version are you using?

**Comment by major-mayer** [comment]
I can confirm that it works for me as well again
