### ISSUE TITLE
Sticker pack does not work in Signal for Android but works in Signal for Desktop

### ISSUE THREAD

**Issue by HyperCriSiS** [signalapp/Signal-Android#13244]
Hi,

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- Install Sticker pack
https://signal.art/addstickers/#pack_id=884c5bc8e034763638038719004b53b6&pack_key=c33df578c4b68331cdefce3cef0b4ad3641ba91cbb9b45816ca82fd38097d20a

- Send a sticker

**Actual result:** The sticker is not visible. It is also not visible in the sticker picker.
**Expected result:** The sticker should be visible in the sticker picker and when its sent

### Screenshots
![Screenshot_20231106-153655_Signal](https://github.com/signalapp/Signal-Android/assets/11708192/a80f34e2-cbba-4ee5-90ef-c8a519fe9843)
![Screenshot_20231106-153719_Signal](https://github.com/signalapp/Signal-Android/assets/11708192/4bd4600e-7849-41a8-a264-8925f7790db9)
![Screenshot_20231106-153719_Signal_1](https://github.com/signalapp/Signal-Android/assets/11708192/f29c0e73-0a8f-4667-9696-64ca068cff98)

### Device info

**Device:** Asus Zenfone 8
**Android version:** 11
**Signal version:** 6.38.2

### Link to debug log
https://debuglogs.org/android/6.38.2/5be17188c748a9a5faf7c710c29cd5b567c6d3f1c2ccfeacb28501ce6faa5343

Thanks
Hyper

**Comment by Perfectio07** [comment]
I would like to add in, this happens to me as well but with animated stickers. Even more specifically, stickers created from an Iphone.

Iphone users can see the sticker fine, but me (Asus Zenfone 9) and my friend (Samsung A54) see the sticker like the pictures above.

![Screenshot_20231202-214820_Signal_1](https://github.com/signalapp/Signal-Android/assets/68266493/780c78b6-54f6-4fb2-be07-b511f3e4e12a)

**Comment by clark-signal** [comment]
Thanks for the report! Do you know if this is recent?

**Comment by HyperCriSiS** [comment]
> Thanks for the report! Do you know if this is recent?

My reported sticker pack still does not work on latest beta (6.41.2)

**Comment by Perfectio07** [comment]
Unfortunately it is not recent. I have had this issue for quite a while (about a year or so) just never got around to reporting it.

**Comment by laggykiller** [comment]
Because the sticker pack contains animated stickers in webp format. Animated stickers must be in apng format to playback on mobile devices. See https://support.signal.org/hc/en-us/articles/360031836512-Stickers

Shameless self-advertisement: You may use sticker-convert (https://github.com/laggykiller/sticker-convert) to convert the stickers to apng and reupload.

**Comment by Perfectio07** [comment]
So per the article, it must be apng, but animated webp works for Iphones and fails on Android? How weird. I would hope that if it works on one it works on the other.

Ill give the converter tool a try

**Comment by Perfectio07** [comment]
This issue still remains. Im not sure if its the format or not, but it fails on Androids and is fine on Iphones.

**Comment by laggykiller** [comment]
@Perfectio07 This problem is addressed here: https://github.com/signalapp/Signal-Android/issues/13067#issuecomment-1961579210

**Comment by Perfectio07** [comment]
It still doesn't explain why webp renders fine on Iphones and not on Android. I could be wrong, but I am sure that Androids should be capable of rendering webp. If not, then I guess it is what it is.

**Comment by HyperCriSiS** [comment]
Stickers showing properly now. Issue solved, thank you 🙂
