### ISSUE TITLE
App always crashes after opening

### ISSUE THREAD

**Issue by chromosapiens** [signalapp/Signal-Android#13255]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
App crashes within seconds after opening.

I described the problem in another issue (https://github.com/signalapp/Signal-Android/issues/13183#issuecomment-1734458664). Since it is unrelated I opened a separate issue.

I attached more complete adb logs below.

### Steps to reproduce
- Open App

**Actual result:** The App opens and I can use the app for 1 to 3 seconds (even new messages loading) then the crash occurs
**Expected result:** No crashing

### Device info

**Device:** Oneplus 8 Pro
**Android version:** Oxygen 13.1 (Android 13)
**Signal version:** 6.40.4 beta (originally occurred on 6.33.3 stable)

### Link to debug log
[adb.log](https://github.com/signalapp/Signal-Android/files/13342817/adb.log)

Most relevant lines probably:

- `Message: SQL logic error`
- `Message: cannot commit - no transaction is active`

I also wanted to ask if there is any chance that this gets fixed by an update or if my database is irreversibly corrupted.
I'd really like not to lose all my data. I used Signal really since forever. Is there anything I can do?
Thanks your work is really appreciated.

**Comment by greyson-signal** [comment]
I don't know if it helps, but the error in  your log is not a corruption issue. At the same time, I have tried recreating the same code path but cannot reproduce it, so it's unclear what's going on her.

You can get a more detailed log by going into airplane mode, go to Settings > Help > Debug log, then press the 3-dot menu to get an option to save the file to disk.

**Comment by chromosapiens** [comment]
Thanks for your insights. Unfortunately I can't get to the debug log menu entry in time before the app crashes.

**Comment by greyson-signal** [comment]
Oh really, even in airplane mode? The thing that crashes shouldn't run if you don't have network. Maybe the crash happens somewhere else in that case?

**Comment by chromosapiens** [comment]
Yes tried that several times.  Does not make any difference whether being in airplane mode or not.

**Comment by abhisontakke** [comment]
@greyson-signal  I'm Also facing the same issue, App always crashes after opening and when connected to Internet.
As Internet is disconnected I am able to open app, 
Please let me know how can I install the latest build of .apk, and will that resolve the issue.

Error : 
1. java.net.SocketException: Software caused connection abort at java.net.SocketInputStream.socketRead0(Native Method)
2. Caused by: java.net.ConnectException: Failed to connect to /...ipv4...:443at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:249)
3. onFailure() java.net.SocketException: Software caused connection abort

**Comment by coro1404** [comment]
same error here - 03.02.2024

**Comment by DominikM60** [comment]
Same error started happening to me today - 14.02.2024
Signal starts opening for a moment and after 3 seconds crashes.
I don't see any chats however I can get into one by desktop shortcuts accessed on the phone's main screen.
In such case I can see messages with the selected person but crash happens after 3 seconds anyway.

**Comment by DominikM60** [comment]
Issue fixed by the reinstallation of the app

**Comment by jvenborg** [comment]
I would like to chime in; just happened today. I have never had this issue beforehand. Android 14, Mi A2 Lite, Lineage OS.
It doesn't crash whilst having no network (either in airplane mode or disabling wifi/data). Desktop version running just fine.

Do have logs if needed. Not too sure how to read it myself, but a quick glance seems to show a lot of errors regarding username. Thinking back, I do seem to remember getting prompted yesterday or the day before to select my username - despite having set that a long time ago

I'm really sorry if this is unhelpful, but here is a few lines from the log. Unfortunately, I can't submit from within the app itself hence the issue. Can attach here if need be.

```
04-15 16:42:47.732 23582 23626 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-1
04-15 16:42:47.732 23582 23626 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 23582
04-15 16:42:47.732 23582 23626 E AndroidRuntime: java.lang.AssertionError: java.lang.ClassNotFoundException: org.signal.libsignal.usernames.UsernameLinkInvalidLinkData
04-15 16:42:47.732 23582 23626 E AndroidRuntime: 	at org.signal.libsignal.internal.FilterExceptions.reportUnexpectedException(FilterExceptions.java:70)
04-15 16:42:47.732 23582 23626 E AndroidRuntime: 	at org.signal.libsignal.internal.FilterExceptions.filterExceptions(FilterExceptions.java:150)
04-15 16:42:47.732 23582 23626 E AndroidRuntime: 	at org.signal.libsignal.usernames.Username.fromLink(Username.java:102)
04-15 16:42:47.732 23582 23626 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.RefreshOwnProfileJob.checkUsernameIsInSync(RefreshOwnProfileJob.java:331)
04-15 16:42:47.732 23582 23626 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.RefreshOwnProfileJob.onRun(RefreshOwnProfileJob.java:158)
04-15 16:42:47.732 23582 23626 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
04-15 16:42:47.732 23582 23626 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
04-15 16:42:47.732 23582 23626 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
04-15 16:42:47.732 23582 23626 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: org.signal.libsignal.usernames.UsernameLinkInvalidLinkData
04-15 16:42:47.732 23582 23626 E AndroidRuntime: 	at org.signal.libsignal.internal.Native.UsernameLink_DecryptUsername(Native Method)
04-15 16:42:47.732 23582 23626 E AndroidRuntime: 	at org.signal.libsignal.usernames.Username.lambda$fromLink$2(Username.java:105)
04-15 16:42:47.732 23582 23626 E AndroidRuntime: 	at org.signal.libsignal.usernames.Username.$r8$lambda$Vy-A0jS3IXkliPqixjPVRDT50rU(Username.java:0)
04-15 16:42:47.732 23582 23626 E AndroidRuntime: 	at org.signal.libsignal.usernames.Username$$ExternalSyntheticLambda3.run(R8$$SyntheticClass:0)
04-15 16:42:47.732 23582 23626 E AndroidRuntime: 	at org.signal.libsignal.internal.FilterExceptions.filterExceptions(FilterExceptions.java:143)
04-15 16:42:47.732 23582 23626 E AndroidRuntime: 	... 6 more
04-15 16:42:47.733 23582 23626 E SignalUncaughtException: java.lang.AssertionError: java.lang.ClassNotFoundException: org.signal.libsignal.usernames.UsernameLinkInvalidLinkData
04-15 16:42:47.733 23582 23626 E SignalUncaughtException: 	at org.signal.libsignal.internal.FilterExceptions.reportUnexpectedException(FilterExceptions.java:70)
04-15 16:42:47.733 23582 23626 E SignalUncaughtException: 	at org.signal.libsignal.internal.FilterExceptions.filterExceptions(FilterExceptions.java:150)
04-15 16:42:47.733 23582 23626 E SignalUncaughtException: 	at org.signal.libsignal.usernames.Username.fromLink(Username.java:102)
04-15 16:42:47.733 23582 23626 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.RefreshOwnProfileJob.checkUsernameIsInSync(RefreshOwnProfileJob.java:331)
04-15 16:42:47.733 23582 23626 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.RefreshOwnProfileJob.onRun(RefreshOwnProfileJob.java:158)
04-15 16:42:47.733 23582 23626 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
04-15 16:42:47.733 23582 23626 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
04-15 16:42:47.733 23582 23626 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
04-15 16:42:47.733 23582 23626 E SignalUncaughtException: Caused by: java.lang.ClassNotFoundException: org.signal.libsignal.usernames.UsernameLinkInvalidLinkData
04-15 16:42:47.733 23582 23626 E SignalUncaughtException: 	at org.signal.libsignal.internal.Native.UsernameLink_DecryptUsername(Native Method)
04-15 16:42:47.733 23582 23626 E SignalUncaughtException: 	at org.signal.libsignal.usernames.Username.lambda$fromLink$2(Username.java:105)
04-15 16:42:47.733 23582 23626 E SignalUncaughtException: 	at org.signal.libsignal.usernames.Username.$r8$lambda$Vy-A0jS3IXkliPqixjPVRDT50rU(Username.java:0)
04-15 16:42:47.733 23582 23626 E SignalUncaughtException: 	at org.signal.libsignal.usernames.Username$$ExternalSyntheticLambda3.run(R8$$SyntheticClass:0)
04-15 16:42:47.733 23582 23626 E SignalUncaughtException: 	at org.signal.libsignal.internal.FilterExceptions.filterExceptions(FilterExceptions.java:143)
04-15 16:42:47.733 23582 23626 E SignalUncaughtException: 	... 6 more
```

**Comment by clark-signal** [comment]
Hi @jvenborg your crash is actually unrelated. But that crash in particular should be fixed in 7.4.2

**Comment by jvenborg** [comment]
Hi @clark-signal. Thank you very much! That sounds splendid - that crash is annoying indeed. Impossible to do anything, and woulder rather not reinstall if avoidable, which it seems to be with the update.

**Comment by chromosapiens** [comment]
Any chance that this can be fixed? 
It's 6 mo now, issue is still ongoing

**Comment by mxjp** [comment]
I had the same Issue today after linking a new linux desktop client to my phone and then immediately locking the app while the desktop client was still syncing contacts, etc. Linking the device succeeded somehow, but since then the android app kept crashing immediately after opening it.

I tried all of the things below, but none of those helped:
+ I cleared all app data & cache, then signed into the same account again using the same phone number and existing pin.
+ Putting my sim card in an old phone, signing in on that phone with the existing pin also didn't help and the app started crashing there too.

I then created a new pin and everything is working again since then which makes me think that the cloud storage for my account got corrupted somehow.

Unfortunately, I don't have access to the debug logs anymore.

**Comment by frankbertoldi** [comment]
> I had the same issue today after linking a new linux desktop client to my phone and then immediately locking the app while the desktop client was still syncing contacts, etc. Linking the device succeeded somehow, but since then the android app kept crashing immediately after opening it.

The same happened to me today after linking a new macOS desktop client to my Samsung android 15 phone. Clearing cache or flight modus did not help. I am reluctant to clear data and reinstall, losing all chats.

**Comment by uurtamo** [comment]
pixel 8, android 14, opens for around 0.5 seconds before crashing. this happened starting this morning. in airplane mode i can get about this far:

(attached)
[signal-log-1719012465908.zip](https://github.com/user-attachments/files/15934417/signal-log-1719012465908.zip)

**Comment by frankbertoldi** [comment]
> Clearing cache or flight modus did not help. I am reluctant to clear data and reinstall, losing all chats.

sorry, correction: disconnected from the internet it works normal. and I run android 14.

**Comment by sndrsmnk** [comment]
Chiming in, same thing happened to me just yesterday. Re-installed two Linux laptops, re-linked them and now this morning i noticed the Android app 'crashes'.

I say 'crashes', because the behaviour does not feel like a 'crash': i still get message notifications for chats when i open Signal, they keep showing in the notifications and the short time the app shows, i can see the new messages in the chat overview.

Then if i open one of the notifications, i get to that chat screen, see that chat content, but then get 'backed' out of the chat to the chats overview screen, and then get 'backed' out of the app all together. It feels like something is constantly pushing the 'back' button with about a second delay, if you can imagine.

I am currently not set up to do adb dumps, nor can i reach the settings in Signal to enable debug logs anymore, but this all seems very related to linking Signal Desktop and perhaps closing that app too quickly after having linked or something?

The linked Signal Desktop(s) work flawlessly with the account. Messages sent from there seem to come in on the Android client too.

The fact that i get backed out, screen by screen, reproducible, instead of the app crashing is kinda suss.

Hope this helps.

**Comment by sndrsmnk** [comment]
Perhaps relevant: one of the reinstalled laptops i gave a new name during linking and if i recall stuff just worked after that. The other laptop i reinstalled later that night and gave it the same name as the old session (which i removed before hand in the android app). Perhaps doing this in quick succession triggers it?

**Comment by cdhermann** [comment]
> Re-installed two Linux laptops, re-linked them and now this morning i noticed the Android app 'crashes'.

Almost the same problem I have. I linked Signal on a Linux device. There was an existing link on a macOS device. Suddenly the Signal Android app crashed. In airplane mode the Android app doesn't crash. As soon as I disable airplane mode the app crashes again - no matter if it is already running or if I start it

**Comment by sndrsmnk** [comment]
Great. I f**ed around too much. And if you f** around you'll find out... Now i'm locked out of my Signal account. Great success. :+1: :+1: 

Anyways, reinstalling and restoring from backup yielded the same crash-results.

Then i trashed everything and did not restore a backup, but aparently too many login attempts or whatever, and the pin code i had to confirm every f**ing month suddenly isnt correct anymore and now i am locked out entirely.

So be warned peeps.

If your linked desktop client still works, use that while we hope this six month old issue gets some attention.

**Comment by fgubler** [comment]
Same problem here: tried to connect a linux device yesterday => Signal has been crashing ever since.
Completely unusable now.
I have tried multiple uninstalls and reinstalls - nothing changed.
In flight-mode it works

**Comment by fgubler** [comment]
(not feeling too great about donating to Signal every month anymore, seeing how long this ticket has been open)
I am guessing, something went wrong with the pairing and now every attempt to load the list of paired devices makes the app crash => a reset-functionality would be worth its weight in gold

**Comment by fgubler** [comment]
By the way, I tried it with a different phone-number on the same device which worked like a charm.
Ofc that is useless to me but at least it proves that the problem is not the phone but is server-based and tied to the specific account.

**Comment by uurtamo** [comment]
> By the way, I tried it with a different phone-number on the same device which worked like a charm. Ofc that is useless to me but at least it proves that the problem is not the phone but is server-based and tied to the specific account.

oh no. that would be a bad scene if it's what's happening for me.

**Comment by fgubler** [comment]
> I then created a new pin and everything is working again since then which makes me think that the cloud storage for my account got corrupted somehow.

That worked for me as well 🤩 I could even restore my old backups.
This is exactly what I did (probably some steps are not necessary but...).
Btw. I had already uninstalled and reinstalled the app a few times before that. But I assume that has no effect.

1. Started Signal in Flight-Mode
1.  Went to _Settings_ - _Account_
1. Disabled the _Registration Lock_
    - This requires an internet-connection, so while on the correct screen, I disabled flight-mode and immediately pressed the slider.
    - This made the app crash but not before the setting hat been changed
1. Re-started the app and went to _Settings_ - _Account_ - _Advanced PIN settings_ and clicked _Disable PIN_
	 - This needs an internet-connection again but you can already click the button and then a loading-bar appears. While that is turning, disable flight-mode.
	 - That should then work and the app should stop crashing.

If you have never uninstalled and re-installed the app or have already re-applied your backups, this might be enough for you and you can skip the next few steps and just set a new PIN. But for me, I went a bit further to get my old chats back.

 - Uninstalled and re-installed the app one last time.
 - On first app-start, I selected the backup to be restored.
 - After having entered my phone-number to "log-in", it asked for my PIN again. 
         - That was strange because I had just disabled my PIN, right???
         - Well my first reaction was to just enter the old PIN again... Stupid mistake => that lead to the crash happening again.
             - Therefore I had to uninstall and re-install the app again and start from scratch. => you can avoid that.
	 - Do **not** enter your old PIN here but click _skip_ in the top-right corner.
	 - As a consequence, it will tell you that you will now have to authenticate by SMS-code. That is ok => do it.
	 - In the next step, it suggests creating a new PIN. I was a bit sick of PINs so skipped that for now.
 - Now the app should start normally with all your chats restored and no crashing 🥳🥳 time to celebrate (and perhaps consume some not strictly speaking healthy beverages of your choosing).
 - Now you can actually go to settings again and set a new PIN (or the old one) and it should still all work.

**Comment by uurtamo** [comment]
Dude. Totally worked.

It's funny, because for a brief second it appears as if you're going to
leave all of your messages unencrypted in the cloud by removing the PIN.

My old messages are still available on my desktop, but not on my phone, so
I guess that there's a local copy on the desktop.

Thanks so much for figuring this out.

**Comment by fgubler** [comment]
🥳🥳
Very welcome

**Comment by KundlJ** [comment]
I am experiencing this issue as well after a similar situation. In my case it was a Windows client.

I'd had issues linking this machine after getting a new phone, and had uninstalled then reinstalled the desktop client. The desktop client now is linked and works, my phone can sometimes get notifications through but that's it.

Hope this gets some attention soon.

> I had the same Issue today after linking a new linux desktop client to my phone and then immediately locking the app while the desktop client was still syncing contacts, etc. Linking the device succeeded somehow, but since then the android app kept crashing immediately after opening it.
> 
> I tried all of the things below, but none of those helped:
> 
> * I cleared all app data & cache, then signed into the same account again using the same phone number and existing pin.
> * Putting my sim card in an old phone, signing in on that phone with the existing pin also didn't help and the app started crashing there too.
> 
> I then created a new pin and everything is working again since then which makes me think that the cloud storage for my account got corrupted somehow.
> 
> Unfortunately, I don't have access to the debug logs anymore.

**Comment by chromosapiens** [comment]
I think your issues are completely different than the original issue.  
My issue had probably nothing to do with the desktop client. 
Also I cannot change the pin since it is always crashing (also in airplane mode) unfortunately.

**Comment by fgubler** [comment]
Ok, that makes sense.
I guess, I will create a separate Issue, then.

**Comment by D0MF** [comment]
I'm having a very similar issue. 
[signal-log-1724709596454 (1).zip](https://github.com/user-attachments/files/16754714/signal-log-1724709596454.1.zip)
Logs attached. 
And logcat: 
[logcat_signal.txt](https://github.com/user-attachments/files/16754717/logcat_signal.txt)
I tried the disabling pin workaround, it did NOT work. I've completely removed the app and reinstalled, restoring from backup, twice now. Once thing I've noticed is that when it's crashing, and I'm in airplane mode, I open signal and the top message is "Something went wrong with your username, it's no longer associated to your account. You can try and set it again or choose a new one" - I've re-set it a couple times today (to the same thing, because it's a specific one I want to keep) but it keeps coming back and the app keeps crashing. I'm on signal ALL day long, I really need to be able to get this working!

**Comment by k-bx** [comment]
Also affected by this terrible bug. Reinstalled Signal multiple times, still it starts crashing very quickly. The symptoms are the same as for D0MF.

**Comment by nikk0s** [comment]
Hi,
Same problem for me since last week after Signal reinstallation and linking with my linux desktop client. 
Never have this problem before, and disable the Registration Lock and PIN doesn't solve it
Need a fix please :pray: 

Phone :Samsung A15
Signal version: 7.14.2
Android 14

Thanks for your support

**Comment by D0MF** [comment]
Just a note to everyone having the problem, since it doesn't seem like we're getting an official response to this bug - I updated to the Beta update channel last night and Signal has been stable since then! I do worry about using a beta for the long term, just because I'm part of multiple organizations who use signal exclusively for communications, and it's extremely difficult for me when it's down/I'm not able to use it.

**Comment by k-bx** [comment]
@D0MF legend! It works for me too.

**Comment by nicholas-signal** [comment]
Signal v7.15.4 is now available on Google Play as well as [our website](https://signal.org/android/apk/). Please let us know if the crash is resolved.

**Comment by pirat89** [comment]
Note for others: the mentioned version has been crashing for me as well. However, after the phone reboot, it crashed just once (the crash has not been immediate as before) and another since another one reopen it works already without any issues. Android 14

**Comment by Juergo** [comment]
Issue occurs on my Android Phone Signal version 7.32.3 since yesterday. Stable since Migrating to this Phone in 2023.
No remedy so far. for some 10 Minutes I was in the aapp again, but no messages sending possible, then it crashed again.

**Comment by jumson** [comment]
On Android Pixel 7 Pro (Android 15 w/5 Jan 2025 security update); 
Signal app version 7.33.2
Immediate crashing whenever I open. 
Airplane mode doesnt help. 
Open recent message thing doesnt help.
It worked 13 Feb 2025, and now 14 Feb 2025 it is broke.
Updated Android Security update to 5 Feb; still no change in Signal App behavior.

**Comment by jormasoul** [comment]
Yeah so this is happening to me with v7.36.2, as posted earlier in https://github.com/signalapp/Signal-Android/issues/13599#issuecomment-2708940793. There's also a log posted by me.

I just joined the beta program and updated – doesn't work. Changed PIN – doesn't work. Turning off data lets me browse the app without crashing but obviously it's a bit useless without a functioning internet connection.

**Comment by Juergo** [comment]
The only thing that helped was transferring account to a second phone,
deinstalling reinstall and transfer back.
This functioned because I very occasionally could reenter defective
installation for some minutes.
Support couldn't help

jormasoul ***@***.***> schrieb am Do., 13. März 2025, 20:48:

**Comment by ryanpaton** [comment]
About a week ago I transferred my signal account from my OnePlus 7t to a Pixel 8a currently running GrapheneOS Android version 15, version code 35, build number 2025050700.

It has worked perfectly fine with my transferred message logs for several days on my pixel 8a then the other day it just stopped being able to launch and would open for a split second then crash and close with no error messages being displayed. 

The weird thing is that I can still open the app and send messages if a notification pops up and I click on that it will open an individual message thread with all the history intact. 

When I try and press the back button to get into the main screen of the app it immediately crashes and closes. 

Does anyone know what my best bet is? I would love to not lose some of my recent messages some of which I have not even read yet because I can't access them. 

I have tried restarting my phone multiple times, I even tried letting the battery run out as I saw on one post but that did not help and going into airplane mode does not help either. 

I couldn't access the logs through the signal app but I went into the app settings and found some logs for signal I'm not sure if these are the proper logs because I'm not a programmer... It seems to show errors tho

Thanks so much for all you do.

-Ryan

[Signal log c2888c21898f.txt](https://github.com/user-attachments/files/20353472/Signal.log.c2888c21898f.txt)

**Comment by mtang-signal** [comment]
> About a week ago I transferred my signal account from my OnePlus 7t to a Pixel 8a currently running GrapheneOS Android version 15, version code 35, build number 2025050700.

We have a fix for your issue that should hopefully be coming out in a few hours (pending play store review)! In the meantime, I believe you can open the app in landscape mode and it should be able to work then. Sorry for the inconvenience to begin with but hopefully it'll be sorted out very soon.

**Comment by chromeragnarok** [comment]
Had the same issue. Started happening on my OP 13. Can confirmed that the app opens fine when I'm on landscape and crashed right away when on vertical.

**Comment by ryanpaton** [comment]
> We have a fix for your issue that should hopefully be coming out in a few hours (pending play store review)! In the meantime, I believe you can open the app in landscape mode and it should be able to work then. Sorry for the inconvenience to begin with but hopefully it'll be sorted out very soon.
----------

Thank you so much for your hard and amazing work @mtang-signal !  🌈🌟💖😻

also thanks for confirming @chromeragnarok 😁

**Comment by mr-salty** [comment]
I reported this to [signal support](https://support.signal.org/hc/en-us/requests/new) - unfortunately the email I got back doesn't include a bug # or the contents of my original report, but I probably should have filed it here anyways.

I recently upgraded to a Pixel 9 pro (previously I was using z filp [3-6] and a pixel 3a and never saw the issue), I transferred all the messages and like [ryanpaton's comment](https://github.com/signalapp/Signal-Android/issues/13255#issuecomment-2895461842) it worked fine for a week or so then started crashing immediately on startup.

I did not try switching the phone orientation, but I did notice that if I long-pressed the icon on the pixel launcher it would show me a list of recent conversations, and if I picked one of those it worked fine.  but, if I pressed the "back" arrow in the upper right to go back to the list it would crash immediately.

I *think* what ended up fixing it was, I have the signal app on my desktop windows PC and noticed it seemed to be showing all recent conversations.  There was one with unread messages - it was a group chat with 4 people, and the message in question was pure text - no images, emoji, etc.  After I read that conversation on the PC app I tried to start signal on the phone and it worked, and hasn't crashed since.  I just tried marking that conversation unread and closed and re-opened the app (both normally and "force stop") and it doesn't crash.
