### ISSUE TITLE
Tapping notifications doesn't go to message

### ISSUE THREAD

**Issue by Paddy5150** [signalapp/Signal-Android#13292]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since Samsung updated their One UI about a week ago, when I get a message notification for Signal nothing happens when I tap on it. It does not take me to the message, or even the Signal app.

Same with chat bubbles. They disappear but don’t click through to anywhere.

Is this a known bug?
### Steps to reproduce
- anyone sends me a message I tap the notification. Samsung Galaxy S23. Android 14

**Actual result:** the notification disappears, but it doesn't open the message
**Expected result:** it should open the message that was notified about

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

### Link to debug log

https://debuglogs.org/android/6.40.5/3c0764332916e9d7fb2b52b8461f918ea65955a7f3721db77cfdc26508f2ba99

**Comment by DinoGoEatChu** [comment]
I am having the same issue.. and bubbles make the os crash .. I have spent probably 8 hours today looking through ways I'm possibly missing to enable the chat to work, if not bubbles then at least in the notification drawer.

**Comment by Paddy5150** [comment]
I fixed it by uninstalling and reinstalling the app.
Remember your backup and your key,


________________________________

**Comment by DinoGoEatChu** [comment]
> I fixed it by uninstalling and reinstalling the app. Remember your backup and your key,
> […](#)


I tried that today, but it didn't seem to change anything. Just reset all of my notifications settings for signal

**Comment by mmalolepszy** [comment]
This is still an issue for me on Galaxy S22 with Android 14.

**Comment by DinoGoEatChu** [comment]
Also still an issue for S23 ultra, on Android 14

**Comment by cody-signal** [comment]
For those experiencing the issue, is this with all notifications or just bubbles? Also, are you using the screen lock feature?

**Comment by DinoGoEatChu** [comment]
Issue with bubbles. What is the screen lock feature? Is that when you have a password/pin enabled on the device? I do have a pin enabled on my device if that helps?

**Comment by cody-signal** [comment]
Thanks, we're actively working on the bubbles thing.

**Comment by mdawid** [comment]
@cody-signal It's not only the bubbles. Clicking on a notification on notification drawer does not do anything. Yes I do use lock screen, but notification is clicked on an unlocked phone.

**Comment by cody-signal** [comment]
@mdawid are you using the in-app lock or just the phone lock? I'm asking about the in-app (Settings->Privacy) setting.

Additionally, are you on Samsung?

**Comment by mdawid** [comment]
> @mdawid are you using the in-app lock or just the phone lock? I'm asking about the in-app (Settings->Privacy) setting.
>
no, Signal lock is disabled

> Additionally, are you on Samsung?

yes, Samsung S22+, Android 14

**Comment by Kaligula0** [comment]
Same here with notifications (on unlocked phone). 
- Samsung S22 (SM-S901BZKGPLS)
- Android 14, One UI 6, security updates of 1/Feb/2024
- device lock (pattern), in-app lock disabled

**Comment by Kaligula0** [comment]
Same here with notifications (on unlocked phone). 
- Samsung S22 (SM-S901BZKGPLS)
- Android 14, One UI 6, security updates of 1/Feb/2024
- device lock (pattern), in-app lock disabled

**Comment by LinuxOnTheDesktop** [comment]
'Wontfix' does not seem the most apt description - or result - of 'staleness'.

I experience a similar bug, namely, I get a notification of a new message, I tap the notification, and no new message is there - until thirty seconds or so later, at which point a new message does appear.

**Comment by LinuxOnTheDesktop** [comment]
'**stale** closed this as **completed**' (_sic_) is something of a self-contradiction.

I noticed recently that Signal received an update. The changelog said that the update added features. I suggest that the developers focus instead upon making the existing features work well.
