### ISSUE TITLE
Bubbling conversations does not work on Android 14 / Samsung devices

### ISSUE THREAD

**Issue by TheOnlineUser** [signalapp/Signal-Android#13325]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Conversations don't bubble in Android 14 when using Samsung phones. Other apps do bubble properly so it's not that Samsung broke the feature.

When you open a conversation in Signal, clicking the 3 dots menu and then "create bubble" simply adds a notification about the conversation to the notification bar but doesn't actually pop out a bubble like other apps do. Notification can't be clicked (clicking it crashes the system UI and takes you to the lock screen—and does not bubble.

In Android 12 and 13, you could follow the following steps to enable it:
1. Enable "Multi Window for all apps" in Settings > Labs 
2. Enable Bubbles (Settings > Notifications > Advanced settings > Floating notifications > Bubbles)
3. In the operating system settings, enable bubbles for Signal. This can be tricky, but you can reliably get to it by doing this:
a. Go to a specific chat
b. 3-dot menu -> Chat Settings -> Sounds & notifications -> Custom notifications
c. Turn on "Use custom notifications"
d. Tap "Customize"
e. You should now be in the operating system's Settings app.
f. Check "Bubble this conversation"
g. Tap "Bubble settings for this app"
h. Change to "All" or "Selected only"
([See this comment on another issue report](https://github.com/signalapp/Signal-Android/issues/12178#issuecomment-1652231525))

However, this no longer works.

### Steps to reproduce
- set Signal conversation to allow bubbling in notification settings
- open conversation in Signal
- click 3 dots > click Create bubble 
- no bubble; clicking notification that appears crashes the phone's system UI.

**Actual result:** doesn't bubble
**Expected result:** should create a floating bubble that can be tapped to open the conversation

### Device info

**Device:** Samsung Galaxy S23 Ultra
**Android version:** 14
**Signal version:** 6.41.3

### Link to debug log

https://debuglogs.org/android/6.41.3/70a4934a25125071d1fc67fb3aca266feba451f6e79879356f41bc6bae89270d

**Comment by gooomis** [comment]
Same here. I've reported it in #13177, which was closed. I've attached more info there.

**Comment by voedev** [comment]
> Same here. I've reported it in #13177, which was closed. I've attached more info there.

This is still a problem on stable builds for the Galaxy S23 series on Android 14. Closing this was and is premature.

**Comment by lsdxm** [comment]
Same issue here. Trying to make a bubble just created a blank notification, clicking it sends me to the lockscreen.

**Comment by Zeklandia** [comment]
After the Jan. 1st security patch update (the first update since the Android 14/OneUI 6.0 upgrade), I'm no longer experiencing this issue.

**Comment by gooomis** [comment]
> After the Jan. 1st security patch update (the first update since the Android 14/OneUI 6.0 upgrade), I'm no longer experiencing this issue.

No Jan 2024 patch here yet though, I really hope it fixes it :/

**Comment by Zeklandia** [comment]
After using it for some time, I can say that the crashes and freezes aren't happening anymore, but Signal's notifications and bubbles are still broken. Bubbles were briefly working after the upgrade, but the vast majority of the time they simply disappear when I open them. Notifications cause nothing to happen when I tap on them. After the bubbles disappear, they do not show as options on the screen for opening additional chat bubbles.

**Comment by volozo** [comment]
I wonder when this problem will get fixed. I use a Galaxy S23 with Dec 2023 security patch. Bubbles do work with the normal Messages app, like everytime. But for some reason, they aren't working for Signal. Yes, it works for Signal once in a while, but that's only when I restart my phone. And after an hour or so, it goes back to the same problem. No bubbles. No pop-up notification on the upper edge of the screen. Only a gitchy/irresponsive notification in the notification shade, which doesn't open the app. Please someone fix this issue.

**Comment by 00raq00** [comment]
For mi 13t pro with android 14 I have same problem with bubble notification. Only for signal it doesn't work properly.

**Comment by gooomis** [comment]
@alex-signal let me know if there is anything I can provide to make this issue easier to resolve and close.

**Comment by lsdxm** [comment]
Still happening. Really wish it would be addressed, I'm now having to use other, less secure messengers because I very much need to be able to bubble conversations.

**Comment by gooomis** [comment]
Guys can we get any update on this? Do you think it can be fixed, and if so, would it be in a near time? @alex-signal @greyson-signal

**Comment by cody-signal** [comment]
We are actively looking into this. Unfortunately, it's not something that can be resolved solely by us.

Please refrain from tagging specific people, simply posting is enough to get our attention.

**Comment by jasniec** [comment]
I have Samsung S22 with android 14, newest samsung update. I fixed the issue enabling:
1. Advanced Features -> Labs -> Multi window for all apps
2. Developer options -> multi window for all apps

The first setting didn't make a change, only the second one fixed the issue (but I have both enabled)

I'd search for issues in app resize options - developer options mention that it enables non-resizable apps to resize, so maybe this will help.

Side note: other apps such as sms text in other apps were properly shown as a bubble before I fixed signal notifications

**Comment by gooomis** [comment]
> The first setting didn't make a change, only the second one fixed the issue (but I have both enabled)

Still not working for me. 

> Side note: other apps such as sms text in other apps were properly shown as a bubble before I fixed signal notifications

Yup, that was the case for me as well, that all other apps are "bubbling" correctly, but Signal app is not responding to these changes, resulting in the empty notification which on-tap restarts SystemUI.

**Comment by gooomis** [comment]
Taking it all back - it has indeed worked. I'll see how much time it takes to break though, there were cases that it'd worked and stopped unexpectedly.

**Comment by lsdxm** [comment]
> We've confirmed that this is actually an issue on Samsung's side. They've apparently blacklisted us from showing bubbles because of some bug we had in the past. We're working with them to resolve it, but it's slow-going.

Lol great solution Samsung... So there was apparently a bug one time, and their idea to deal with that is to intentionally break a feature in such a way that makes it seem like an even worse bug is happening. Oye vey.

**Comment by CelticWraith** [comment]
I haven't been able to disable signal bubbles (don't want them).

Tapping signal notifications and nothing happening is the third most irritating thing.

Opening Signal and no longer being able to use the keyboard in it or any other app until rebooting is the second most irritating thing.

Signal opening up in what appears to be a pop-up window view that stays open over every other app (including other instances of Signal) that can't be closed until rebooting the phone is the most annoying thing.

These issues seemed to start with an update that mentioned bubbles 1-2 months ago, which was when Signal bubbles first started appearing on my phone.

I actually upgraded my S22 Ultra to the S24 Ultra yesterday largely due to the signal issues, only to find I wasted my cash as the issues immediately persisted on the S24 Ultra.

**Comment by nicholas-signal** [comment]
> Any way for interested parties to bother Samsung about this in any way that'll be meaningful?

Unfortunately not.

**Comment by Ark9975** [comment]
I am having a problem on my S24 Ultra where I can see bubbles but pressing them immediately dismisses them.

**Comment by morta5** [comment]
Signal bubbles seem to work for me again. 
I am using the latest Signal Beta and I am on the April security patch.

**Comment by Ark9975** [comment]
> Signal bubbles seem to work for me again. 
> I am using the latest Signal Beta and I am on the April security patch.

My bubbles also seem to be working. Oneui  6.1 with April patch I am not on the beta though.

**Comment by Kaligula0** [comment]
S22 @One UI 6.0 April patch and Signal stable, wiped cache → still bubbles don't work for me.

**Comment by morta5** [comment]
@GBT7 I am not on One UI 6.1 and signal bubbles work for me again

**Comment by nicholas-signal** [comment]
Hello everyone,

As many of you have noticed, we have cooperated with Samsung to restore Bubble privileges to Signal.

If anyone continues to have issues with Bubbles, first make sure that you have updated your Samsung device to the latest available OS update, and that your device is freely able to contact Samsung's servers to receive updated configurations.

If any new issues with Bubbles arise, please file a new GitHub issue, as I am considering this specific issue completed.

**Comment by MMM2441** [comment]
I have a Samsung A54
Instead of a bubble set up in the Signal app, you can enable Floating Notifications in your device's settings.  
Settings-Advanced Settings-Floating notifications-Smart pop-up view-include app in the list

**Comment by MMM2441** [comment]
I'm not sure what you were referring to; once your floating notifications are enabled for the app, a bubble will pop up whenever there is new activity. It just takes one click to open a bubble. It may open the homepage, at which point you would need to choose which chat you want to look at. The way I see it, until Signal fixes the problem, floating notifications are the next best thing. 

https://github.com/user-attachments/assets/d2f04cca-55ba-4a7e-8d35-f19f82d4d5fe
