### ISSUE TITLE
Android "Share" menu does not display the most recent/shared-to contacts

### ISSUE THREAD

**Issue by breversa** [signalapp/Signal-Android#13398]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sharing a file from any another app, the suggested Signal contacts are neither the most recent ones, nor the most shared-to ones.

### Steps to reproduce
- open the file manager
- select a file
- tap the "Share" button

**Actual result:** The Android share menu suggests Signal contacts to share the file to, but these are not the most recent ones, nor the most frequently shared-to ones. They seem to be random. Also, the share menu icons take a few seconds to appear and be selectable.

**Expected result:** The Android menu should suggest the latest contacts I’ve interacted with, or those to whom I have the most frequently shared files with.

### Screenshots
![obscura1706781990793](https://github.com/signalapp/Signal-Android/assets/2071276/ecabb289-a54a-4480-9ffa-4de15826420c)
(contacts blurred for privacy reasons) 

### Device info
**Device:** Samsung Galaxy S9
**Android version:** Android 11 (/e/OS 1.17)
**Signal version:** 6.44.3

**Comment by breversa** [comment]
![Screenshot_20240201-110048_Système_Android](https://github.com/signalapp/Signal-Android/assets/2071276/9ceb2805-10b9-442d-a784-36d6716a6651)
(contacts blurred for privacy reasons)

**Comment by fwinn** [comment]
The problem does not appear for me on version 6.44.3, Google Pixel 6 with Android 14

**Comment by tedgravlin** [comment]
I have the same issue, Pixel 7a Android 14
Logs: https://debuglogs.org/android/6.47.0/536158454094eb89bd6b8d4c580c488f4a1fc0226d5a634cd7f79a1fc6ee178b

**Comment by sudansh** [comment]
The sharesheet is managed by Android OS and we can't control the order in which those are shown. 
ref: https://developer.android.com/training/sharing/send

**Comment by breversa** [comment]
But the targets list has to be fed to/read by the Android Sharesheet somehow, hasn't it? There's a reason why the targets are displayed in that order (even if the reason doesn't make sense)... 🤔

**Comment by alex-signal** [comment]
The targets are fed but how they're cached and managed are on the OS.

**Comment by breversa** [comment]
Thank you for this in-depth analysis and solution suggestion!

**Comment by breversa** [comment]
After updating my phone to Android 12 (/e/OS 2.1), I still have that issue, but the share menu appears without delay now, so that’s already a better thing.

**Comment by breversa** [comment]
Erratum:
Following the upgrade to Android 12, the share menu is not empty, with no contact suggestion. :-/
It doesn't disturb me a lot ; at least it's much quicker that way.

**Comment by genodeftest** [comment]
The issue is still present.

**Comment by genodeftest** [comment]
Can anyone who has signal installed on an android tablet (or a foldable phone or any other android device with a screen that is way larger than a regular smartphone) please check how many contacts/items are shown in the direct share panel? Does anyone see a number that is different from 4?

Why I'm asking: If Android will never show more than 4 items in the direct share panel, I would create a PR to change the code I mentioned above to make Signal only pass the top 4 contacts instead of the top 150.

**Comment by breversa** [comment]
Sorry, I don't have such a device but I wholeheartedly support your suggestion.

**Comment by genodeftest** [comment]
Despite the change I proposed being merged and the update rolled out months ago, I still see the same behavior. In other words, my change did not fix the problem, it is caused by something else.

@breversa or @greyson-signal can you please reopen this issue?

**Comment by oneguynick** [comment]
> Despite the change I proposed being merged and the update rolled out months ago, I still see the same behavior. In other words, my change did not fix the problem, it is caused by something else.
> 
> [@breversa](https://github.com/breversa) or [@greyson-signal](https://github.com/greyson-signal) can you please reopen this issue?

I can confirm the same behaviour on Oneui 8 in both foldable screen sizes on Fold7.

**Comment by datennutzung** [comment]
This annoys me too, to great lengths, so I also did some digging. 
Signals list of shortcuts published with `setDynamicShortcuts` is correct (with the exception of the order of the pinned chats #14642). That means, that android mostly ignores the order of these shortcuts when it comes to the ordering of the Direct Share targets.
In the [developer docs for direct share](https://developer.android.com/training/sharing/direct-share-targets#track-shortcut-usage-comms-apps), it is stated, that an app can "improve [its] ranking in the Android Sharesheet by reporting [...] outgoing and incoming messages [...] through [ShortcutManagerCompat.pushDynamicShortcut](https://developer.android.com/reference/androidx/core/content/pm/ShortcutManagerCompat#pushDynamicShortcut(android.content.Context,androidx.core.content.pm.ShortcutInfoCompat))."
Signal does do that. On recieved and sent messages it runs the [`ConversationShortcutRankingUpdateJob`](https://github.com/signalapp/Signal-Android/blob/8b2aeba3bdda6543798b01cc4739ef26d2a862ee/app/src/main/java/org/thoughtcrime/securesms/jobs/ConversationShortcutRankingUpdateJob.kt#L74), which calls [`ConversationUtil.pushShortcutForRecipientSync`](https://github.com/signalapp/Signal-Android/blob/8b2aeba3bdda6543798b01cc4739ef26d2a862ee/app/src/main/java/org/thoughtcrime/securesms/jobs/ConversationShortcutRankingUpdateJob.kt#L74).
```java
/**
 * Synchronously pushes a dynamic shortcut for the given recipient.
 * <p>
 * The recipient is given a high ranking with the intention of not appearing immediately in results.
 *
 * @return True if it succeeded, or false if it was rate-limited.
 */
@WorkerThread
public static boolean pushShortcutForRecipientSync(@NonNull Context context, @NonNull Recipient recipient, @NonNull Direction direction ) {
  List<ShortcutInfoCompat> shortcuts  = ShortcutManagerCompat.getDynamicShortcuts(context);
  return pushShortcutForRecipientInternal(context, recipient, shortcuts.size(), direction);
}
```
I believe this *"The recipient is given a high ranking with the intention of not appearing immediately in results."* is wrong. It tells Android, that a person with which you interact a lot is not as important. With `pushShortcutForRecipientInternal(context, recipient, shortcuts.size(), direction);` it sets the rank hint of the shortcut to `shortcut.size()`, so the lowest rank it could have. And when we look at the available direct targets in our phones, we can see the effect that has. When you message someone on your direct share list, they disappear from that list and someone else (someone you haven't messaged in quite some time) appears on it.

I believe something that could fix the Direct Share mess, is just not setting a rank hint (which causes it to be 0) and letting android figure out whats the best order. If setting the rank hint is preferred, it should be set to a value that preserves the order of the dynamic shortcuts, something like this:
```java
/**
 * Synchronously pushes a dynamic shortcut for the given recipient.
 * <p>
 * The recipient is given the ranking it has from the dynamic shortcuts with the intention of not changing the order of the ranking
 *
 * @return True if it succeeded, or false if it was rate-limited.
 */
@WorkerThread
public static boolean pushShortcutForRecipientSync(@NonNull Context context, @NonNull Recipient recipient, @NonNull Direction direction ){
  Recipient resolved   = recipient.resolve();
  String shortcutId = getShortcutId(resolved);
  List<ShortcutInfoCompat> shortcuts  = ShortcutManagerCompat.getDynamicShortcuts(context);
  int rank = shortcuts.size();
  for (ShortcutInfoCompat shortcut: shortcuts) {
    if (shortcut.getId().equals(shortcutId)) {
      rank = shortcut.getRank();
      break;
    }
  }
  return pushShortcutForRecipientInternal(context, recipient, rank, direction);
}
```

could you @genodeftest maybe test out if this works? i cant compile signal on my pc

and since this issue is obviously not fixed, could someone @breversa or @greyson-signal please reopen this issue?

**Comment by wertzuz** [comment]
Please be reminded having them ordered by any means seems like a bog privacy concern since it can be seen without unlocking the App.

**Comment by datennutzung** [comment]
> Please be reminded having them ordered by any means seems like a bog privacy concern since it can be seen without unlocking the App.

Actually not. When the screen lock is active the shortcuts are cleared and aren't getting pushed. [(see the code here)](https://github.com/signalapp/Signal-Android/blob/8b2aeba3bdda6543798b01cc4739ef26d2a862ee/app/src/main/java/org/thoughtcrime/securesms/jobs/ConversationShortcutRankingUpdateJob.kt#L68)

**Comment by genodeftest** [comment]
@datennutzung wrote:

> could you @genodeftest maybe test out if this works? i cant compile signal on my pc

I'm sorry, I haven't set up a build environment for Signal on my machine. I'll be unable to test this now or any time soon. It would be nice if someone from Signal could do that.

**Comment by jeffrey-signal** [comment]
Fixed in 8.3.0!

**Comment by newhinton** [comment]
At least to me, it still seems unfixed. (8.4.2)

If i want to share a picture to my partner, i only get 3 groups i don't actively participate in. (They aren't even the most recently active groups)
I'd expect chats that had recent activity/active participation would be shown first.


Is this a caching issue that android still has old data and it takes a few weeks to properly update the share target statistics?

**Comment by UserX404** [comment]
@jeffrey-signal 
This is also still an issue on my side.

https://debuglogs.org/android/8.6.1/93999210c11f194b466e44bfa14f58b7eec1c8a1c0509f27c5deb735d2b967b3

**Comment by tedgravlin** [comment]
Hey @newhinton @UserX404 - I was having the same issue but I believe there is actually a "cache" of some kind and I was able to clear it by following these steps:

* Android Settings > Notifications > Conversations
* Tap "Clear Recent Conversations"

After doing that, Signal started showing the correct contacts in the share menu.

This was on Android 16, GrapheneOS, so YMMV

**Comment by jeffrey-signal** [comment]
Let us know if [the above steps](https://github.com/signalapp/Signal-Android/issues/13398#issuecomment-4226313233) don't resolve the issue for you @newhinton @UserX404

**Comment by edisondotme** [comment]
> Hey [@newhinton](https://github.com/newhinton) [@UserX404](https://github.com/UserX404) - I was having the same issue but I believe there is actually a "cache" of some kind and I was able to clear it by following these steps:
> 
> * Android Settings > Notifications > Conversations
> * Tap "Clear Recent Conversations"
> 
> After doing that, Signal started showing the correct contacts in the share menu.
> 
> This was on Android 16, GrapheneOS, so YMMV

**Wow**! This worked for me. **Thank you so much**, this issue has been ongoing for so long, glad to finally have a solution.

**Comment by newhinton** [comment]
Hmm, it did change the chats shown. But it's still not 'recent' chats.

There is even a chat that is marked as "not on signal anymore".

I'll wait a couple of days and do the cleanup again and report back. But right now, its still weird.

**Comment by newhinton** [comment]
@jeffrey-signal 

So, at least for me the share targets are still weird. They are a little bit less 'static', but they are still nonsense.
I currently only have groups, but not even the most recently active ones, let alone the last used single-chats. I am pretty sure that i even have one chat pinned, that does not show up, but i can't guarantee that right now. (I did have a pinned one in the past, which was displaced by unimportant ones)

I am using grapheneos, so i'll check up with them too.


Edit:

It seems [this](https://discuss.grapheneos.org/d/10312-how-to-customize-share-menu) helps. (Disable the signal app via Settings>Apps>Signal>Disable, and then enable it again)

That seems to have cleared all the old garbage data, and now 3 of the 4 "pinned" (pinned in signal, not the share dialog) chats show up. Pinning in android however, seems to be broken. Is that something apps influence?

That said, i don't think this is fixed long term, at least for me. The order of the three pinned items is still not following a logic i understand. Now i'd expect them to be shown "in order", that is ordered by when they had their last interaction.
That is not the case. I get three items, and it is not the oldest one missing.

**Comment by genodeftest** [comment]
> It seems [this](https://discuss.grapheneos.org/d/10312-how-to-customize-share-menu) helps. (Disable the signal app via Settings>Apps>Signal>Disable, and then enable it again)

This option seems to not be available on some Android flavors. Is it possible that it is only available on Graphene OS? At least on my almost stock Android (15, Fairphone 4), this option does not exist. I _could_ only _uninstall_ Signal, but I don't want that.

**Comment by newhinton** [comment]
@jeffrey-signal No, after a couple of days it started flooding the recommendations again with useless chats. For me, its still broken.


Though the pinning-issue is defintively an android bug. One that exists at least for a couple versions, and it seems google does not care about that problem.

**Comment by datennutzung** [comment]
> It seems [this](https://discuss.grapheneos.org/d/10312-how-to-customize-share-menu) helps. (Disable the signal app via Settings>Apps>Signal>Disable, and then enable it again)

This worked for me. I'm on Graphene as well. The ordering of the chats after disabling and reenabling is the one Signal sends to Android. Unfortunately this is not completely correct (as mentioned in #14642) as the order of the pinned chats is reversed. 
I cant see any issue with how Signal is handling the Direct Share Targets though. I think the rest of the weirdness just comes from Android
