### ISSUE TITLE
Signal App keeps on crashing

### ISSUE THREAD

**Issue by ralphie02** [signalapp/Signal-Android#13599]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
App keeps on crashing, I'm not sure why...

### Steps to reproduce
- Click icon to open the app

Not sure if this helps, but the last thing I did was forward myself an image from "Note to Self" into the same "Note to Self" chat because it's on phone but not on my computer's signal app (I recently switched computers..). Overall, pretty shitty experience and now I can't seem to even use the app it just keeps on crashing - I've already tried re-installing the app and restarting my phone...

EDIT:
- Turning off mobile data/wifi seem to stop the app from crashing but it's obviously useless without data...

**Actual result:** App minimizes/closes and I proceed to go back to my home screen

**Expected result:** I should be able to open the app, navigate and message people

### Device info

**Device:** Pixel 5
**Android version:** 14
**Signal version:** 7.8.1

### Link to debug log
I can't. The app is broken

EDIT:
Got the log when I turned off data/wifi
[signal-log-1718958262102.zip](https://github.com/user-attachments/files/15924989/signal-log-1718958262102.zip)

**Comment by eastcw** [comment]
This also just started happening to me today

**Comment by alex-signal** [comment]
Hi all! This has been resolved in `7.9.x`, which is currently in Google Review Purgatory (tm)

Apologies for the inconvenience!

**Comment by jimbohostetler** [comment]
> Hi all! This has been resolved in `7.9.x`, which is currently in Google Review Purgatory (tm)
> 
> Apologies for the inconvenience!

Is the APK available? I still see 7.8.1 on [signal.org/](https://signal.org/android/apk/)

**Comment by ralphie02** [comment]
@alex-signal Good to know, thanks for the letting us know!

I was wondering though, without getting into details, do you know the root cause? I didn't update my phone nor the app recently so I'm not quite sure what would cause this.

**Comment by ralphie02** [comment]
Managed to restore usage of the app by creating a new pin

When restoring my backup, at some point it asks for the PIN (the old pin used on the app). I tried to skip it but it insisted on a PIN and the verbiage changed to "create PIN". I did and the app no longer crashes! I'm not sure how android apps work but I think the old PIN is the issue. It somehow got corrupted and creating a new one purges the issue, or something like that 🤷

**Comment by eastcw** [comment]
> > Hi all! This has been resolved in `7.9.x`, which is currently in Google Review Purgatory (tm)
> > Apologies for the inconvenience!
> 
> Is the APK directly available? I still see 7.8.1 on [signal.org/](https://signal.org/android/apk/)

There are beta versions on apkmirror. 7.9.6beta fixed the issue for me.

**Comment by alex-signal** [comment]
Hi everyone! 7.9.6 is available now in production.

> I was wondering though, without getting into details, do you know the root cause? I didn't update my phone nor the app recently so I'm not quite sure what would cause this.

Basically, we weren't checking whether the currency code was valid when syncing some account info between linked devices. This caused us to try to parse a blank value, which caused the application to crash. How the value became blank is a bit of a mystery, but it won't happen again because we now *require* a parsed currency before hitting any database methods. (And I added a migration to try to "self heal" these errant subscribers as well).

**Comment by zander13auto** [comment]
I now have this crashing problem after moving to my new Pixel 9 pro XL.  App wont stay open for more than a second now, but was working for the first few hours after I restored the data.

**Comment by mtang-signal** [comment]
> I now have this crashing problem after moving to my new Pixel 9 pro XL. App wont stay open for more than a second now, but was working for the first few hours after I restored the data.

Likely the same issue we have been seeing in 7.14 that we're trying to fix now. If the app is crashing on startup, it's probably difficult to get traditional logs but if you are able to [provide any other logs](https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports#advanced-capturing), that would be helpful.

**Comment by birbritto** [comment]
Im having the same problem. 
[signal-log-1724517047898.zip](https://github.com/user-attachments/files/16737369/signal-log-1724517047898.zip)

**Comment by zander13auto** [comment]
Sadly it wont stay open long enough to get logs.  Is there a way to refresh the install without losing my data?  I really blew it my not making a backup before this all started.  It did work on this phone for about half a day when I first moved it over.

**Comment by huowen2020** [comment]
my signal keeps crashing. it crashes once it opens.  here is messages from the log:

User-Agent        : Signal-Android/7.14.2 Android/33
SlowNotifications : false
IgnoringBatteryOpt: false
BkgRestricted     : false
Data Saver        : DISABLED
APNG Animation    : true
App               : Signal 7.14.2 (1446, 144600) (879c794324b0) 
Package           : org.thoughtcrime.securesms (doDiFGKPO1r)

[7.14.2] [73   ] 2024-08-25 11:08:49.216 EDT D StorageSyncHelper: No need for sync. Last sync was 884019 ms ago.
[7.14.2] [76   ] 2024-08-25 11:08:49.217 EDT I PendingRetryReceiptMana: Next closest expiration is in 2079421 ms for timestamp 1724596806432.
[7.14.2] [67   ] 2024-08-25 11:08:49.217 EDT D JobManager: Initialized
[7.14.2] [main ] 2024-08-25 11:08:49.218 EDT I JobManager: onConstraintMet(NetworkConstraintObserv)
[7.14.2] [71   ] 2024-08-25 11:08:49.220 EDT I ApplicationContext: Deleted 0 abandoned attachments.
[7.14.2] [81   ] 2024-08-25 11:08:49.223 EDT I JobRunner: [JOB::bc255818-eb17-4d1b-bbe1-f68543e41e6f][PreKeysSyncJob][3] Running job. (Time Since Submission: 14888835 ms, Lifespan: 2592000000 ms, Run Attempt: 1/Unlimited, Queue: PreKeysSyncJob)
[7.14.2] [75   ] 2024-08-25 11:08:49.224 EDT I ViewOnceMessageManager: No messages to schedule.
[7.14.2] [65   ] 2024-08-25 11:08:49.225 EDT I PersistentAlarmManagerL: [RotateSenderCertificateListener] onReceive(signal.ACTION_SCHEDULE)
[7.14.2] [65   ] 2024-08-25 11:08:49.225 EDT I PersistentAlarmManagerL: [RotateSenderCertificateListener] scheduling alarm for: 1724629869080
[7.14.2] [81   ] 2024-08-25 11:08:49.226 EDT W PreKeysSyncJob: [JOB::bc255818-eb17-4d1b-bbe1-f68543e41e6f][PreKeysSyncJob] Forced rotation was requested. (Time Since Submission: 14888838 ms, Lifespan: 2592000000 ms, Run Attempt: 1/Unlimited, Queue: PreKeysSyncJob)
[7.14.2] [81   ] 2024-08-25 11:08:49.226 EDT W PreKeysSyncJob: [JOB::bc255818-eb17-4d1b-bbe1-f68543e41e6f][PreKeysSyncJob][ACI] Active Signed EC: 1121315, Last Resort Kyber: 1121315 (Time Since Submission: 14888838 ms, Lifespan: 2592000000 ms, Run Attempt: 1/Unlimited, Queue: PreKeysSyncJob)
[7.14.2] [81   ] 2024-08-25 11:08:49.226 EDT W PreKeysSyncJob: [JOB::bc255818-eb17-4d1b-bbe1-f68543e41e6f][PreKeysSyncJob][PNI] Active Signed EC: 3283032, Last Resort Kyber: 3283032 (Time Since Submission: 14888838 ms, Lifespan: 2592000000 ms, Run Attempt: 1/Unlimited, Queue: PreKeysSyncJob)
[7.14.2] [65   ] 2024-08-25 11:08:49.227 EDT I RoutineMessageFetchRece: Alarm scheduled to repeat at interval 10800000
[7.14.2] [65   ] 2024-08-25 11:08:49.227 EDT I PersistentAlarmManagerL: [AnalyzeDatabaseAlarmListener] onReceive(signal.ACTION_SCHEDULE)
[7.14.2] [65   ] 2024-08-25 11:08:49.232 EDT I PersistentAlarmManagerL: [AnalyzeDatabaseAlarmListener] scheduling exact alarm for: 1724655879000 hasManagerPermission: true
[7.14.2] [71   ] 2024-08-25 11:08:49.233 EDT D EmojiFiles: Verifying all name files exist.
[7.14.2] [71   ] 2024-08-25 11:08:49.236 EDT D EmojiFiles: All names exist? true
[7.14.2] [82   ] 2024-08-25 11:08:49.263 EDT I JobRunner: [JOB::94b64f78-8b30-42d6-8734-54ee0a384e9a][RetrieveProfileJob][4] Running job. (Time Since Submission: 856065 ms, Lifespan: Immortal, Run Attempt: 1/3, Queue: null)
[7.14.2] [80   ] 2024-08-25 11:08:49.265 EDT I JobRunner: [JOB::2d062366-e6b5-42b2-85eb-1e3a49314051][GroupV2UpdateSelfProfileKeyJob][2] Running job. (Time Since Submission: 699618 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited, Queue: GroupV2UpdateSelfProfileKeyJob)
[7.14.2] [80   ] 2024-08-25 11:08:49.266 EDT I GroupV2UpdateSelfProfil: Ensuring profile key up to date on group GV2::***be9
[7.14.2] [79   ] 2024-08-25 11:08:49.273 EDT I JobRunner: [JOB::1fbe7d7d-06e1-4b48-b545-e00f7eb90e0b][RequestGroupV2InfoWorkerJob][1] Running job. (Time Since Submission: 485423 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited, Queue: __PUSH_PROCESS_JOB__RecipientId::316)
[7.14.2] [79   ] 2024-08-25 11:08:49.274 EDT I RequestGroupV2InfoWorke: Updating group to latest revision
[7.14.2] [70   ] 2024-08-25 11:08:49.333 EDT D NetworkConnectionListen: ConnectivityManager.NetworkCallback onBlockedStatusChanged()
[7.14.2] [68   ] 2024-08-25 11:08:49.334 EDT D IncomingMessageObserver: [Needs Connection] Network: true, Foreground: false, Time Since Last Interaction: 1 ms (within limit), FCM: true, Stay open requests: [], Registered: true, Proxy: false, Force websocket: false
[7.14.2] [68   ] 2024-08-25 11:08:49.334 EDT I IncomingMessageObserver: Making websocket connection....
[7.14.2] [68   ] 2024-08-25 11:08:49.335 EDT D IncomingMessageObserver: WebSocket State: DISCONNECTED
[7.14.2] [68   ] 2024-08-25 11:08:49.335 EDT I OkHttpWebSocketConnection: [normal:109550475] connect()
[7.14.2] [68   ] 2024-08-25 11:08:49.432 EDT I OkHttpWebSocketConnection: [unidentified:204928163] connect()
[7.14.2] [65   ] 2024-08-25 11:08:49.444 EDT D IncomingMessageObserver: WebSocket State: CONNECTING
[7.14.2] [68   ] 2024-08-25 11:08:49.518 EDT D IncomingMessageObserver: [Needs Connection] Network: true, Foreground: false, Time Since Last Interaction: 321 ms (within limit), FCM: true, Stay open requests: [], Registered: true, Proxy: false, Force websocket: false
[7.14.2] [68   ] 2024-08-25 11:08:49.518 EDT D IncomingMessageObserver: Reading message...
[7.14.2] [81   ] 2024-08-25 11:08:49.593 EDT E libsignal: Unexpected checked exception class org.signal.libsignal.protocol.InvalidKeyException
org.signal.libsignal.protocol.InvalidKeyException: bad KEM key type <0x05>
	at org.signal.libsignal.internal.Native.KyberPreKeyRecord_GetKeyPair(Native Method)
	at org.signal.libsignal.protocol.state.KyberPreKeyRecord.lambda$getKeyPair$3(KyberPreKeyRecord.java:53)
	at org.signal.libsignal.protocol.state.KyberPreKeyRecord.$r8$lambda$zilH1BOxGnLVbEOx41IkVvkRw7E(KyberPreKeyRecord.java:0)
	at org.signal.libsignal.protocol.state.KyberPreKeyRecord$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
	at org.signal.libsignal.internal.FilterExceptions.filterExceptions(FilterExceptions.java:110)
	at org.signal.libsignal.protocol.state.KyberPreKeyRecord.getKeyPair(KyberPreKeyRecord.java:53)
	at org.thoughtcrime.securesms.jobs.PreKeysSyncJob.checkPreKeyConsistency(PreKeysSyncJob.kt:267)
	at org.thoughtcrime.securesms.jobs.PreKeysSyncJob.onRun(PreKeysSyncJob.kt:131)
	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:88)
	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:51)

[7.14.2] [81   ] 2024-08-25 11:08:49.595 EDT E SignalUncaughtException: 
[7.14.2] [81   ] 2024-08-25 11:08:49.595 EDT E SignalUncaughtException: java.lang.AssertionError: org.signal.libsignal.protocol.InvalidKeyException: bad KEM key type <0x05>
[7.14.2] [81   ] 2024-08-25 11:08:49.595 EDT E SignalUncaughtException: 	at org.signal.libsignal.internal.FilterExceptions.reportUnexpectedException(FilterExceptions.java:70)
[7.14.2] [81   ] 2024-08-25 11:08:49.595 EDT E SignalUncaughtException: 	at org.signal.libsignal.internal.FilterExceptions.filterExceptions(FilterExceptions.java:114)
[7.14.2] [81   ] 2024-08-25 11:08:49.595 EDT E SignalUncaughtException: 	at org.signal.libsignal.protocol.state.KyberPreKeyRecord.getKeyPair(KyberPreKeyRecord.java:53)
[7.14.2] [81   ] 2024-08-25 11:08:49.595 EDT E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.PreKeysSyncJob.checkPreKeyConsistency(PreKeysSyncJob.kt:267)
[7.14.2] [81   ] 2024-08-25 11:08:49.595 EDT E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.PreKeysSyncJob.onRun(PreKeysSyncJob.kt:131)
[7.14.2] [81   ] 2024-08-25 11:08:49.595 EDT E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
[7.14.2] [81   ] 2024-08-25 11:08:49.595 EDT E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:88)
[7.14.2] [81   ] 2024-08-25 11:08:49.595 EDT E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:51)
[7.14.2] [81   ] 2024-08-25 11:08:49.595 EDT E SignalUncaughtException: Caused by: org.signal.libsignal.protocol.InvalidKeyException: bad KEM key type <0x05>
[7.14.2] [81   ] 2024-08-25 11:08:49.595 EDT E SignalUncaughtException: 	at org.signal.libsignal.internal.Native.KyberPreKeyRecord_GetKeyPair(Native Method)
[7.14.2] [81   ] 2024-08-25 11:08:49.595 EDT E SignalUncaughtException: 	at org.signal.libsignal.protocol.state.KyberPreKeyRecord.lambda$getKeyPair$3(KyberPreKeyRecord.java:53)
[7.14.2] [81   ] 2024-08-25 11:08:49.595 EDT E SignalUncaughtException: 	at org.signal.libsignal.protocol.state.KyberPreKeyRecord.$r8$lambda$zilH1BOxGnLVbEOx41IkVvkRw7E(KyberPreKeyRecord.java:0)
[7.14.2] [81   ] 2024-08-25 11:08:49.595 EDT E SignalUncaughtException: 	at org.signal.libsignal.protocol.state.KyberPreKeyRecord$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
[7.14.2] [81   ] 2024-08-25 11:08:49.595 EDT E SignalUncaughtException: 	at org.signal.libsignal.internal.FilterExceptions.filterExceptions(FilterExceptions.java:110)
[7.14.2] [81   ] 2024-08-25 11:08:49.595 EDT E SignalUncaughtException: 	... 6 more
[7.14.2] [81   ] 2024-08-25 11:08:49.595 EDT E SignalUncaughtException: 
[7.14.2] [79   ] 2024-08-25 11:08:49.612 EDT I GroupsV2StateProcessor: [GV2::***e9] Paging from server targetRevision: latest
[7.14.2] [79   ] 2024-08-25 11:08:49.615 EDT I GroupsV2AuthorizationSi: Loaded 8 credentials from local storage
[7.14.2] [79   ] 2024-08-25 11:08:49.616 EDT I GroupsV2AuthorizationSi: Loaded 8 credentials from local storage
[7.14.2] [main ] 2024-08-25 11:09:02.618 EDT I libsignal: rust/bridge/jni/src/logging.rs:160: Initializing libsignal version:0.52.5
[7.14.2] [main ] 2024-08-25 11:09:02.618 EDT I ApplicationContext: onCreate()
[7.14.2] [main ] 2024-08-25 11:09:02.619 EDT I ApplicationContext: Installed AesGcmProvider: 1
[7.14.2] [main ] 2024-08-25 11:09:02.623 EDT I ApplicationContext: Installed Conscrypt provider: 2
[7.14.2] [main ] 2024-08-25 11:09:02.626 EDT I KeyValueDatabase: onOpen()
[7.14.2] [main ] 2024-08-25 11:09:02.632 EDT D ApplicationMigrations: Not an update. Skipping.
[7.14.2] [67   ] 2024-08-25 11:09:02.632 EDT D JobManager: Starting initialization: Thread[signal-JobManager,5,main]
[7.14.2] [main ] 2024-08-25 11:09:02.633 EDT I IncomingMessageObserver: Initializing! (25640340)
[7.14.2] [68   ] 2024-08-25 11:09:02.633 EDT I IncomingMessageObserver: Waiting for websocket state change....
[7.14.2] [main ] 2024-08-25 11:09:02.634 EDT W RemoteConfig: Tried to read android.internalUser before initialization. Initializing now.
[7.14.2] [main ] 2024-08-25 11:09:02.634 EDT I RemoteConfig: init() {android.animatedStickerMinMemory=193, android.animatedStickerMinTotalMemory=3072, android.attachments.maxCount=32, android.automaticSessionReset.2=true, android.calling.ad.hoc.3=false, android.calling.fieldTrial.anyAddressPortsKillSwitch=true, android.calling.hardwareAecBlockList=Redmi Note 5,FP2,M1901F7*,ASUS_I006D,motorola one power,FP3,FP4,S22 FLIP,Mi Note 10,SM-S215DL, android.calling.softwareAecBlockList=false, android.calling.telecomAllowList=false, android.calling.telecomModelBlockList=SM-G930F,SM-G950F,SM-N950*,SM-J737V,SC-02*,SM-A105*,SM-A530*, android.calling.useActiveCallManager.6=false, android.calling.useHardwareAecIfOlderThanApi29=false, android.cameraXMixedModelBlockList=Pixel 3,Pixel 4,Pixel 4 XL,SM-G930T,SM-G930V,YAL-L21,YAL-AL00,YAL-TL00,VOG-L29,VOG-L09,VOG-AL00,VOG-TL00,VOG-L04,VOG-AL10,HW-02L,EVR-L29,EVR-AL00,EVR-TL00,CPH2583,CPH2573,CPH2581,SM-A336E,MAR-LX1A,FP4, android.cameraXModelBlockList=ALE-L21,GT-N7100,GT-N8000,COL-L29,C66,C66_EEA,

**Comment by huowen2020** [comment]
Android           : 13, API 33 (T870XXS7DXE3, TP1A.220624.014.T870XXS7DXE3)
ABIs              : arm64-v8a, armeabi-v7a, armeabi
Memory            : 49M (47.76% free, 512M max)
Memclass          : 512
MemInfo           : availMem: 3299 mb, totalMem: 7643 mb, threshold: 216 mb, lowMemory: false

**Comment by nemobis** [comment]
I also have the same issue. On Android 12, after migrating from a previous phone, things seemed to work fine for a while except for the fact that every hour the "Personal notes" chat would have a bogus "chat updated" notice. Then the app started crashing upon startup every time. The Signal Desktop client meanwhile keeps working fine.

> Turn it on airplane mode and it may allow you to get logs

That worked. Excerpt from the log:

```
08-25 23:17:58.771  2202  2393 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-1
08-25 23:17:58.771  2202  2393 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 2202
08-25 23:17:58.771  2202  2393 E AndroidRuntime: java.lang.AssertionError: org.signal.libsignal.protocol.InvalidKeyException: bad KEM key type <0x05>
08-25 23:17:58.771  2202  2393 E AndroidRuntime: 	at org.signal.libsignal.internal.FilterExceptions.reportUnexpectedException(FilterExceptions.java:70)
08-25 23:17:58.771  2202  2393 E AndroidRuntime: 	at org.signal.libsignal.internal.FilterExceptions.filterExceptions(FilterExceptions.java:114)
08-25 23:17:58.771  2202  2393 E AndroidRuntime: 	at org.signal.libsignal.protocol.state.KyberPreKeyRecord.getKeyPair(KyberPreKeyRecord.java:53)
08-25 23:17:58.771  2202  2393 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PreKeysSyncJob.checkPreKeyConsistency(PreKeysSyncJob.kt:267)
08-25 23:17:58.771  2202  2393 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PreKeysSyncJob.onRun(PreKeysSyncJob.kt:131)
08-25 23:17:58.771  2202  2393 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
08-25 23:17:58.771  2202  2393 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:88)
08-25 23:17:58.771  2202  2393 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:51)
08-25 23:17:58.771  2202  2393 E AndroidRuntime: Caused by: org.signal.libsignal.protocol.InvalidKeyException: bad KEM key type <0x05>
08-25 23:17:58.771  2202  2393 E AndroidRuntime: 	at org.signal.libsignal.internal.Native.KyberPreKeyRecord_GetKeyPair(Native Method)
08-25 23:17:58.771  2202  2393 E AndroidRuntime: 	at org.signal.libsignal.protocol.state.KyberPreKeyRecord.lambda$getKeyPair$3(KyberPreKeyRecord.java:53)
08-25 23:17:58.771  2202  2393 E AndroidRuntime: 	at org.signal.libsignal.protocol.state.KyberPreKeyRecord.$r8$lambda$zilH1BOxGnLVbEOx41IkVvkRw7E(KyberPreKeyRecord.java:0)
08-25 23:17:58.771  2202  2393 E AndroidRuntime: 	at org.signal.libsignal.protocol.state.KyberPreKeyRecord$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
08-25 23:17:58.771  2202  2393 E AndroidRuntime: 	at org.signal.libsignal.internal.FilterExceptions.filterExceptions(FilterExceptions.java:110)
08-25 23:17:58.771  2202  2393 E AndroidRuntime: 	... 6 more
```

It's the same exception @birbritto  has above.

Maybe the PIN update mentioned above works because it updates this key? Unfortunately I don't see how to do that while offline.

**Comment by birbritto** [comment]
My issue is still unresolved and there's no update to install that I havent yet installed

**Comment by D0MF** [comment]
[signal-log-1724709596454.zip](https://github.com/user-attachments/files/16754260/signal-log-1724709596454.zip)
I've had the same problem twice today. I fixed it this morning by taking a backup (in airplane mode), then removing the app, reinstalling, and importing the backup. It worked for a good 6 hours and then has started crashing again if I turn airplane mode off. Logs attached.

**Comment by birbritto** [comment]
I tried that several times and it just happens again in a few mins or hours

**Comment by birbritto** [comment]
Still crashing within seconds, no update

**Comment by D0MF** [comment]
> Still crashing within seconds, no update

Join the beta from the play store, it'll update to a version that does not crash

**Comment by birbritto** [comment]
Im on the play store and I dont see any beta? can you help me understand how to get that?

**Comment by D0MF** [comment]
> Im on the play store and I dont see any beta? can you help me understand how to get that?

I think this should take you there?
https://play.google.com/apps/testing/org.thoughtcrime.securesms
When I click it it already says I'm in beta. It's in the fine print of the app description in the play store.

**Comment by birbritto** [comment]
Thank you SO MUCH that fixed it for now! What a nightmare.

**Comment by zander13auto** [comment]
this beta fixed my issue, thanks

**Comment by jormasoul** [comment]
So this exact issue is happening again. I'm currently on version 7.36.2, upgraded yesterday because the issue started occurring on an earlier version. Turning off data lets the app run without constantly shutting down. Managed to get the log:

[signal-log-1741536693959.zip](https://github.com/user-attachments/files/19150722/signal-log-1741536693959.zip)

**Comment by ralphie02** [comment]
> So this exact issue is happening again. I'm currently on version 7.36.2, upgraded yesterday because the issue started occurring on an earlier version. Turning off data lets the app run without constantly shutting down. Managed to get the log:
> 
> [signal-log-1741536693959.zip](https://github.com/user-attachments/files/19150722/signal-log-1741536693959.zip)

Have you tried my solution? I'm curious if this actually works or just a weird coincidence on my part and something else entirely fixed the issue.

**Comment by jormasoul** [comment]
> > So this exact issue is happening again. I'm currently on version 7.36.2, upgraded yesterday because the issue started occurring on an earlier version. Turning off data lets the app run without constantly shutting down. Managed to get the log:
> > [signal-log-1741536693959.zip](https://github.com/user-attachments/files/19150722/signal-log-1741536693959.zip)
> 
> Have you tried my solution? I'm curious if this actually works or just a weird coincidence on my part and something else entirely fixed the issue.

Tried it. I managed to get to the Change PIN screen while offline and committed the change by quickly putting data back on just before clicking Confirm. I think the PIN did change. Didn't work tho, kept crashing.

**Comment by AnthonyCamper** [comment]
Same exact issue. Putting in airplane mode allowed me to grab the debug.
`============ LOGCAT =============
--------- beginning of crash
04-23 23:11:07.097  3452  4265 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-1
04-23 23:11:07.097  3452  4265 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 3452
04-23 23:11:07.097  3452  4265 E AndroidRuntime: org.thoughtcrime.securesms.jobs.StorageSyncJob$MissingChatFolderModelError: Missing local chat folder model!
04-23 23:11:07.097  3452  4265 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.buildLocalStorageRecords(StorageSyncJob.kt:511)
04-23 23:11:07.097  3452  4265 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.kt:346)
04-23 23:11:07.097  3452  4265 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.kt:182)
04-23 23:11:07.097  3452  4265 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
04-23 23:11:07.097  3452  4265 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:88)
04-23 23:11:07.097  3452  4265 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:51)
04-23 23:11:14.613  7129  7236 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-2
04-23 23:11:14.613  7129  7236 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 7129
04-23 23:11:14.613  7129  7236 E AndroidRuntime: org.thoughtcrime.securesms.jobs.StorageSyncJob$MissingChatFolderModelError: Missing local chat folder model!
04-23 23:11:14.613  7129  7236 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.buildLocalStorageRecords(StorageSyncJob.kt:511)
04-23 23:11:14.613  7129  7236 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.kt:346)
04-23 23:11:14.613  7129  7236 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.kt:182)
04-23 23:11:14.613  7129  7236 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
04-23 23:11:14.613  7129  7236 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:88)
04-23 23:11:14.613  7129  7236 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:51)
04-23 23:11:25.304  9072  9155 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-1
04-23 23:11:25.304  9072  9155 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 9072
04-23 23:11:25.304  9072  9155 E AndroidRuntime: org.thoughtcrime.securesms.jobs.StorageSyncJob$MissingChatFolderModelError: Missing local chat folder model!
04-23 23:11:25.304  9072  9155 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.buildLocalStorageRecords(StorageSyncJob.kt:511)
04-23 23:11:25.304  9072  9155 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.kt:346)
04-23 23:11:25.304  9072  9155 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.kt:182)
04-23 23:11:25.304  9072  9155 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
04-23 23:11:25.304  9072  9155 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:88)
04-23 23:11:25.304  9072  9155 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:51)
04-23 23:12:28.780  9599  9663 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-3
04-23 23:12:28.780  9599  9663 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 9599
04-23 23:12:28.780  9599  9663 E AndroidRuntime: org.thoughtcrime.securesms.jobs.StorageSyncJob$MissingChatFolderModelError: Missing local chat folder model!
04-23 23:12:28.780  9599  9663 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.buildLocalStorageRecords(StorageSyncJob.kt:511)
04-23 23:12:28.780  9599  9663 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.kt:346)
04-23 23:12:28.780  9599  9663 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.kt:182)
04-23 23:12:28.780  9599  9663 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
04-23 23:12:28.780  9599  9663 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:88)
04-23 23:12:28.780  9599  9663 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:51)
04-23 23:12:30.049  9727  9784 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-1
04-23 23:12:30.049  9727  9784 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 9727
04-23 23:12:30.049  9727  9784 E AndroidRuntime: org.thoughtcrime.securesms.jobs.StorageSyncJob$MissingChatFolderModelError: Missing local chat folder model!
04-23 23:12:30.049  9727  9784 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.buildLocalStorageRecords(StorageSyncJob.kt:511)
04-23 23:12:30.049  9727  9784 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.kt:346)
04-23 23:12:30.049  9727  9784 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.kt:182)
04-23 23:12:30.049  9727  9784 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
04-23 23:12:30.049  9727  9784 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:88)
04-23 23:12:30.049  9727  9784 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:51)
04-23 23:12:32.640  9860  9919 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-3
04-23 23:12:32.640  9860  9919 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 9860
04-23 23:12:32.640  9860  9919 E AndroidRuntime: org.thoughtcrime.securesms.jobs.StorageSyncJob$MissingChatFolderModelError: Missing local chat folder model!
04-23 23:12:32.640  9860  9919 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.buildLocalStorageRecords(StorageSyncJob.kt:511)
04-23 23:12:32.640  9860  9919 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.kt:346)
04-23 23:12:32.640  9860  9919 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.kt:182)
04-23 23:12:32.640  9860  9919 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
04-23 23:12:32.640  9860  9919 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:88)
04-23 23:12:32.640  9860  9919 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:51)
04-23 23:13:09.867 10012 10082 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-1
04-23 23:13:09.867 10012 10082 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 10012
04-23 23:13:09.867 10012 10082 E AndroidRuntime: org.thoughtcrime.securesms.jobs.StorageSyncJob$MissingChatFolderModelError: Missing local chat folder model!
04-23 23:13:09.867 10012 10082 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.buildLocalStorageRecords(StorageSyncJob.kt:511)
04-23 23:13:09.867 10012 10082 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.kt:346)
04-23 23:13:09.867 10012 10082 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.kt:182)
04-23 23:13:09.867 10012 10082 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
04-23 23:13:09.867 10012 10082 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:88)
04-23 23:13:09.867 10012 10082 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:51)
04-23 23:17:08.701 10469 10522 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-1
04-23 23:17:08.701 10469 10522 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 10469
04-23 23:17:08.701 10469 10522 E AndroidRuntime: org.thoughtcrime.securesms.jobs.StorageSyncJob$MissingChatFolderModelError: Missing local chat folder model!
04-23 23:17:08.701 10469 10522 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.buildLocalStorageRecords(StorageSyncJob.kt:511)
04-23 23:17:08.701 10469 10522 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.kt:346)
04-23 23:17:08.701 10469 10522 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.kt:182)
04-23 23:17:08.701 10469 10522 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
04-23 23:17:08.701 10469 10522 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:88)
04-23 23:17:08.701 10469 10522 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:51)
04-23 23:17:09.587 11269 11334 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-1
04-23 23:17:09.587 11269 11334 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 11269
04-23 23:17:09.587 11269 11334 E AndroidRuntime: org.thoughtcrime.securesms.jobs.StorageSyncJob$MissingChatFolderModelError: Missing local chat folder model!
04-23 23:17:09.587 11269 11334 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.buildLocalStorageRecords(StorageSyncJob.kt:511)
04-23 23:17:09.587 11269 11334 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.kt:346)
04-23 23:17:09.587 11269 11334 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.kt:182)
04-23 23:17:09.587 11269 11334 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
04-23 23:17:09.587 11269 11334 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:88)
04-23 23:17:09.587 11269 11334 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:51)
04-23 23:17:13.936 11425 11482 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-2
04-23 23:17:13.936 11425 11482 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 11425
04-23 23:17:13.936 11425 11482 E AndroidRuntime: org.thoughtcrime.securesms.jobs.StorageSyncJob$MissingChatFolderModelError: Missing local chat folder model!
04-23 23:17:13.936 11425 11482 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.buildLocalStorageRecords(StorageSyncJob.kt:511)
04-23 23:17:13.936 11425 11482 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.kt:346)
04-23 23:17:13.936 11425 11482 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.kt:182)
04-23 23:17:13.936 11425 11482 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
04-23 23:17:13.936 11425 11482 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:88)
04-23 23:17:13.936 11425 11482 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:51)
--------- beginning of main`

**Comment by pash99** [comment]
> Managed to restore usage of the app by creating a new pin
> 
> When restoring my backup, at some point it asks for the PIN (the old pin used on the app). I tried to skip it but it insisted on a PIN and the verbiage changed to "create PIN". I did and the app no longer crashes! I'm not sure how android apps work but I think the old PIN is the issue. It somehow got corrupted and creating a new one purges the issue, or something like that 🤷

Same problem here. Updating Signal to the latest version 7.41.3 didn't help, neither did clearing the cache. I tried to change PIN-code while my phone was in Airplane mode, then went back online and the problem went away, at least for now. PIN-code change fails in Airplane mode, of course, but that did it. I didn't have to create backup and restore.

**Comment by mmhhh72043778-sys** [comment]
Un
