### ISSUE TITLE
Sending messages impossible v7.19.0

### ISSUE THREAD

**Issue by drubinger** [signalapp/Signal-Android#13724]
### Guidelines

- [X] I have searched searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

### Bug description

Today I updated Singla Android to 7.19.0. 

2 Bugs:

1) Sending messages doesn't work anymore (incoming messages works properly, small sending circle remaining)
2) Creating a backup archive isn't possible anymore (choose folder works, key is beeing displayed, but then... no backup possible, even if you set a backup time or try to start it manually)

Clearing cache doesn't help. Uninstall not possible due to loss of messages.

### Device

OnepPlus 9 Pro

### Android version

Android 14

### Signal version

7.19.0

**Comment by greyson-signal** [comment]
Hi there, unfortunately there's a query running in a migration that is running oddly slow on some devices. We have a fix coming in 7.19.1 :+1:

**Comment by robsliwi** [comment]
Seems like 9.17.1 didn't help at my end. It is still stuck at pending.

Is there any additional trick to get it going again?
Or: is there any way to assist with logs to debug the issue a little bit better?

Google Pixel 6 Pro running stock Android 14 with September patch level here.

**Comment by icynstant** [comment]
i still have problems with 7.19.2

**Comment by greyson-signal** [comment]
@icynstant Can you please share a [debuglog](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug)?

**Comment by icynstant** [comment]
> @icynstant Can you please share a [debuglog](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug)? 

you can check logs from other people in #13726

**Comment by greyson-signal** [comment]
@icynstant That issue had a couple different problems bundled together. I'm fairly confident that the OP's issue has been resolved, and you likely are experiencing something else.

**Comment by icynstant** [comment]
> @icynstant That issue had a couple different problems bundled together. I'm fairly confident that the OP's issue has been resolved, and you likely are experiencing something else.

i had an issue with 2 my friends on both sides when messages indicated as sent (one unpainted circle), but actually they was lost. and on the next day i can send another messages and my friend will get and read those, but older ones are still only "sent" (with 1 circle). it was in v7.19.2.

android - https://debuglogs.org/android/7.19.2/d89eba5de757dd8a0c491f685e789b270cd6970dcd07af77643e580c5cb837ed

desktop - https://debuglogs.org/desktop/7.29.0/06f3c37833d97ac8530e3270dde3ea048e582d8fb075ffa5b76d5f941dcb84b6.gz

**Comment by nerozero** [comment]
I dont get it, why that issues are closed ? The issue is still present, nothing changed, a friend of mine cannot send messages. 
Here is the log from the person who is receiving my messages but unable to send anything.
[signal-log-1728978674081.zip](https://github.com/user-attachments/files/17405952/signal-log-1728978674081.zip)

**Comment by greyson-signal** [comment]
@nerozero Two people may experience similar symptoms but have different root causes. We try to track bugs by root cause, not symptom. There was one very obvious root cause that a lot of people experienced because of a change in a specific release, and that's what these bugs where tracking.

FWIW your friend has many logs implying that they're sending messages successfully, at least in the last couple days that the log covers. Outside of that, they could be experiencing issues with Russian censorship.

**Comment by greyson-signal** [comment]
@icynstant I looks like there was a period of timer where you both had bad sender key certificates. I wonder if that correlates to some censorship issues that were happening. Looking at the logs though, it seems like that's self-repaired and you've been able to send messages since that were successfully decrypted.

**Comment by nerozero** [comment]
@greyson-signal first of all thanks for your contribution.
Yes indeed a friend of mine now is in russia, we installed VPN for that purpose. After that signal works normally for a long time. Last message I received from a friend of mine was send @ 2024-10-14, no messages has received after that ...

**Comment by icynstant** [comment]
> @icynstant I looks like there was a period of time where you both had bad sender key certificates. I wonder if that correlates to some censorship issues that were happening. Looking at the logs though, it seems like that's self-repaired and you've been able to send messages since that were successfully decrypted.

thanks, im from russian too and im using ByeDPIAndroid by dovecoteescapee on github, otherwise signal doesn't work. sorry i don't really understant a lot, will signal work properly for me now? because i switched to other messanger that works good in russia, but i wanna go back and use signal as main messanger. when they will block vpns in russia i think a lot of people will start use byedpi, please consider fully support it. you can learn more about it in GoodbyeDPI on github, thanks a lot.

**Comment by nerozero** [comment]
@greyson-signal just received a message from my friend who had sending issues. The messages comes with random delays, 10 min up to hours ... So I guess you where right, its not a signal issue but a censorship firewalls in russia.... 

@icynstant I bought a proton vpn service for a friend. But I guess this also doesn't seems to be a solution. ByeDPIAndroid, GoodbyeDPI was used previously bot doesn't seems to work anymore .

the world is getting darker and darker every day...

**Comment by nerozero** [comment]
@icynstant thank you so much. Now I have to explain all of that to a friend who is not that good in computers ...

**Comment by icynstant** [comment]
@greyson-signal Recently all of messages stuck on sent to server.

https://debuglogs.org/android/7.19.2/f8d0b3451bc79a25cf8430bca9ba5a38ee40cea6ec875ff80f30bfe03446c973

**Comment by Hasshu** [comment]
@icynstant Is that on GrapheneOS, by any chance?

**Comment by icynstant** [comment]
@Hasshu no, realme ui
