### ISSUE TITLE
Notifications missed when screen locked (Graphene OS, without Gapps)

### ISSUE THREAD

**Issue by idealemu** [signalapp/Signal-Android#13952]
### Guidelines

- [x] I have searched searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

### Bug description

Hi,

I have noticed that notifications get regularly missed when the screen is locked.
I am running Graphene OS and do not have GApps, signal works using the permanent notification. 
Battery optimisation is _disabled_.
I do not have notifications for most messages because of this. No sound, nor vibration (when those are enabled) and not notification banner on locked screen (when those are enabled), most notifications (> 80%) only appear on the top bar once the phone is unlocked. The signal lock feature is not enabled.

### Expected behaviour:
Notifications always show new messages even when those are received with a locked screen.

### Attempts at fixing:
Have tried different settings regarding notifications and privacy, but the issue seems to persist.

### Device

Pixel 6A

### Android version

Graphene OS Android version 15

### Signal version

7.30.2

### Link to debug log

https://debuglogs.org/android/7.30.2/7aef60aa5bb92784c410ac4fd36164a4c4517bc781cdb3386d17df77b2ad9167

**Comment by kevenwyld** [comment]
I'm having the same problem.  Also on GrapheneOS (2025020200) and Signal version 7.32.2 installed via the APK

**Comment by kevenwyld** [comment]
I'm having what might be a related issue but only with signal calls so far, also on GrapheneOS.  Do calls require you to unlock the phone to answer them?  Until a few days ago they were full screen notifications like any other call.

**Comment by greyson-signal** [comment]
Fixed in 7.33.0 (in beta)

**Comment by relishdumpling** [comment]
This Issue is still appearing for me. Calls, Chats, ... Also have similar settings and environment (w/o gapps) as @idealemu

**Comment by greyson-signal** [comment]
@relishdumpling Can you please post a link to a [debuglog](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports)?

**Comment by relishdumpling** [comment]
@greyson-signal https://debuglogs.org/android/8.20.5/11035eafa7d0c43c0da8db4a4df4df499c1321ff1d662a76d9745b370fa75325
