### ISSUE TITLE
Lockscreen Call Notifications not showing up [OneUI 7]

### ISSUE THREAD

**Issue by lysutchi** [signalapp/Signal-Android#13963]
### Guidelines

- [x] I have searched searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

### Bug description

Hello,

I just switched to the new Galaxy S25 Ultra with Android 15, OneUI 7 skin and noticed that whenever I get calls, the screen turns on with no indication (notification) then quickly turns off and the ringtone gets muted. I tried disabling battery optimization, re-install the app... but the issue is still persistent.

P.S., the issue so far is only with Signal, I tried other apps and they are working fine.

### Device

Samsung Galaxy S25 Ultra

### Android version

Android 15, OneUI 7

### Signal version

7.31.1

### Link to debug log

https://debuglogs.org/android/7.31.1/963580751f9e9e93dadba9a4840a7aaefcc01a83bb04189cb21bef824cbb47a6

**Comment by kevenwyld** [comment]
I'm having a similar problem on GrapheneOS (2025020200) running on pixel 7 and Signal version 7.32.2 installed via the APK.  Calls no longer show a full screen notification, instead it's a regular notification and I have to unlock the phone to answer.

**Comment by lysutchi** [comment]
> I'm having a similar problem on GrapheneOS (2025020200) running on pixel 7 and Signal version 7.32.2 installed via the APK. Calls no longer show a full screen notification, instead it's a regular notification and I have to unlock the phone to answer.

I noticed that if I don't unlock my phone, the call gets muted within 5 seconds. To answer I have to unlock my phone, open the notification menu, and select Signal then click answer 😵

**Comment by Brane1003** [comment]
> I'm having a similar problem on GrapheneOS (2025020200) running on pixel 7 and Signal version 7.32.2 installed via the APK. Calls no longer show a full screen notification, instead it's a regular notification and I have to unlock the phone to answer.

Hy, i have the same problem on my Motorola G51 5G with stock Android 12 and Signal version 7.32.2 installed via Fdroid.

**Comment by aadnan181** [comment]
Same issue on my Pixel 7 running on Android 15.

**Comment by greyson-signal** [comment]
This should be fixed in 7.33.0, currently in beta. I'm also likely going to put this in a production hotfix via 7.32.3.

**Comment by youer-mam** [comment]
> This should be fixed in 7.33.0, currently in beta. I'm also likely going to put this in a production hotfix via 7.32.3.

Was this fix ever implemented?  I'm still experiencing this issue as of 7.38.1 with a Samsung Galaxy S7 SM-G930U on Android 8

The last working version was 7.30.2

**Comment by mtang-signal** [comment]
> Was this fix ever implemented? I'm still experiencing this issue as of 7.38.1 with a Samsung Galaxy S7 SM-G930U on Android 8
> 
> The last working version was 7.30.2

Yep, it should be fixed. If you're experiencing it again, could you send a [debug log](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug)?

**Comment by youer-mam** [comment]
I'll try to submit a log later today.

Specifically my issue is more like kevenwyld's in the first reply. The screen wakes up and I get an "Incoming Signal voice call"
notification, but not the fullscreen Decline/Answer UI.  I have to unlock my phone to answer the call.

I've been testing older releases and narrowed it down to 7.30.2 working and 7.31.1 not working.

**Comment by youer-mam** [comment]
https://github.com/signalapp/Signal-Android/commit/5769287c77b7175e10ce40cfeadf060176c6180e is the only 7.30.2=>7.31.0 change that looked relevant.

So I bit the bullet and compiled it myself.  Checked out v7.31.0, reverted commit 5769287 and it's working again.  Unfortunately WebRtcCallActivity.java has since been removed so it's a bit more complicated than that.

Also is there a way to re-register without getting the SMS?  I've been reinstalling so much that I'm getting super-annoying captchas now.  I noticed it gets bypassed when restoring a backup (just asks for you pin) but my only backup was made with 7.36.2 and I can't restore that with the versions I'm testing.

**Comment by youer-mam** [comment]
I fixed it!

I found the lines in WebRtcCallActivity.kt that correspond to the now-defunct WebRtcCallActivity.java, removed the two instances of` || state.callState.isIncomingOrHandledElsewhere` that were added in the "faulty" commit, and it's working again as of v7.38.3.

I have no idea if this breaks anything or is a proper "fix," but it does go back to the old behavior, which was working for me.

**Comment by alex-signal** [comment]
Is this occuring for you for all calls? Just group calls?

The code was added to *fix* the fullscreen incoming call view not appearing (as it'd end up triggering the finish() call) so I'd like to understand more about your reproduction steps before I start modifying (and possibly breaking) things.

**Comment by youer-mam** [comment]
I haven't tested group calls, just regular single person-to-person, both video and voice.

Literally the only change I made to the code was removing the isIncomingOrHandledElsewhere test in onPause() and it started working again.

I tried to make every test as consistent as possible - uninstall, install test version, restore backup, make a test call while awake to fully set up permissions, put phone to sleep, make test calls from another phone to mine.  Also did the same process without restoring a backup for a while until I started getting "You've made too many attempts to register this number." 

Every release version I've tested past v7.30.2 (and my own "clean" builds without the edit just to make sure there was no funny business with the build process itself) has consistently not shown the call answer UI while the builds with that edit did.

One interesting thing I noticed with the broken versions is that if I revoke the mic permission, the "Allow access to your microphone" popup will consistently force the call answer UI to display.  I can repeatedly say "Not now", let the phone go back to sleep, and every time "Allow access" comes up and the UI is displayed under it.  But after finally allowing access subsequent calls go back to the broken behavior.

Oh and I just tested an even more ancient 2013 1st gen Moto G (it's a miracle Signal works at all on 5.1) running v7.37.3 (the current google play version) and I got similar symptoms.  Occasionally I'd see lock screen for a second, call UI for a second, then back to lock screen.  But usually it was just the lock screen with no call UI, like my S7.

Then I installed a fixed build of v7.37.3 and lo and behold it fixes that phone too.  Maybe it's a pre API 27 thing?  I'm not an Android dev but I did see a lot of tests for < 27 API in Signal's code.

**Comment by youer-mam** [comment]
Just a small update: I was able to get my hands on two more phones, one Android 10 and one 12.  Both work fine with v7.37.3 as released. They aren't my phones so I can't really install my builds on them to test whether they break things, but it does seem to narrow it down to earlier than 10, which is API 29.

Perhaps keep the current fix but simply bypass the isIncomingOrHandledElsewhere check if Build.VERSION.SDK_INT < 27?  That should at least guarantee that devices with Android 8.1 and later don't get re-broken.

**Comment by alex-signal** [comment]
@youer-mam Thanks for the debugging! I believe 27 is around the time some of the way you manage call notifications / full screen intents changes. Sounds like your proposed fix should be ok. I'll test it out today.

**Comment by youer-mam** [comment]
Thanks! The owner of the Android 10 phone allowed me to install my fixed build so I can now confirm that same build is working with both Android 8 and 10.

**Comment by alex-signal** [comment]
Perfect! This fix i believe is in 7.39 and should go out next week.
