### ISSUE TITLE
Signal Not Starting

### ISSUE THREAD

**Issue by diligentlystereotypedinvestment** [signalapp/Signal-Android#14043]
### Guidelines

- [x] I have searched searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

### Bug description

Hi, whenever I try opening the app, it just immediately crashes. I am using Graphene OS android 15, Signal version 7.36.2.

Attached is the error log I am getting:

Let me know if there's any other 

[Signal log be7fca9413c7.txt](https://github.com/user-attachments/files/19218983/Signal.log.be7fca9413c7.txt)

Let me know if there is any more info I can give to help.

### Device

Pixel 6

### Android version

Android 15

### Signal version

7.36.2

**Comment by Rockee79** [comment]
I have the same Problem since Yesterday. Signal Version  7.38.1 on Xperia 1 V.
I have cleaned up the cache folder and did a Smartphone restart but this does Not solve the Problem.

**Comment by grieben** [comment]
I am also a Graphene useraffected by this. See #13814 where I have attached a [log](https://github.com/user-attachments/files/19255880/SignalLog.txt). I will copy/paste the comment here:

> I am also suddenly experiencing crashes on launch. I've tried turning system date/time back 2 weeks but still experience crashes and cannot create a backup. I have tried launching the app in Airplane mode, but it still crashes. I have also cleared the cache which was suggested in another GH Issue. I have attached a log of the crash. This is on a Pixel 7 Pro running Graphene OS release 2025020500.

I am hoping to find a fix so I don't have to uninstall and do a fresh install (losing all my conversation history!). If there is more info I could provide, I am happy to find it.

**Comment by Rockee79** [comment]
No changes since the Update 7.38.2.
Are there only 3 persons with this problem?
My last Backup is from the Beginning of March and i will lose a lot of conversations if i want to do a reinstall.
At the moment the only way is to write with the desktop app.
@grieben @diligentlystereotypedinvestment do you found a fix or a way to solve the problem?

------------------------
Xperia 1 V
Android 15

**Comment by grieben** [comment]
For those on Graphene, I have created an issue on the Graphene OS Issue Tracker repo: https://github.com/GrapheneOS/os-issue-tracker/issues/5099

**Comment by alex-signal** [comment]
Hi! Could you please try launching the app with Airplane mode enabled on your device?

**Comment by Rockee79** [comment]
# @alex-signal 
Hi, i tried it too but no effect on my phone.
Yesterday I was lucky enough to open the app once; I then tried to start a new current backup. Unfortunately, the backup did not start at the set time. However, I did manage to create an error report.
This is stored here; maybe that will help?

<https://debuglogs.org/android/7.38.3/0f5d9a7c52a7cde21ce4fa7106ce6893a29c876419798e8f68034476087f7e8f>

Thank you very much for your help; I really hope that you can solve the problem? Best regards from Germany
---------------------------------------------------------------------
Xperia 1 V
Android 15
Signal Version: 7.36.3

**Comment by alex-signal** [comment]
Hi guys! This appears to be an issue with one of our migrations. Thanks for the debug logs, we are looking into it!

**Comment by Rockee79** [comment]
Hi Alex,
i have checked the new Version 7.38.4 but the same problem on my site.

I have noticed that I can always open Signal briefly when I have a poor mobile signal or no signal at all. Strangely enough, it is not identical to the phone's flight mode. Nothing changes for me in flight mode and I can't open the app either.
When I was able to open the app, some pending messages arrive, but I can't send any messages.
Unfortunately, I still haven't been able to create a new, up-to-date backup. The backup function still doesn't seem to be working again for me.

I have now been able to open the app once again and I have another log file from version 7.38.4 for you here.

[https://debuglogs.org/android/7.38.4/bed440c9970a11e888a864f1f4d9d557cf1947e573bf8cd6cb1ac45583706f90](url)

I hope it helps you.

Best regards.
Manuel

**Comment by alex-signal** [comment]
Hi! I believe the fix went out in 7.38.5 which I just pushed into the review queue this morning. Sorry for the delay!

**Comment by grieben** [comment]
Hi @alex-signal. Just updated to 7.38.6 and am still crashing on startup. Does that release include the fix? I can email a log to you if that would help.

**Comment by Rockee79** [comment]
Hi Alex,
today there was the update to 7.38.5 but there are no changes for me. 
The v7.38.**6** was not shown in the google playstore for me, so until now i have no chance to test this out how @grieben tested this.

After many attempts to open the app, I managed to keep it open once again; here is the new diagnostic log v 7.38.5
[https://debuglogs.org/android/7.38.5/5819db64a142da5bfb2132317c24c472833f7321131e3076d519e30a2b385f90](url)

Additional infos
- The backup function is still not working for me.
- When the app was open, I received a few messages but couldn't write; sending messages was not possible and pictures/sticker from others cannot be loaded.

Is there a better place to download the new Signal Beta "apk" files, to get new versions faster than over the google play store app?

Xperia 1 V
Android 15
Signal Version: 7.38.5

**Comment by grieben** [comment]
@Rockee79 you can grab an APK from the releases page here: https://github.com/signalapp/Signal-Android/releases
You may have to adjust your phone's settings to permit APKs from outside the Play Store.

**Comment by Rockee79** [comment]
> @Rockee79 you can grab an APK from the releases page here: https://github.com/signalapp/Signal-Android/releases
> You may have to adjust your phone's settings to permit APKs from outside the Play Store.

Perfect! 👍 Thanks a lot.

**Comment by Rockee79** [comment]
> Hi Alex,
> today there was the update to 7.38.5 but there are no changes for me. 
> The v7.38.**6** was not shown in the google playstore for me, so until now i have no chance to test this out how @grieben tested this.
> 
> After many attempts to open the app, I managed to keep it open once again; here is the new diagnostic log v 7.38.5
> [https://debuglogs.org/android/7.38.5/5819db64a142da5bfb2132317c24c472833f7321131e3076d519e30a2b385f90](url)
> 
> Additional infos
> - The backup function is still not working for me.
> - When the app was open, I received a few messages but couldn't write; sending messages was not possible and pictures/sticker from others cannot be loaded.
> 
> Is there a better place to download the new Signal Beta "apk" files, to get new versions faster than over the google play store app?
> 
> Xperia 1 V
> Android 15
> Signal Version: 7.38.5

No changes with 7.38.6 on my Site....

**Comment by hagbard13** [comment]
Also no changes from my side, tested with 7.38.5 and 7.38.6.

**Comment by hagbard13** [comment]
Also no changes from my side, tested with 7.38.5 and 7.38.7. 

Now it is working again, 7.38.7.
Thank you very much!

**Comment by Rockee79** [comment]
Yes! It works again on my site V 7.38.7
The Backupfunction is working too again.
Thank you very much!

One short question ... is there a way to verify backup files to ensure that the backup works correctly in an emergency case? 

Thanks and best regards.

**Comment by fazlefahimrohan** [comment]
Sounds great.

**Comment by grieben** [comment]
I just updated to 7.38.7 and am still experiencing the corrupt db/cipher error crashing on start up.

**Comment by cody-signal** [comment]
@grieben I looked at the log from the other thread, thanks for pointing me to it. Unfortunately, there's not much we can do for you. Your DB is corrupted where other folks in this thread were experiencing a different kind of crash on startup that was fixable. SQLCipher is saying your db is fully corrupt and no longer recognizable as a databsae :(

We are sorry this happened, it really sucks, but not much we can do for you at this point.

**Comment by grieben** [comment]
Sad news but I do appreciate the digging you did. Is there any way I can extract and manually attempt to fix the DB? Or should I go ahead and full reinstall (and start a routine backup practice!)?

**Comment by fazlefahimrohan** [comment]
yeah appritiate

**Comment by TheRealPingWin** [comment]
Same problem on pixel8a graphineOS

[Error in Signal 5206e23efeec.txt](https://github.com/user-attachments/files/20298378/Error.in.Signal.5206e23efeec.txt)

**Comment by elkajetano** [comment]
[debug.txt](https://github.com/user-attachments/files/20302186/debug.txt)

**Comment by mtang-signal** [comment]
> same here, Pixel 8 Android 15, Signal 7.41.3 it started 3 hours ago, can't see the start screen (list of chats)

Thank you for the logs. It'll be fixed in 7.41.4 which should hopefully be available on the play store in the next 24 hours or so.

**Comment by elkajetano** [comment]
it works now, thanks

**Comment by TheRealPingWin** [comment]
Works for me as well, thanks

**Comment by paulshryock** [comment]
I've been having the same issues mentioned in this thread lately.

- Pixel 9
- Android 16
- GrapheneOS 2025122501
- Signal 7.62.3

Edit: my issues were resolved after upgrading Signal to the latest version.
