### ISSUE TITLE
Sending video get stuck in "Processing..." and notification stuck showing "compressing video"

### ISSUE THREAD

**Issue by ndesai510** [signalapp/Signal-Android#14332]
### Guidelines

- [x] I have searched searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

### Bug description

I saw a similar post on Reddit, but no resolution posted there - https://www.reddit.com/r/signal/comments/1nbwghw/cant_send_videos_stuck_processing/

Android version 7.56.9

Been happening for about a week or so now.  Any video I try to send gets stuck and will not send.  I've cleared app cache, rebooting, force closing.

I will uninstall and re-install next to see if that helps.

### Device

Motorola Edge+ 2023

### Android version

Android 15

### Signal version

7.56.9

### Link to debug log

https://debuglogs.org/android/7.56.9/32914e58bce5cbdbc74cdd7f0e107e536a95e37a0c1569544275622c1edf7e0c

**Comment by ghub2015** [comment]
Same phone, same problem here.

**Android version**
Android 15

**Signal version**
7.56.10


- It started off with just one contact, but now affects multiple contacts.

- Once any message containing any media (video, photo, etc) gives the "Processing" and the spinning wheel in bottom right, any other message containing media (including just URL's which you allow to resolve the thumbnail) ... will _not_ send.  

- You _can_ send the affected contact a plain text message

- Tried mobile data only and WiFi only to see if any difference in behavior ... same result.

- Clearing cache etc does nothing to resolve.


Hope this helps @ndesai510 

Thank you

**Comment by fluckx-cs** [comment]
I've been struggling with this for a long time.
Nobody else seems to be having the issues in my direct circle.

I am, interestingly, also on a motorola device ( moto edge 40 pro ).
I assumed it was a flaw in my device, but maybe it's a motorola thing. That is going to be a pain to resolve.

I've had mixed success with stopping the send, force stopping the app, clearing the cache and retrying to send. Sometimes it gets further, sometimes it manages to send it. Sometimes it doesn't work at all.

It's quite frustrating

**Comment by ghub2015** [comment]
Agreed on the frustration.

One thing new I have noticed with this:

- After DAYS, I see the following notification in the notification list view:

`Message delivery failed.  Failed to...`

- When you click on it to read the entire message, it just goes to the Signal chat home screen and you can't read the entire message

- Only then will sending media _to that specific contact_ resume working

- Among my circle I have been the early adopter of Signal ... no one else seems to have the issue;  this issue _is_ frustrating

Thank you

> I've been struggling with this for a long time. Nobody else seems to be having the issues in my direct circle.
> 
> I am, interestingly, also on a motorola device ( moto edge 40 pro ). I assumed it was a flaw in my device, but maybe it's a motorola thing. That is going to be a pain to resolve.
> 
> I've had mixed success with stopping the send, force stopping the app, clearing the cache and retrying to send. Sometimes it gets further, sometimes it manages to send it. Sometimes it doesn't work at all.
> 
> It's quite frustrating

**Comment by RoryNorman** [comment]
Motorola Edge 2023 + here. Larger video sizes that require compression will freeze during random parts of the video compression/upload processing.

Force stopping the app will resume compression but will freeze randomly again. Eventually through force stopping enough I can sometimes get the video to fully process and send.

Only started happening to me when I switched from Samsung to Motorola.

**Comment by GBHZO** [comment]
I have the same issue, seems to be specific to Motorola phones running latest version of Signal and Android

**Comment by gustinn** [comment]
I have the same issue on a Fairphone 6

**Comment by Lod3** [comment]
> I have the same issue on a Fairphone 6

Same issue, same phone

**Comment by b-a0** [comment]
Same issue on Fairphone 4, Android 15 and Signal 7.64.2

Debug log in broken situation: https://debuglogs.org/android/7.64.2/a0e05d5b2c908ca54d68d181530f2c4bde71b6b872ab75b5b8447b5519e3ac0a

------
After trying the random workarounds above (clear cache, delete message, etc...) without any result I found that disabling the  "Photos and videos" permissions (i.e. setting to "Don't allow") and enabling it again when Signal asks for it, created a workaround: I can now upload videos again and processing happens in an instant.

Here's the debug log after this workaround: https://debuglogs.org/android/7.64.2/281a5115244ebbec12ba72cf3599d96dcba070f57970da092d2f8560d1c58f03

**Comment by senegalo** [comment]
Same on Fairphone 4 on android 15

it's a 15 seconds video !

![Image](https://github.com/user-attachments/assets/d33e8339-39b3-44ec-aa75-07f74e787b0a)

**Comment by b-a0** [comment]
At first I thought [the workaround](https://github.com/signalapp/Signal-Android/issues/14332#issuecomment-3539407441) resolved the issue for a while, but I found that I have to do this permissions dance *for every video I send*.

That's a bit cumbersome. Is there any other way of fixing or working around this?

**Comment by fluckx-cs** [comment]
None that I have found so far :(

**Comment by justfortherec** [comment]
> I have the same issue on a Fairphone 6

I also experience this on Fairphone 6. I was also a regular issue on my Fairphone 4 before.

In my experience, rebooting the device helps.

I will try out the permission workaround.

Edit: I can confirm that revoking "Photos and Videos" permissions and granting them again works for one video. The second video got stuck again. It restarted and succeeded with processing after I had performed the permissions dance.

**Comment by skamuuu** [comment]
Same issue on Xiaomi Redmi Note 13 Pro 5G. I usually reboot the device and then it starts, but it is really annoying. This needs a solution.

OS: Xiaomi HyperOS 2.0.206.0
Android version: 15 (31/12/2025 security update)
Signal version: 7.68.5

**Comment by michcio1234** [comment]
Same issue on motorola razr 40 ultra (XT2321-1) with Android 15.
The permission dance helps.

**Comment by arichiardi** [comment]
Has anybody tried if Molly exibits the same error?

**Comment by cody-signal** [comment]
We have a handful of video fixes coming out in 8.0 and 8.1, hopefully they resolve these issues. If not, please provide new debuglogs after you encounter the issue.

**Comment by Lod3** [comment]
> We have a handful of video fixes coming out in 8.0 and 8.1, hopefully they resolve these issues. If not, please provide new debuglogs after you encounter the issue.

It has to be said as well, I am having way less issues with videos, Signal is finishing the processing and uploading. Thank you

**Comment by ndesai510** [comment]
Still an issue with the latest version for me.

**Comment by cody-signal** [comment]
@ndesai510 any chance you could provide a debuglog and any details about the type of video (hd/hdr/mp4/etc)

**Comment by RoryNorman** [comment]
Still an issue for me as well. The issue definitely occurs during compression of larger files. The larger the file the more pronounced the issue. 

The baffling thing is, I can force kill the app, and upload a video over and over, and then eventually it will work.

It seems like there is something system specific with compression that hangs.

**Comment by ndesai510** [comment]
@cody-signal its an mp4. Not particularly big. 40 second video taken with gcam.
Attached is the log. 

[signal-log-1772117175064.zip](https://github.com/user-attachments/files/25578961/signal-log-1772117175064.zip)

**Comment by elietheocari** [comment]
Hello, I have the same issue on a Fairphone 4, with Android 15, and Signal 8.11.5.
The workaround listed above seems to work for me too (disabling photo / video permissions, then re-enabling them), but it's quite a hassle.
To be noted, it does not happen on a systematical basis. I would say more, every 3-4 weeks maybe before the problem comes back.

**Comment by mattcoxonline** [comment]
Signal version: 8.12.4
Android version: 15
Device: Sony Xperia 5 V (XQ-DE54)

I just had the same issue. 

Usually I have Signal set to _Not Allowed_ for photos and video permission, then share using the Photos app into Signal. No problem. 👍 

But this time I wanted to edit the video first, in Signals editor, so changed the permission to _Always Allow All_ and selected the video from within the Signal app. 

I trimmed the video using the in-app editor and then hit send and it hung on compression. Disabling and re-enabling permissions as described above worked to resolve the issue. The video finished processing and sent. 

I'm not even going to try to make a guess at where Signal is failing to detect that change in permission, or why toggling permissions on and off works to resolve the issue - but hopefully sharing the steps I took here helps.

**Comment by Heinz-Beans** [comment]
I have the same issue on a Samsung Galaxy S22+ running Android 14 with Signal version 8.15.3.

I managed to debug the issue a bit.

After sending one specific video, Signal enters a state where no other videos can be sent. Every video gets stuck in the "processing" state.

I backed up my data, reinstalled Signal, and restored the backup. After that, I was able to send videos again. However, when I tried sending the same video that had previously triggered the issue, it happened again. The video got stuck in processing, and from that point on, no other videos could be sent to anyone. This persisted even after deleting the problematic video from Signal.

For reference, the video has a 1:1 aspect ratio, a resolution of 3840×3840 pixels, runs at 60 FPS, and is 62 MB in size. It was recorded with an action camera.

I then re-exported the same video in a 4:3 aspect ratio and Full HD resolution. That version could be sent through Signal without any issues and did not trigger the bug.

**Comment by b-a0** [comment]
@Heinz-Beans Interesting finding, thanks for the making the effort to do a full backup/restore.
Curious if [the workaround I posted](https://github.com/signalapp/Signal-Android/issues/14332#issuecomment-3539407441) (toggle Photos and videos permission) also works around your issue with the 1:1 aspect ratio 3840 px video file?  
If not, perhaps you stumbled on a different issue?

**Comment by Heinz-Beans** [comment]
@b-a0 No, for me the permission toggling didnt work at all. I tried it several times. Also tried clearing cache or rebooting the phone. None of which worked for me.

**Comment by greyson-signal** [comment]
Hi @Heinz-Beans, please share a link to a [debuglog](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports) so we can investigate.

**Comment by LubomirKovalcik** [comment]
For me removing and adding permission for camera access, made photos and videos that were stuck send instantly. Maybe someone could fix it after these years?

**Comment by ghub2015** [comment]
It appears that this has now been resolved for my phone!  I believe it was fixed by a software update, but not sure of whether it was an Android update or Signal update that fixed it.

Working now for me on:

- Motorola Edge+ 2023
- Android: 16
- Signal: version 8.23.3

Thank you

**Comment by elietheocari** [comment]
Hello, still not working for me. This morning I have tried to send a 33 MB video (that I compressed beforehand to reduce the size) and it's stuck since already 5 minutes in the "Compressing video" state.
DebugLogs URL: https://debuglogs.org/android/8.23.3/c531bdcf8e27ac77fb5849670a73fec84b37938134611e40e32c1242715fd244
I started the upload around 9:54 GMT+02:00.
Thank you for helping

- Fairphone 4
- Android 15
- Signal 8.23.3
