### ISSUE TITLE
Forwarding Messages Shows Deleted Contact in Signal

### ISSUE THREAD

**Issue by nitishp-gh** [signalapp/Signal-Android#14405]
### Guidelines

- [x] I have searched searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

### Bug description

**Summary**

When attempting to forward a message in the Signal app, I see a deleted contact (Contact B) listed as a potential recipient, despite having removed them from all associated apps (Android Contacts, Google Voice, and Signal). This issue persists even after uninstalling and reinstalling the app.

**Details**

I had a phone A that had a contact B in the Signal app, the Android Contacts app, and the Google Voice app.

I removed contact B from phone A years ago, from the Contacts app and Google Voice app, and the Signal app.

Then, I got a new phone C, installed the Signal app, and the Google Voice app. In neither the Android Contacts app, the Google Voice app, or the Signal app did I have contact B.

However, when I select a message to forward in the Signal app, I see contact B as a potential recipient.

Contact B shows up as a Signal Connection. How I found that out is I went to compose a new Signal message, in the search bar for Contacts, I entered contact B's name, and it showed contact B is a Signal Connection, but Signal says "This person is no longer using Signal. Invite them to Signal to keep the conversation here."

**Steps to Reproduce**

1. Remove contact B from Android Contacts, Google Voice, and Signal.
2. Install Signal on a new phone.
3. Attempt to forward a message.
4. Observe that contact B appears as a potential recipient for forwarding.

### Device

Google Pixel 9 Pro

### Android version

16

### Signal version

7.62.3

**Comment by dfavaro** [comment]
This issue is likely due to Signal retaining conversation history or cached data for previously messaged contacts, even after they are deleted from your device's contacts and other apps. Have you perhaps restored any prev backup?

**Comment by nitishp-gh** [comment]
@dfavaro I wasn't aware of the backups feature, so there aren't any other backups, but thanks for the suggestion. Is there any other recourse?

**Comment by mtang-signal** [comment]
Hi! The next time this happens can you gather a [debug log](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug)?

**Comment by wertzuz** [comment]
@nitishp-gh is it still happening for you?

**Comment by nitishp-gh** [comment]
@wertzuz Yes, the issue persists.

@mtang-signal Here's the debug log after I tried forwarding a message to the contact who should no longer be accessible.

https://debuglogs.org/android/7.68.5/9fb8771c907db575224245bed73a9f964a7bca9edf818d58fce4cc5b40bc7b28

**Comment by wertzuz** [comment]
Any update?

**Comment by jeffrey-signal** [comment]
Fixed in 8.6

**Comment by nitishp-gh** [comment]
Issue persists in Signal 8.11.5 on Android.

I still don't see this person in my Android Contacts or Google Voice contacts, but somehow I do see that person as eligible to get Signal messages forwarded.

Is there a Contacts cache I can purge?

**Comment by jeffrey-signal** [comment]
> I removed contact B from phone A years ago, from the Contacts app and Google Voice app, and the Signal app.

Please confirm you removed the contact from Signal using [these steps](https://support.signal.org/hc/en-us/articles/360007319011-Manage-Contacts-Nicknames-and-Notes#contact_remove)?

> Is there a Contacts cache I can purge?

@nitishp-gh you can [refresh your Signal contacts list](https://support.signal.org/hc/en-us/articles/360007319011-Manage-Contacts-Nicknames-and-Notes#contacts_refresh), which will remove the system contact link for contacts you've removed from your phone and mark recipients as unregistered if they've left Signal (which appears to be the case for your situation). However, it will not mark them as hidden, which is the flag that controls whether they show up in the contact search.

Removing the contact using the steps above should prevent the contact from appearing in the search.

**Comment by nitishp-gh** [comment]
> > I removed contact B from phone A years ago, from the Contacts app and Google Voice app, and the Signal app.
> 
> Please confirm you removed the contact from Signal using [these steps](https://support.signal.org/hc/en-us/articles/360007319011-Manage-Contacts-Nicknames-and-Notes#contact_remove)?
> 
> > Is there a Contacts cache I can purge?
> 
> [@nitishp-gh](https://github.com/nitishp-gh) you can [refresh your Signal contacts list](https://support.signal.org/hc/en-us/articles/360007319011-Manage-Contacts-Nicknames-and-Notes#contacts_refresh), which will remove the system contact link for contacts you've removed from your phone and mark recipients as unregistered if they've left Signal (which appears to be the case for your situation). However, it will not mark them as hidden, which is the flag that controls whether they show up in the contact search.
> 
> Removing the contact using the steps above should prevent the contact from appearing in the search.

This solved it for me. Thank you so much!
