### ISSUE TITLE
Unable to connect to MMS server

### ISSUE THREAD

**Issue by rypervenche** [signalapp/Signal-Android#1721]
I have been using TextSecure for a while now and have had no issues so far until now. I believe this happened after the latest update, however I am not sure. I have checked my MMS settings several times; they have not changed since I first set them. I had been able to receive MMS messages before this problem, so I believe this is a problem with the application.

I receive an MMS message and it does not automatically download. I click on "Download" and it gives me the following two messages:

"Connecting to MMS server..."

Then after a certain amount of time:

"Error connecting to MMS provider..."

Please look into this, as it makes the app somewhat unusable. If you need any information from my phone, please let me know what you need and I will provide it.

Thank you.^^

**Comment by faffi** [comment]
Threads a little old, but FWIW I was having this issue on my N5 with Lollipop. Removing the custom MMSC URL and changing the stack to use IPv4 and rebooting resolved the issue.

**Comment by letrec** [comment]
Changing the stack to use IPv4 resolved the issue without rebooting on my unlocked N5 on T-Mobile.

**Comment by wayfairuser** [comment]
I'll try this again when I'm back on wifi, but I was pretty sure when I changed to ipv4, it was still broke.

**Comment by elyobo** [comment]
I sometimes receive MMS messages, other times it fails to connect to the MMS server.  The debug log makes it look like the correct APN details are being retrieved.  The settings for my network can be seen at [on this google cached page](https://webcache.googleusercontent.com/search?q=cache:dnZWDrux3BMJ:support.vaya.net.au/support/discussions/topics/20052+&cd=1&hl=en&ct=clnk); some of these settings cannot be overridden in TextSecure (MCC, MNC).

Debug log gist abailable at https://gist.github.com/anonymous/eb3985140898f7f78e61 - you can see an early success fetching an MMS followed by later failures.

I seem to recall that TextSecure used to have an option to not handle MMS messages, but I can't seem to find that now on Android L.  Am I dreaming or is that a thing?

**Comment by Murazaki** [comment]
Same issue here. The problem does not seems to relate with WiFi on my side.

I also wonder if anyone else tried to check/uncheck WiFi Calling ?

**Comment by Adalan** [comment]
My issues have been resolved with one of the latest updates (I think
2.9.0). I do not use WiFi calling though.

**Comment by w1res** [comment]
I'm still having this issue on a Moto X running Android 4.4.4. I'm on Verizon. I know that I had this problem a while back, and then I seem to think that it worked at some point after that (not 100% sure on that). I don't know when it started, but it is still not working for me.

To make it work, I have to disconnect from WiFi, receive the MMS, and then connect to WiFi again. Now that I have a VPN it is even worse, because I have to disconnect from WiFi, Disconnect my VPN, download the MMS, and then re-enable both.

**Comment by mcginty** [comment]
@w1res can you download MMS using another app while you're connected to VPN?

**Comment by RonCollins** [comment]
I'm also finding I have to disconnect my VPN to download the MMS.

**Comment by riyapenn** [comment]
@RonCollins do you have issues w/ Google Play or other websites or apps when connected to your VPN? Do you have a setting for
"Set MMS of TCP payload, 
Configured MMS value X" ?
What is X? Does changing X to a different number, like 1280 solve the problem?

**Comment by moxie0** [comment]
For most carriers, MMS won't work while connected to a VPN.  A lot of MMS servers use DNS names that resolve to the RFC1918 range, so it isn't possible to connect to them from a VPN's exit point on the internet, just from your phone's radio in MMS mode.  This is obviously true for any MMS app, not just Signal.

**Comment by Murazaki** [comment]
MMS work fine now for me. The only issue is we can't get MMS if cellular
data is not ON (which is how it should work). Shouldn't we ask the user to
enable data so that they don't get confused ?

**Comment by wesQ3** [comment]
I also have this issue intermittently, on a MotoX 2013/Cricket Wireless US. I know this issue is closed but having arrived here from a web search I thought I could share my current workaround with fellow searchers.

First off, sometimes MMS works fine. When it doesn't (and I get the "unable to download MMS.." error), sometimes switching off wifi lets Signal download the MMS. At some point in the past I set my APN and roaming APN to "IPv4 only" as an attempted solution. This time turning off wifi didn't fix it (I tried toggling it and re-trying the downloads) I switched my APN settings back to IPv4/IPv6 and the group texts downloaded immediately.

I'll get a log if it happens again. Hope this helps someone out there!

**Comment by n76** [comment]
That might not be a Signal issue as much as a general Android and mobile phone carrier issue: Even with the stock AOSP messaging app, if I am on a IPv4 only WiFi/WLAN network I can't get MMS messages from T-Mobile US (which uses IPv6). Turn off WiFi/WLAN and the download works fine.
