### ISSUE TITLE
Attachments cannot be sent from gallery - on certain phones sometimes

### ISSUE THREAD

**Issue by horstschimanski** [signalapp/Signal-Android#1744]
When trying to add an attachment, e.g. a picture, the dialog "Open" will only show the folder "Recent" and "Downloads". Sending pictures or videos that are stored in the gallery would be really nice.

**Comment by unrulygnu** [comment]
Reproduced on a stock Nexus 5:
* Google Nexus 5 D820
* Android 5.1 LMY47I stock; no superuser
* TextSecure 2.9.3
* AOSP Gallery2 1.1.40030 (`com.android.gallery3d`)
* Google Photos DISABLED

![side-by-each](https://cloud.githubusercontent.com/assets/11031903/7584691/1d7ddb02-f8da-11e4-8856-855069e3688a.png)
**Left**: TextSecure, after tapping "Add Attachment", then "Picture", then the hamburger menu.
**Right**: An app in development, after sending an `Intent` to choose images.

Please forgive the Korean; I've been trying to cut down. From the top, the text in the navigation drawer reads as follows: 
* Open:
* Recent
* Images
* Download
* Gallery (only in the right screenshot)

Relevant log entries:

**TextSecure**

    05-12 18:47:52.500     752-1170/? I/ActivityManager﹕ START u0 {act=android.intent.action.OPEN_DOCUMENT typ=image/* cmp=com.android.documentsui/.DocumentsActivity} from uid 10093 on display 0

**App in development**

    05-12 18:48:54.624     752-9970/? I/ActivityManager﹕ START u0 {act=android.intent.action.GET_CONTENT typ=image/* cmp=com.android.documentsui/.DocumentsActivity (has extras)} from uid 10096 on display 0

The <a href="https://developer.android.com/reference/android/content/Intent.html#ACTION_OPEN_DOCUMENT">`ACTION_OPEN_DOCUMENT`</a> `Intent` action was added relatively recently, in API 19 (Android 4.4 KitKat).  Apps which haven't added this action to an `intent-filter`, like AOSP Gallery2, will not be listed in a `DocumentsActivity` started with this action.

From <a href="https://developer.android.com/guide/topics/providers/document-provider.html">Storage Access Framework | Android Developers</a>:

> <a href="https://developer.android.com/reference/android/content/Intent.html#ACTION_OPEN_DOCUMENT">`ACTION_OPEN_DOCUMENT`</a> is not intended to be a replacement for <a href="https://developer.android.com/reference/android/content/Intent.html#ACTION_GET_CONTENT">`ACTION_GET_CONTENT`</a>. The one you should use depends on the needs of your app:
>
> * Use <a href="https://developer.android.com/reference/android/content/Intent.html#ACTION_GET_CONTENT">`ACTION_GET_CONTENT`</a> if you want your app to simply read/import data. With this approach, the app imports a copy of the data, such as an image file.
> * Use <a href="https://developer.android.com/reference/android/content/Intent.html#ACTION_OPEN_DOCUMENT">`ACTION_OPEN_DOCUMENT`</a> if you want your app to have long term, persistent access to documents owned by a document provider. An example would be a photo-editing app that lets users edit images stored in a document provider.

From **AttachmentManager.java**

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
          intent.setAction(Intent.ACTION_OPEN_DOCUMENT);
          try {
            activity.startActivityForResult(intent, requestCode);
            return;
          } catch (ActivityNotFoundException anfe) {
            Log.w(TAG, "couldn't complete ACTION_OPEN_DOCUMENT, no activity found. falling back.");
          }
        }
    
        intent.setAction(Intent.ACTION_GET_CONTENT);
        try {
          activity.startActivityForResult(intent, requestCode);
        } catch (ActivityNotFoundException anfe) {
          Log.w(TAG, "couldn't complete ACTION_GET_CONTENT intent, no activity found. falling back.");
          Toast.makeText(activity, R.string.AttachmentManager_cant_open_media_selection, Toast.LENGTH_LONG).show();
        }

Is there any reason not to remove the first block and just default to `ACTION_GET_CONTENT`?  It will better fit the guidelines from Google, have more backward compatibility, and media apps going forward should be supporting both.

PR incoming.

**Comment by unrulygnu** [comment]
Correction: PR **was** incoming, but the <a href="https://whispersystems.org/cla/">CLA page is broken</a>.

Cue sadness. ㅠㅠ

**Comment by TextSucks** [comment]
I registered just to comment on this. I recently installed TextSecure on Galaxy S4 v.4.4.2. and I have the same problem: you can't add videos, pictures or anything from Gallery! This has been reported OVER A YEAR AGO, and yet nothing has been done! I had to remove the whole bloody application. I'm so disappointed! Seems that nobody cares about fixing this.

**Comment by icyfyer** [comment]
I haven't seen this issue in more than 4 updates. I am also running the Samsung Galaxy S4, but with Android version 4.4.4 and Cyanogenmod 11-20141112-Snapshot-M12-jflte.

**Comment by icyfyer** [comment]
You should provide a log file so that they can troubleshoot your specific issue.

**Comment by paulbir** [comment]
Signal 3.5.2
Samsung Galaxy S4 I9500
Android 4.4.2, stock rom XXUFNB3 rooted

When I try to attach a photo, video or audio, appears this dialog with "Recent" and "Downloads".
![none](https://cloud.githubusercontent.com/assets/16079137/11467299/277c506c-9758-11e5-999c-445f78b28ef1.png)
I can't choose anything here, even from storage.

Then I found that I can enable choosing from internal storage by enabling some weird setting.
![weird_setting](https://cloud.githubusercontent.com/assets/16079137/11467333/5f8ecf98-9758-11e5-8d6d-375aff6e4f24.png)

But there is still no gallery or external sd card.

And here is how this dialog looks when I try to attach something in my mail program.
![mail_attachment](https://cloud.githubusercontent.com/assets/16079137/11467374/b782df00-9758-11e5-86d6-f58bee205c0b.png)

**Comment by unrulygnu** [comment]
There's a pull request pending review that, if it's approved and merged, should resolve this for you.

**Comment by Junohea** [comment]
Saw this was still open, so apologies if I should be placing this into a new issue but I'm having the same problem as defined in the OP with the following configuration:

- OnePlus One
- CyanogenMod 13 (Android 6.0.1)
- Signal 3.31.4

The issue has been in place for some time, an update broke the functionality but I didn't note the version that broke it, sorry.

When using Signal to attach pictures/files it only shows basic functionality
![screenshot_20170320-140957 01](https://cloud.githubusercontent.com/assets/13029766/24119726/d394034a-0d77-11e7-9868-e476477c47e8.png)



But previously it had shown all available apps for browsing photos/attachments in the "Open From" dialogue as shown here (other apps work fine. Screenshot from Hangouts app)
![screenshot_20170320-142002](https://cloud.githubusercontent.com/assets/13029766/24120034/ca5b6f1a-0d78-11e7-9a3b-1bc75e715e77.png)

Another user showed a checkbox for "show advanced devices" but I had no such option available to add the functionality back in within any of the apps or "Open From" choosers. 

Let me know if this isn't the right place for it and I'll move it elsewhere, Thanks.

**Comment by Junohea** [comment]
Tested on another device setup and the issue still exists.

Oneplus 5
Oxygen OS 4.5.13 (Android 7.1.1)
Signal 4.11.5

Actual result: Selecting to add photo from gallery pulls up a basic selector (Recent/Images/Downloader)
Expected result: Selecting to add photo from galley should show all available photo apps or handlers (QuickPic/Google Photos/etc)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
