### ISSUE TITLE
Black preview of camera while linking with signal desktop 

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#4843]
When i am trying to pair my device with signal desktop, the QR code can not be scanned. The preview is black and nothing happens (see image below).
![screenshot_2015-12-09-14-33-39](https://cloud.githubusercontent.com/assets/16224851/11686795/65c02bf0-9e83-11e5-816d-6d9414d4b651.png)

Device info: Samsung GT-S7710, Android 4.1.2, Signal 3.6.1
Debug logs: https://gist.github.com/anonymous/e179a4400f275da6e5de

I found a little workaround. When entering the menu in landscape view the problem does not occur and also after rotating back everything does fine.

**Comment by danf** [comment]
I am having the same issue with a Moto E 2nd Generation (XT1528) with Android 5.1 and Signal 3.7.2. The landscape workaround does not work for me.

**Comment by leonkons** [comment]
Same issue on Xperia M 
Android 4.3
Signal 3.14.2
https://gist.github.com/afa124370b11b73ea7ca51eb99e0e84f

**Comment by kimocrossman1** [comment]
I'm having this too
Nexus 6p
Android 6.01
Signal 3.15.2

**Comment by tomtomklima** [comment]
Still active on Samsung GT-S7710+  Android 4.1.2

**Comment by konnykonny50** [comment]
I did some research and found out that my problem depends on the resolution chosen for the preview. Even though there are a lot of supported preview sizes listed not all of them seem to work equally. For landscape 1280x720 is chosen and this does well. But with 960x720 pixels in normal position the camera does not start and the following errors are thrown:
```
W/Camera: Camera server died!
W/Camera: ICamera died
E/Camera:` Error 100
```

The issue of @kimocrossman1 might have a different reason since the log file contains a RuntimeException. This does not occur in my case anywhere.

**Comment by danf** [comment]
I'm not an Android developer, but it seems like the problem is somewhere around [here](https://github.com/WhisperSystems/Signal-Android/blob/a307ff350c4f2ef0c778b1e2fd4656cb6ac086e6/src/org/thoughtcrime/securesms/components/camera/CameraView.java#L306). It would appear that it should be using [getSupportedPreviewSizes()](https://developer.android.com/reference/android/hardware/Camera.Parameters.html#getSupportedPreviewSizes%28%29).

**Comment by tomtomklima** [comment]
Well, on Samsung GT-S7710 works the landscape mode. Thanks!

**Comment by konnykonny50** [comment]
getSupportedPreviewSizes() is used (see [here](https://github.com/WhisperSystems/Signal-Android/blob/a307ff350c4f2ef0c778b1e2fd4656cb6ac086e6/src/org/thoughtcrime/securesms/components/camera/CameraView.java#L310) and [here](https://github.com/WhisperSystems/Signal-Android/blob/a307ff350c4f2ef0c778b1e2fd4656cb6ac086e6/src/org/thoughtcrime/securesms/components/camera/CameraUtils.java#L37)) and returns a lot of resolutions. This is also reported in the log file:
```
W/CameraUtils(21024): getPreferredPreviewSize(90, 480, 678) -> target 678x480, AR 1,41
W/CameraUtils(21024):   1280x720 (1,78)
W/CameraUtils(21024):     (good size, suboptimal ratio)
W/CameraUtils(21024):   960x720 (1,33)
W/CameraUtils(21024):     (good size, suboptimal ratio)
W/CameraUtils(21024):   800x480 (1,67)
W/CameraUtils(21024):     (good size, suboptimal ratio)
W/CameraUtils(21024):   720x480 (1,50)
W/CameraUtils(21024):     (good size, suboptimal ratio)
W/CameraUtils(21024):   640x480 (1,33)
W/CameraUtils(21024):   352x288 (1,22)
W/CameraUtils(21024):   320x240 (1,33)
W/CameraUtils(21024):   176x144 (1,22)
W/CameraView(21024): starting preview with size 960x720
```
But some of these resolutions seem not to work on my device.

**Comment by gerg5c42g542g2c54g52c** [comment]
Same issue here. Stock unmodified Sony Xperia M with all the updates installed of both OS and Signal.

**Comment by danf** [comment]
FWIW, this is no longer an issue for me after a recent update.

Moto E 2nd Generation (XT1528) with Android 5.1 and Signal 3.16.0.

**Comment by kimocrossman1** [comment]
hi @kimocrossman1 here, it is fixed on the Nexus 6P

**Comment by gerg5c42g542g2c54g52c** [comment]
Checked again with the newest version of Signal and in landscape mode. It's still not fixed for Sony Xperia M.

**Comment by japostoles** [comment]
Not working here either with latest version.

Nexus 5X, Android N

**Comment by 2-4601** [comment]
@japostoles 
> Not working here either with latest version.
> 
> Nexus 5X, Android N

Works fine here with Nexus 5x, stock 7.0, Signal 3.18.3.

**Comment by Caligatio** [comment]
I had this problem with my Nexus 5X running Android 7.0 and 3.19.1.  I previously had denied access to my Location and Calendar but granting Signal access to both made the camera work.  I could then actually turn them both back off and the camera still worked.

**Comment by ted42** [comment]
I'm having the same issue on the Nexus 5 using the latest cyanogenmd nightly "13.0-20160928" and Signal version 3.19.1.
https://gist.github.com/anonymous/040555f965795df6c0f4b02025297b06

**Comment by ComiR** [comment]
Same issue here.
```
Device  : Samsung GT-I9505 (jflte)
Android : 7.1.1 (eng.b--b.20161212.005427, NMF26O)
Memory  : 13M (25.36% free, 192M max)
Memclass: 192
OS Host : JDCTeam
App     : Signal 3.25.4
```
https://gist.github.com/anonymous/d629bda1c86410dccbeca5a8c55a0d85#file-cat-log-L77

Perhaps because of the usage of deprecated `android.hardware.Camera`?

**Comment by yhager** [comment]
Same issue here. Even accessing the camera through the chat window results in a black screen. I had signal working on this phone in the past with no problems, but had to reinstall it after a wipe. I managed to activate the camera once and link another computer, but no more.
````
Device  : BLU BLU Advance 5.0 (BLU_Advance_5.0)
Android : 5.1 (1458805524, ALPS.L1.MP6.V2_6580.WE.L)
Memory  : 20M (10.20% free, 256M max)
Memclass: 128
OS Host : C208
App : Signal 3.28.4
````
debug log: https://gist.github.com/anonymous/dae7e76b04be052e9da5d034512e21c5

**Comment by ComiR** [comment]
fyi: I got a new phone and it works:
```
Device  : samsung SM-G920F (zerofltexx)
Android : 6.0.1 (G920FXS4DPJ5, MMB29K.G920FXXS4DPJ5)
Memory  : 26M (11.34% free, 512M max)
Memclass: 256
OS Host : SWHD8913
App     : Signal 3.28.4
```

**Comment by ted42** [comment]
So, it turns out my Signal was missing the camera permission.
After enabling it, everything worked fine.

**Comment by aleksandersumowski** [comment]
Still happening in latest version on Oreo:

Device: OnePlus 5
Android version: OxygenOs 5.0.3 - 8.0.0 (108, ONEPLUS A5000_23_180129)
Signal version: 4.15.5

The workaround didn't work for me

**Comment by matthewpucc** [comment]
Ran into this issue on a pixel 2016 (8.1.0) and removing camera permissions and re-adding them worked.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
