### ISSUE TITLE
Unsharp pictures with built in camera

### ISSUE THREAD

**Issue by m-terlinde** [signalapp/Signal-Android#5276]
I have:
- [X] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
### Bug description

If I take pictures with the built in camera function the preview is very sharp, but if I take the picture it suddenly gets very unsharp.
A friend of mine has the same problem on a Samsung mobile phone.

![screenshot_2016-02-21-23-00-16](https://cloud.githubusercontent.com/assets/10097313/13205787/5a3adc60-d8f0-11e5-90c3-8f1681ba290d.png)
![screenshot_2016-02-21-23-00-27](https://cloud.githubusercontent.com/assets/10097313/13205786/5a3a628a-d8f0-11e5-85bf-420f83dafe9a.png)
### Steps to reproduce
1. Try to take a picture (very clear picture)
2. Take the picture (unsharp)
### Device info

 **Model:** Google Nexus 5

 **Android version:** CyanogenMod 11-20150901-SNAPSHOT-XNG3CAO3G0 (4.4.4)

 **Signal version:** 3.11.1
### Link to debug log

https://gist.github.com/f72c35cd81f8941a661e

**Comment by 2-4601** [comment]
Related #4637, though the devices are mostly Samsung (GSII) but there's one Nexus 6P.

**Comment by m-terlinde** [comment]
Okay, I dind't found that one.

If you need more logs or so on, please let me know!

Yeah, I read the instrucions, they are very clear ;).

**Comment by 2-4601** [comment]
Hmm... there doesn't seem to be any camera activity in the log you posted. You could try capturing another log immediately after the focus has failed.

**Comment by m-terlinde** [comment]
I hope, this is better!

https://gist.github.com/83b1aeb86a595bf2a9dd

The first foto was sharp, the second wasn't!

Am 22. Februar 2016 02:28:10 MEZ, schrieb 2-4601 <notifications@github.com>:

**Comment by Argafal** [comment]
On a related note, it's also not possible to select the focus point by taping a location in the screen, or to activate the flash.

**Comment by sashw** [comment]
I can confirm this behaviour on my Nexus 5 running CyanogenMod 12.1
With the built-in camera function everything is sharp, but once the picture is taken it's always blurred.

**Comment by p512** [comment]
Also have this issue on OnePlus One running Signal 3.14.2 on CM 11.

**Comment by jnns** [comment]
Same issue occurs on a Nexus 5 running Android 6.0.1.

### Device info

**Device:** Google Nexus 5 (hammerhead)
**Android version:** 6.0.1 (2862625, MOB30M)
**Signal version:** 3.16.0

### Link to debug log
https://gist.github.com/anonymous/5322546c0014d01c70cfe258099057e3

**Comment by m-terlinde** [comment]
I think there isn't a fix yet?
Does the developers know, whats the exact problem?

**Comment by 2-4601** [comment]
If you can, you might want to try a newer version of cyanogenmod. See https://github.com/WhisperSystems/Signal-Android/issues/4637#issuecomment-241203827

**Comment by m-terlinde** [comment]
I'll give the new Snapshot a try and will report next week.

**Comment by merkste** [comment]
I experience the same problem on a Moto G 3rd gen. However, the preview image ist unsharp es well. The in-app camera does not focus. This also affects the ability to scan QR codes for linking and security numbers and makes this very hard. Would a debug log be useful?

# Device Info
**Model:** Motorola Moto G3
**Android version:** Android 6.0.1 (from manufacturer)
**Signal version:** 3.23.0

**Comment by smichel17** [comment]
I'm on 3.24.1 and this still exists. Info for reproducing: this happens far less often when trying to take a picture of text or something else with sharp, bold lines.

Even if I can't choose a spot on my screen to focus on, it would be helpful (both to getting a nice picture and to dbugging) if tapping the image forced a refocus. Maybe that's also focused enough that a member of the community could submit a patch?

**Comment by m-terlinde** [comment]
> If you can, you might want to try a newer version of cyanogenmod.
This exists with the newest release for the Nexus 5 aswell.

**Comment by jnns** [comment]
Tried this yesterday with CyanogenMod 14.1-20161212-NIGHTLY-hammerhead. The problem persists.

**Comment by m-terlinde** [comment]
The new CyanogenMod build didn't help as well.

**Comment by jhellen** [comment]
Still there :(
Signal 3.26.2
Motorola MotoG 3rd gen
Android 6.0

**Comment by hynz** [comment]
I can confirm this behaviour for Nexus 5, Android 6.0.1 with Signal 3.29.6.

I would like to add that to me it seems as if the cameras auto-focus works. At least the in-app-preview of the picture is sharp. As far as I get it, it is the moment of shooting a picture which seems to initiate a refocussing/unfocussing of the camera. In a lot of cases this then leads to a blurred shot (as already depicted in the first post).

The only workaround I see is to use the camera feature available from the "attachments"-Button, which works just fine.

**Comment by m-terlinde** [comment]
Luckily my new LG G5 doesn't have the autofocus problem.

Could this problem be limited to a few mobilephones?

Am 15. Februar 2017 15:23:02 MEZ schrieb hynz <notifications@github.com>:
>I can confirm this behaviour for Nexus 5, Android 6.0.1 with Signal
>3.29.6.
>
>I would like to add that to me it seems as if the cameras auto-focus
>works. At least the in-app-preview of the picture is sharp. As far as I
>get it, it is the moment of shooting a picture which seems to initiate
>a refocussing/unfocussing of the camera. In a lot of cases this then
>leads to a blurred shot (as already depicted in the first post).
>
>The only workaround I see is to use the camera feature available from
>the "attachments"-Button, which works just fine.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/WhisperSystems/Signal-Android/issues/5276#issuecomment-280023328

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by smichel17** [comment]
I can confirm it on a Galaxy S6. In my experience, it tends to happen more with close-up pictures. However, certain types are okay (ie, when I try to take pictures of text at a similar distance, I rarely have the issue).

My best guess it that when Signal has a hard time picking out text or other straight lines as a focal point, it just goes to a default focal point that is most often wrong. Here's an example of an amp. Granted, the lighting is also somewhat poor here.

![signal-amp](https://cloud.githubusercontent.com/assets/6563664/23006242/a1c0b6a0-f3ce-11e6-820f-1978cb2d83d2.jpg)
Signal's version

![better-amp](https://cloud.githubusercontent.com/assets/6563664/23006246/a665c45c-f3ce-11e6-88b3-b82343cb8fb2.jpg)
A different camera app

**Comment by ngulden** [comment]
I no longer observe this issue on my Samsung Galaxy SII (GT-I9100) running LineageOS 14.1-20170307-NIGHTLY (Android 7.1.1) and Signal 3.30.4.

**Comment by hynz** [comment]
I cant observe the issue anymore either (Nexus 5, Stock Android 6.0.1), Signal 3.31.4). Great!

**Comment by jnns** [comment]
This problem does no longer occur for me as well since 3.31.4.

**Comment by m-terlinde** [comment]
I didn't have the problem with my new LG G5. 
I can't confirm it for my old Nexus G5, because I don't use it any more.

Do you guys agree, that this issue is solved?

**Comment by Rondom** [comment]
I encountered this as well, but unfortunately my Nexus 5 is broken. Tthe fact that there has already been one Nexus-5-user (@hynz) who confirmed it working is a good sign :-)

It would be interesting what kind of change fixed it, though.

**Comment by merkste** [comment]
I still experience unsharp pictures in version 3.31.4. The camera does not seem to refocus at all.

**Comment by jhellen** [comment]
Still having this issue on Motorola Moto g 3rd gen 2015

**Comment by aidan-fitz** [comment]
I'm having this issue on my Samsung Galaxy J3 (2016).
![blurry qr scan on galaxy j3](https://user-images.githubusercontent.com/2768977/29139503-372880d6-7d15-11e7-8129-6b9af6140b36.png)

**Comment by AlexandreBonneau** [comment]
With signal 4.14.9 on an old Samsung galaxy s2, the camera is blurred (Under Cyanogen 11)

**Comment by AlexandreBonneau** [comment]
Note: I just upgraded to LineageOS 14.1-20171213-nightly-i9100, and the bug is still there.
It's a critical bug since it prevent using the desktop app altogether.

**Comment by jnns** [comment]
Still having this issue with updated system and Signal app:

Device                    | Google Nexus 5 (hammerhead)
------------------------|------------------------------------
Android version      | 8.0.0 (2862625, MOB30M)
Signal version         | 4.14.10
LineageOS version | 15.0.-20171204_082331-UNOFFICIAL-hammerhead
Kernel version        | 3.4.0

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
