### ISSUE TITLE
Reply line gets closed when chat partner sends new message (Android N direct reply notification)

### ISSUE THREAD

**Issue by tge-linee** [signalapp/Signal-Android#6042]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
If I try to answer a message from the notification with the new direct reply functionality and my chat partner keeps sending new messages the reply line gets closed every time a new message arrives. With the standard Messenger app the reply line stays open.

### Steps to reproduce
- have Signal closed
- receive a new message
- hit "REPLY" on the notification (Android N)
- start typing the reply
- receive a new message

**Actual result:** The reply line gets closed.
**Expected result:** The reply line should stay open.

### Device info

**Device:** Nexus 5X
**Android version:** 7.1
**Signal version:** 3.26.2

### Link to debug log

If you need one let me know, but I don't think it shows anything.

**Comment by jimbudarz** [comment]
Couldn't this be solved by freezing new notifications while the user is writing reply in the original notification? Just stopping the app from sending new replacement messages while there is text in the box?

**Comment by FeuRenard** [comment]
Maybe, but #6050 seems to be the preferrable way to resolve this issue.

**Comment by C0d3ineC0wboy** [comment]
This issue is still persisting. Extremely frustrating. when I'm typing a reply via the quick reply line and get another message. Since the new message closes the quick reply line along with my keyboard it usually causes me to press something on the screen that I didn't want to that would otherwise be covered by my keyboard.

This is been my number one issue with Signal over the course of the past two and a half years. I think the reason it's most frustrating to me is because it's such a simple fix and it's been persistent for such a long time.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
