### ISSUE TITLE
Anonymous bug reporting mechanism reveals personal info

### ISSUE THREAD

**Issue by malkhamis** [signalapp/Signal-Android#6276]
### Bug description
Anonymous bug report contains personal and potentially identity-revealing info.

### Steps to reproduce
- generate a bug report if you experience a problem with initiating a video call.
- I didn't test without having a video issue (ie creating a debug report immediately after video call).

**Actual result:**
02-21 17:19:36.919 11297 11297 W WebRtcCallActivity: Got message from service: [State: CALL_CONNECTED, recipient: **((((+1 123-456-789))))**, identity: null, remoteVideo: false, localVideo: true]

**Expected result:**
identity-revealing information shall not be present in an anonymous bug report

### Device info
**Device:** Google Nexus 5X
**Android version:** 7.1.1
**Signal version:** 3.29.6

**Comment by malkhamis** [comment]
More examples (phone numbers were changed for privacy):

02-21 17:19:36.352 11297 11297 W WebRtcCallActivity: Got message from service: [State: CALL_CONNECTED, recipient: **+1 123-456-7890**, identity: null, remoteVideo: false, localVideo: true]
02-21 17:19:36.354 11297 11297 I org.webrtc.Logging: EglRenderer: setMirror: true

02-21 17:19:36.919 11297 11297 W WebRtcCallActivity: Got message from service: [State: CALL_CONNECTED, recipient: **+1 123-456-7890**, identity: null, remoteVideo: false, localVideo: true]

02-21 17:19:40.365 11297 11297 W WebRtcCallActivity: Got message from service: [State: CALL_CONNECTED, recipient: **+1 123-456-7890**, identity: null, remoteVideo: true, localVideo: true]

02-21 17:20:36.242 11297 11297 W WebRtcCallActivity: Got message from service: [State: CALL_DISCONNECTED, recipient: **+1 123-456-7890**, identity: null, remoteVideo: true, localVideo: true]

**Comment by 2-4601** [comment]
I can reproduce this if I format the contact's phone number in my system contact's app as:
`123-456-7890`
instead of
`1234567890`

Not sure if this is a problem in Signal or in libpastelog.

**Comment by McLoo** [comment]
Fixed with  742b54f (#6310)

**Comment by 2-4601** [comment]
Hmm... 742b54f32d20b38a2117cf556c93c33f20fdd4ca did not fix this. Seems like there are some parts in the calling code where phone numbers are not converted to e164.
Tested with 4.0.0.

**Comment by Trolldemorted** [comment]
@2-4601 how can i test that? Just convert a contact to e164 and initiate a webrtc call?

**Comment by 2-4601** [comment]
> how can i test that? Just convert a contact to e164 and initiate a webrtc call?

Change the contact's number so that it doesn't have the `+1` country code. And possibly add some dashes between the numbers.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
