### ISSUE TITLE
Android 8 notification dot does not display until there are multiple threads with unread messages

### ISSUE THREAD

**Issue by riyapenn-signal** [signalapp/Signal-Android#7580]
I have:
- [X] searched open and closed issues for duplicates; could be a duplicate of https://github.com/signalapp/Signal-Android/issues/7322 if it's the same root cause
- [X] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports 

----------------------------------------

### Bug description
On Android 8, the notification dot does not appear on the app icon until there are unread messages in multiple conversations. Notifications still appear in the notification drop down. This issue is only for the app badge/dot that displays on the icon.

### Steps to reproduce
- receive a message in thread A
- See no notification dot 
- leave the message unread
- receive a message in thread B

**Actual result:** See notification dot only when there is more than one thread with an unread message
**Expected result:** See notification dot for any unread message

### Screenshots

N/A

### Device info 
**User 1**

**Device:** Samsung Galaxy S9
**Android version:** 8.0.0
**Signal version:** 4.16.9

**User 2**
**Device:** Samsung Galaxy S8
**Android version:** 8.0.0
**Signal version:** 4.17.5

**User 3**
**Device:** Samsung Galaxy S8+
**Android version:** 8.0.0
**Signal version:** 4.16.9

### Link to debug log
**User 1**

One message received, no badge/dot:  https://hastebin.com/xoyadaqazo 
Two threads with new messages and the badge appeared:  https://hastebin.com/ixatociwez 

**User 2**
One message received, no badge/dot: https://debuglogs.org/1d1c957eaa4a0e685b55b96a5f29bc49fca4d5c380f3a08f4c5e3f02c3941b56
Two messages received and the badge appeared: https://debuglogs.org/f385f1c6367df132ac06221ca0b238c1058fb1627f9e67d59bdf570f76cd9363

**User 3**
One message received, no badge/dot: https://hastebin.com/udojuhozic
Two messages received and the badge appeared with a count of 2: https://hastebin.com/biwakefoda

**Comment by ahgoodman** [comment]
I have the same issue:
Device: Pixel 2 XL
Android Version:  8.1.0
Signal Version:  4.17.5

One message Received no badge: https://debuglogs.org/47f2ef85b8f5fddd3a0773f2c5835ac01a622e10d56bea2f32d4cae7f05801c7

**Comment by ADepic** [comment]
I'm sorry OP, but you got the android version and signal version mixed up. Apparently your galaxy s9 runs android 4

**Comment by jeremymasters** [comment]
Oddly enough, if you read the first message, it still shows the dot because the second one isn't read yet.

**Comment by whaco1** [comment]
I experience the same behavior.

Device: Samsung Galaxy S7
Android version: 8.0.0
Signal version: 4.19.3

**Comment by MickMickle** [comment]
Possible temporary workaround(?): Send a Signal message to yourself from a second instance/account and always leave it unread. Based on other comments here, that may create a constant baseline of "1" unread message on the icon badge, so new messages would start with "2", which is an improvement over nothing.

Maybe the second Signal account could use a Google voice number. I tried to test using my Note 8 Dual Messaging capability in the settings Advanced Features; however, Signal is not shown as supported (only Facebook, WhatsApp, and Messenger (Facebook) show up).

**Comment by SingerGuy** [comment]
I am experiencing this as well. I have a Samsung Galaxy S7 running Android 8.0 Oreo and Signal 4.21.6. When I have only one unread message I do not get a badge. I have turned badge notification off, restarted the phone, and turned it back on again and the behavior did not change.

**Comment by MickMickle** [comment]
I tested the possible workaround I described above using Samsung Secure Folder to install a second Signal account with my Google Voice number. If you first send a test message from the second account, you'll have no number on the Signal icon, as expected since that's the issue. Then after you get another message, you'll have the number "2". After reading the second "real" message, but never reading the permanent test message, the baseline number "1" will remain on the icon. However, the downside is that you'll also still have that first test message in the notification panel, which is not acceptable for me. And when you clear that notification in the notification panel, the icon number will disappear. Therefore, this isn't a good workaround.

**Comment by sowcrayts** [comment]
I am having this problem, too.

Device: Samsung Galaxy S7
Android version: 8.0.0
Signal version: 4.22.4

**Comment by MickMickle** [comment]
FWIW, as a clue to maybe help fix this problem:  I just tried out the Microsoft Launcher as an alternative to the stock "Samsung Experience Home" (although I still like Samsung's home screen launcher), and the notification badge shows up just fine on the Signal icon.

**Comment by ImAGitHubUser** [comment]
I'm having the same problem as the other reporters. 

ANDROID 8.0.0
SAMSUNG S7
Samsung Experience 9.0
SIGNAL 4.24.8

When one thread contains unread messages, no badges appear. 

When two or more threads contain unread messages, the badge works.

**Comment by jeremymasters** [comment]
I believe this is fixed (at least for me) in 4.25.2

**Comment by MickMickle** [comment]
That's a good sign, but Google Play store's version is still 4.24.8. How do you get the later version?

**Comment by MickMickle** [comment]
Thanks for the beta info. I joined up easy. But I'm still not getting a badge showing number of messages received over the icon in the home screen. (Testing from a second installation of Signal in the Samsung secure folder.)  Any particular settings to adjust? I do have App icon badges turned on in the system settings. I also see in the beta what's new: "★ Use notification channels in your system settings on Android 8.0+ to customize alert behavior for incoming messages, calls, and more."

The working icon badge is just too important to me. I need the fact that I've got a message to be very obvious if I miss the notification when it occurs. And I think the status bar is often a bit subtle.

**Comment by bme13** [comment]
Based on the comments from @jeremymasters I would expect this to work in the 4.25 release however for the Samsung S9 the behaviour remains. Attached a logfile with the next test. Starts at 19:14.
- message from contact A.(no notification dot)
- second message from contact A (still no notification dot)
- message from contact B (notification dot, with correct number of messages 3)

The app icon badge setting is turned on in the setting. Don't know if other settings are needed.
Since a different launcher was suggested I've tested both MS Launcher and Nova Launcher. For both launchers the notification dot did not work.
https://debuglogs.org/a650b52f0aa52320a94d8ee2bb8547b8285b83ccdc4be13ba77f5216b66c286a

**Comment by jeremymasters** [comment]
I actually need to report that it doesn't work now.  I think the reason it was "working" was that there was a bug that included the "signal unlocked" notif as the first notification, which is normally ignored currently.  Now it's not doing that since channels stuff was re-tooled some more in 4.25.  To be clear, it was working and it's stopped working again.  Basically it looks like an issue where it doesn't count the first conversation's notifications (1 or many) for the notification dot/counter until there are other conversations with notifs.

**Comment by MickMickle** [comment]
I agree that it doesn't work even with the latest beta.  I gave feedback via the Android beta channel, but I really have no idea who or where or what good this reporting does.  I'll try the MS Launcher later (I actually forgot how to access it) and let you know, because it did let the badge work when I did it.

**Comment by whaco1** [comment]
agreed. no notif badge symbols unless two or more conversations have at least one unread message.

**Comment by MickMickle** [comment]
Although @bme13 did not get an icon badge using a different launcher, I just gave Microsoft Launcher another try on Samsung Note 8, Android 8.0.0.  Right off the bat with only one Signal message, I successfully got a "1" dot on the Signal icon on the home screen. 

My test method is to send a message to myself from a second installation of Signal in the Samsung Secure Folder which allows the installation of second accounts of various apps (including Signal) on the same phone.  If I then switch back and forth between MS Launcher and the default Samsung Experience Home (ver. 9.0),  the icon badge with the number "1" disappears and reappears (Settings> Apps> Default Apps> Home Screen).  If you can't see the badge in MS Launcher, there's a lengthy FAQ in the MS Launcher settings about, "I’ve enabled “Notification badges” in settings, but I don’t see them in my launcher. Either they have stopped displaying after a period of use, or I never see them in the first place."

**Comment by bme13** [comment]
I just tried MS Launcher again and indeed @MickMickle, after changing settings in the launcher itself the icon badge works. Directly showing the first message.
I've created a log while using the Samsung launcher using logcat which contains some additional messages about the icon badges.[Here's](https://github.com/signalapp/Signal-Android/files/2329663/badge.txt) a snippet of that. If needed the complete log is available.

**Comment by greyson-signal** [comment]
We use notification channels now for Android 8.0, so well-written launchers should be showing the dot appropriately.

**Comment by jeremymasters** [comment]
I'd like to report that this is still a problem on galaxy s9 (verizon stock).  If there is only one contact with notifications, it shows no indicator on the icon.  If there are two or more, it shows the correct total count.  Not sure if this is because I used some beta versions or not, but it's a little frustrating.

Signal 4.25.10

**Comment by SingerGuy** [comment]
Still not fixed for my Verizon Samsung Galaxy S7 (SM-G930V) using Signal 4.25.10. I can have multiple messages from a single contact (or MMS group) and have no badge. It is only when I have at least one message from a second contact that the badge appears and accurately reflects the number of messages waiting. Please re-open this issue until it is correctly resolved.

**Comment by ImAGitHubUser** [comment]
Agreed.  This is not working on Samsung S7 using Signal 4.25.10.  

As described above, badges only appear when there is more than 1 unread messages from two or more distinct contacts.  

Thank you.

**Comment by MickMickle** [comment]
Still not working on Samsung Note 8 Unlocked on T-Mobile when only one message has been received. Apparently, Samsung Experience falls into the category of well-written launchers NOT. Let's blame the devices.

**Comment by jeremymasters** [comment]
My example is:
1. contact sends me one message
2. I get notifications in my notification bar, etc, but NOT on the icon ( don't actually read the message yet)
3. Another contact sends me a message.
4. NOW I get the icon with two messages (the appropriate total count) showing.
5. read message at the TOP of the contact list first, leaving the other unread in spot 2
6. note that the notification dot still is there and shows the correct count

**Comment by MickMickle** [comment]
I have (had since I first installed Signal) the same bug as @jeremymasters experiences.

**Comment by greyson-signal** [comment]
I've been able to repro this. I can confirm that the Samsung Galaxy S9 has the same problem that @jeremymasters described.

I've also confirmed the same problem with the notification dot on the Pixel launcher (minus the count, since the Pixel launcher only shows a generic dot regardless of the count).

I'll look into this. FWIW the [Android documentation](https://developer.android.com/training/notify-user/badges) implies that we should't have to do anything special to get the dot. My guess is we're screwing up something when we call NotificationCompat.Builder#setNumber().

**Comment by mrHJS** [comment]
Any news on this? Problem still there...

**Comment by greyson-signal** [comment]
@mrHJS Lots of stuff happening right now with the target26 migration, so I just don't have time to look at this at the moment. If anyone else wants to investigate this or even make a PR in the meantime, I'd be more than happy to look at it. Thanks!

**Comment by inqgithub** [comment]
Just want to add that my Samsung A3 (Android 8.0.0) has this problem too.

**Comment by DonDino2** [comment]
I've just noticed that my phone has this problem as well.

Model: Galaxy S7 Edge
Android: 8.0.0
Signal: 4.29.0 (beta)

No dot. So far I only have one conversation at a time (still not enough Signal contacts!), so I've not been able to test it when there's two messages from two different conversations waiting.

**Comment by jeremymasters** [comment]
@inqgithub  @DonDino2 one of the things here is that if you are just having the issue too, but don't have additional info, go ahead and use the response like the thumbs up or something.  If you have more info, list the debug log as well.  Entries here email tons of people, so the "me too" comments make it harder to sift out the comments with logs, etc.

**Comment by bme13** [comment]
Based on the code in MessageNotifier.java I noticed a difference in handling single and multiple thread notifications. As a test I've build my own signal (first time :smiley: ) with some debug and tested some changes to see if I could get the badger work for a single message on the Samsung S9.
It turns out that if I changed the bundled argument from false to true in the 
sendSingleThreadNotification() call for a single thread notification (line272)  I get the message dot with 1 after the first message. Also if I send an second message on a different thread the message increases to 2 and after reading one message the count decreases to 1 again. That also seems to work correctly then.
Now I'm not an android programmer and I guess this is not a real solution however I hope this helps to identify the problem.

**Comment by imcurtispenner** [comment]
I'm having the same issue using a Samsung S9 plus running Android 8.

**Comment by TheShanMan** [comment]
Same on HTC 10. I talked my friend (has an S9 I think) into trying Signal despite not really wanting another messaging app and this is a big issue to him. I see that targeting API level 26 was done on Oct 3 according to the commits. So 1.5 months later is it time to show this problem a little love, especially given @bme13's effort to find a potential solution?

**Comment by dlnycs** [comment]
Same exact issue with latest Signal:

Device: Samsung Galaxy S8
Android version: 8.0.0
Signal version: 4.30.7

So many people have this important issue.  Can we get it fixed soon?   8 months have elapsed.   Thanks.

**Comment by dlnycs** [comment]
And it happens with the just released 4.30.8, too

**Comment by dorakas** [comment]
same with

Device: Pixel 3
Android version: 9.0.0
Signal version: 4.30.7

**Comment by MickMickle** [comment]
What's the first version that will incorporate the new code (https://github.com/signalapp/Signal-Android/commit/caf93b9203ff14332744d0208f550280f7fcc701)?  I'm on the current beta 4.31.3 which doesn't resolve the issue yet.

**Comment by greyson-signal** [comment]
It was just merged into master, so it won't be there until 4.31.4. In the future, if you're curious, you can go to https://github.com/signalapp/Signal-Android/commits/master to see what version it's in (look for the "Bump version to x.x.x" commits and looks what's underneath them).

**Comment by MickMickle** [comment]
Yep, it appears fixed. Well done! Signal updated on the beta channel a few minutes ago to 4.31.4, and I have the badge now with just one message (test message sent from second account in secure folder of Samsung Note 8, Android 8.0.0).

**Comment by greyson-signal** [comment]
Cool! Wanted to give a shoutout to @bme13. Your earlier content really helped point me in the right direction to fix the underlying problem. Thank you!

**Comment by greyson-signal** [comment]
Hey, so unfortunately we've hit a bit of a setback. There have been some reports of people experiencing notification issues after I made this change. The main feature in 4.31.x is typing indicators, and I don't want this to delay that release, so I've reverted the fix for now, but I'm going to continue to look into this for 4.32.x. I know it's frustrating to have a fix come and go, but hopefully you can understand where I'm coming from.

**Comment by Edu4rdSHL** [comment]
It was working fine in Samsung phone with Android 8.1.0, but I will wait for the next fix @greyson-signal and thank you.

**Comment by jeremymasters** [comment]
To be fair, there were notification issues for everyone affected by this bug before the fix.  I know discussion should take place in the forum, which would be fine.  Maybe explain more there, although you're certainly not obligated to do so.

**Comment by MickMickle** [comment]
I got 4.31.4 while the gettin' was good, and I'm happy with the way it works, fixed the notification badge and I've not encountered any other issues. I froze it there by in checking "Enable auto update." For others' benefit, is there a repository of archived versions for download now that beta has moved on to 4.31.5?

**Comment by sacanuck** [comment]
Just installed Signal 4.31.6
samsung galaxy a8.
Android 8.0.0

the notification problem still exists.

**Comment by MickMickle** [comment]
As described earlier, it was only fixed temporarily for 4.31.4.  I don't know if there's any way to get back to that beta version or not.

**Comment by greyson-signal** [comment]
I noted earlier in this thread that the fix was removed. This thread will be updated when a fix is put back in. Thanks!

**Comment by thecosmicyes** [comment]
It was mentioned earlier but as some people might not read the whole thread I repeat it: if you are using the Microsoft launcher anyhowe just enable Badge-support for Signal in the launchers settings. This solved the Problem for me. I heard that this ist also possible with the Nova-launcher but did not try it myself.

**Comment by thecosmicyes** [comment]
@Edu4rdSHL I just wanted to show a possible workarround. But thanks for the hint.

**Comment by MickMickle** [comment]
The notification badges are working fine on my Samsung Note 8 native launcher with beta version 4.31.4, and I haven't noticed any other bugs.  In Google Play Store, I have unchecked "Enable auto update" because it was a temporary intermediate beta version and is no longer available. Using Apk Extractor, I copied it over to my OneDrive for sideloading if anyone wishes:  https://1drv.ms/u/s!Agx1f1hbcVcZjH8CaQ9akA7o626N  (Hopefully, posting this link is allowed.)

**Comment by mathsen** [comment]
Same problem on Samsung XCover 4, despite disabled energy saving options for Signal and enabled notifications. When two or more different people send messages the app message indicator appears.

**Comment by SteveDun** [comment]
I persuaded my 60-strong local hobby club to use Signal groups for our collaboration / conversation recently. The overall response has been very positive, with the very big exception of this badge problem. There is now increasing frustration, and agition to change over to WhatsApp. Can you please help me allay this pressure by indication when a fix for the problem might be available. Personally, I don't want to use WhatsApp, but I am only one in 60 users at the club, and likely to be outvoted if this issue continues much longer.

**Comment by huettenwirt** [comment]
Same here, many of my friends I persuaded to switch are complaining about the badge problem. Since it was temporary fixed in a beta version, we would really appreciate a hint on the release date for the fix...

Best regards and keep up the great work! We need an open, secure and free counterpart to WhatsApp & Co.

**Comment by sybercorp** [comment]
For tracking purposes, the bug is still present in 4.32.7.

**Comment by MickMickle** [comment]
As posted earlier by @greyson-signal, "In the future, if you're curious, you can go to https://github.com/signalapp/Signal-Android/commits/master to see what version it's in (look for the "Bump version to x.x.x" commits and looks what's underneath them)."  You can check there periodically to see if the issue was fixed and then "bumped" to a new version.

In the meantime, you can get the apk for the only beta version that fixed the badges, 4.31.4, from my OneDrive account which I also posted earlier. (I would suggest an online archive site like apkmirror, but apparently they don't keep the beta versions.):

The notification badges are working fine on my Samsung Note 8 native launcher with beta version 4.31.4, and I haven't noticed any other bugs. In Google Play Store, I have unchecked "Enable auto update" because it was a temporary intermediate beta version and is no longer available. Using Apk Extractor, I copied it over to my OneDrive for sideloading if anyone wishes: https://1drv.ms/u/s!Agx1f1hbcVcZjH8CaQ9akA7o626N

**Comment by SteveDun** [comment]
Still hoping for a response to give an idea of when this bug might be fixed - or even if...
I cannot really ask my 60 colleagues to upload a beta version (most of them will not understand what that means!!).

**Comment by TheShanMan** [comment]
Yeah, that's the same fix that went into the beta. Perhaps the problem that caused him to revert the change last month was found to be unrelated to this change. Glad to see it's back in place! Hopefully this time for good! Thank you, @greyson-signal!

**Comment by MickMickle** [comment]
Just confirming that I am getting notification badges now with 4.33.0 on Samsung Note 8, Android 8.0.0.  (Signal 4.33.0 is beta, so you have to join the beta channel to get it.)

**Comment by SteveDun** [comment]
Delighted that this bug is fixed and in beta. Look forward to general release, as my group of old codgers don't go for early release versions...
Many thanks.

**Comment by greyson-signal** [comment]
Hey folks, I'm really sorry, but this had to get reverted again. It ended up causing a regression that can be seen in #8598.

So some background: when I first put this fix in, it was late in the beta, and we saw some beta feedback about notifications that made me nervous, causing us to revert it. These issues were different from #8598. But those issues looked like they may have been similar to long-standing issues we've seen from devices with aggressive battery optimizations, so I figured I'd try it again in this beta and see if we saw any trends. Everything looked good -- until I saw #8598. It's a bug directly caused by this fix.

That's the bad news. The good news is that I was spending some time trying to fix this again today, and I *think* I have a solution that fixes this issue without negative side-effects. But notifications on Android are super finnicky and change in subtle ways in almost every Android release, so I need to do more testing. Since we're starting our production rollout, I can't just throw this in there. But pending additional testing, it'll be in the next beta.

So hold in there! We'll get this fixed.

**Comment by MickMickle** [comment]
Ok, well.  Thanks.  I think I'll stay suspended at 4.33.3 with Google Play auto update for Signal disabled.

**Comment by TheShanMan** [comment]
Can't wait for 4.34 then!

**Comment by Edu4rdSHL** [comment]
It issue is fixed in Signal 4.34.2 without affecting other notifications things. Thank you Greyson.

**Comment by MickMickle** [comment]
Yep. 4.34.2 works.

**Comment by MickMickle** [comment]
And, the badge works in version 4.34.6, which is NOT beta.

**Comment by IanSpam** [comment]
I started getting this with 4.53.7. Just noticed when I am using the PC Signal. My phone notifies me quite fast. Otherwise no notifications arrive until I open app on phone. Seems odd, hope it helps...

**Comment by BestusefulTips** [comment]
I have a Pixel 3a (Running Android 10) device with the same issue. Below settings help me to fix the notification dots issue. You'll try it.

_**Settings > Apps & notifications > Advanced > Special app access > Notification access > Toggle on "Pixel launcher"**_
