### ISSUE TITLE
Notification sound issue

### ISSUE THREAD

**Issue by soulstenance** [signalapp/Signal-Android#7670]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Notifications sometimes come in silently (vibration only) while the app is not in focus. The issue occurs with no other apps and all sound settings are fully enabled with Do not Disturb off.

### Steps to reproduce
Note that I can't reliably reproduce it every single time but rather it happens once in a while with no apparent explanation.
- Leave app (with or without killing seems to make no difference)
- Receive a message

**Actual result:** Message notification comes through only with a vibration (if vibration is enabled).
**Expected result:** Message notification comes through with sound and vibration.

### Screenshots
N/A

### Device info
**Device:** Samsung Galaxy S9+
**Android version:** 8.0
**Signal version:** 4.17.5

### Link to debug log
https://debuglogs.org/c4be0d1266d9c93471f89a998efb812c829605273101469bcef199540b38b93e

**Comment by deutrino** [comment]
When this happens to me, I often get a truncated notification sound that lasts a couple tenths of a second.

Possibly related issue closed by auto-cleanup: #6600.

**Comment by soulstenance** [comment]
@deutrino Yes, that has occurred too, although more often than not, it's completely silent for me when this issue occurs.

**Comment by freed00m** [comment]
I also have this problem, but I actually never hear the sound. Only vibrations. Despite what sound I select.

I used to have Signal desktop but not anymore.

**Comment by mborod** [comment]
I have the same issue reported at the top.

I just want to add that I have repeatedly restarted my phone, and toggled the audible notification setting on and off, exiting the app each time, all with no effect.

I too have it installed on desktop but don't have it running on desktop.

**Comment by arjenlentz** [comment]
Same here on Nokia 5 and Nokia 6 under Nougat (Android 7.2)

**Comment by nathanaelhoyle** [comment]
I also frequently experience an issue with no sound played at all when a message is received. The display will light briefly to show the notification for the message, but no sound is played. I can usually temporarily resolve this with a restart of the phone (a Pixel XL running Android 8.1.0), but this never seems to last more than a couple of days (I don't intentionally ever have my phone off). This is true even though the volume is turned as high as it will go on every volume slider in the phone, it's not been set to vibrate mode, Do Not Disturb, etc.

**Comment by SingerGuy** [comment]
This is a constant irritant for me. I have a dozen or more contacts that I use customized sounds so I can triage an incoming message based on which sound I hear. Very frequently I'll hear a custom notification sound for a contact, respond to the message, and then set the app out of focus or turn off the display and I would expect the sound to play when they reply. I'll look at my phone some minutes later and see that they replied but I heard no sound and neither heard nor felt a vibration. I have even had it where as I was opening the app, but before getting into the contact, they sent me another message and the sound played as it should. This happens when my laptop computer is shut down and I am not running Signal Desktop. I am aware that with SD running and in focus that I shouldn't receive a sound (which is a great feature, thank you very much). I have found no pattern to this lack of sound and restarting it doesn't seem to make any difference. It is not isolated to any one contact or sound. It happens randomly on all incoming messages, whether they are Signal encrypted or SMS/MMS, with or without custom notification sounds.

**Comment by EOSfoto** [comment]
Having the same issue on a S8 (SM-G950F) on Android 8.0 (G950FXXU3CRGH).

**Comment by peterjanes** [comment]
I'm seeing similar behaviour as @SingerGuy but with a twist: I'll also miss the first notification after my phone (Nexus 6P, fully-patched Android 8.1.0) goes into or out of "Do Not Disturb" mode, customized to allow messages from starred contacts.

**Comment by jonaskew** [comment]
I have had the same issue for a long time now, at least a year, on a Samsung S7 (SM-G930F) over various Android versions (currently on 8.0.0).

Reinstalling seems to briefly help, but soon reverts to intermittent sounds, and quite often the 'clipped' playback mentioned above.

I'm not running Signal Desktop.

**Comment by greyson-signal** [comment]
Since this issue was reported, we've switching to notification channels, so hopefully issues with custom sounds playing have been resolved.

**Comment by Baconandstraws** [comment]
I am having the issue that the default sound is not working. The only special sound contact I have does come through. I am also not seeing badges for messages.

**Comment by Vomvas** [comment]
I am still experiencing this exact issue under MIUI 10 as well as on a Pocophone under MIUI (for POCO) 11.0.4. I have tested under MIUI Global 11.02 and the issue does not happen.

I have checked notification settings, permissions and power maagement. I get notification, badges, and vibration when enabled. I also get in-chat sounds when enabled. I never get out-of-chat sounds though. Is there anything else that might affect it?
