### ISSUE TITLE
Encrypted backup regression

### ISSUE THREAD

**Issue by RichJeanes** [signalapp/Signal-Android#7844]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal is no longer creating encrypted backups. The feature was working without issue when it was originally implemented. I do not have an SD card and I do not see any exceptions in the debug logs, so I think this is different than the existing issues on the repo. Apologies if it is not.

When the feature was working, my backup item count was ~24k items. Now it gets into that range and slows down (media messages and such) like before, but then continues very rapidly up to ~74k items. Once it finishes, no backup file has been created at /storage/emulated/0/Signal/Backups as they previously were and settings property correctly displays the day and time of the last successful backup file.

### Steps to reproduce
- Manually trigger backup or let one trigger automatically 

**Actual result:** Signal does not create a new backup
**Expected result:** Signal should create a new backup

### Device info

**Device:** Google Pixel 2 XL
**Android version:** 8.1.0, OPM2.171019.029.B1, May 5 patch
**Signal version:** 4.20.2, 4.20.4

### Link to debug log
4.20.2: https://debuglogs.org/236fd96194c0f416920df0195dfa5accbea6ec14318f13d892d66569bfbac707
4.20.4: https://debuglogs.org/89f96691eb686c5082e12eeb1b2a644aaed2679537d2c423ac178e655c08578e

**Comment by johanw666** [comment]
A fix (https://github.com/signalapp/Signal-Android/commit/70c2a863cca7984fec072913148fb4651e9644e4) is in master and will (hopefully very soon) be in 4.20.5.

**Comment by Hellmark** [comment]
@johanw666 will it actually fix it though? They've said they've had fixes for backup in place for months, and I've not seen anything work. People are kinda screwed right now. The ability to export out of Signal is taken away, backup doesn't work, and you cannot use adb to create a backup either. People cannot migrate their messages to new devices, and we're locked into only using Signal right now. To be honest, I regret switching to it.

**Comment by johanw666** [comment]
@Hellmark  I have not yet tested it. I agree with your sentiment, therefore I run my own fork of Signal with a functioning backup-restore.

**Comment by Ilnahro** [comment]
I have what seems to be the same issue on 4.20.4. 

Debug log: https://debuglogs.org/ec6db5673c799909ba82033d241573a3da76a9fbad9047dabf62ecd38d416821

**Comment by RichJeanes** [comment]
4.20.5 seems to be creating backup files again (though I have not tried restoring one) but the item count is still going up to ~74k items for some reason.

**Comment by Ilnahro** [comment]
Did you compile 4.20.5 yourself? I don't seem to get that update from Google yet.

**Comment by RichJeanes** [comment]
Yes, I compile and sign my own apks.

**Comment by Ilnahro** [comment]
Which begs the question why that version is not released yet. This new backup function is driving me crazy. It worked for a couple of weeks but since then one or another bug has consistently made it useless. And to top it off Signal crashes when restored with TB.

**Comment by Ilnahro** [comment]
Yeah, 4.20.5 is rolled out BUT the backup doesn't properly restore, so the feature remains pointless...

**Comment by devkid** [comment]
For me, creating the backup in Signal 4.20.5 worked (it's now in the beta channel), but it crashes repeatedly at restore on another phone (tried both 4.20.5 and 4.19.3) after exactly one message.

**Comment by dcgolden** [comment]
Can confirm issue with both backup and restore device on 4.20.5, restore crashes at 1st message

**Comment by dcgolden** [comment]
This functionality is working on 4.20.6, was able to restore 100,000+ messages to new device using encrypted backups

**Comment by greyson-signal** [comment]
@RichJeanes I think everything should be working now. I'm guessing you saw your message count skyrocket to 74k because we were incorrectly backing up the new full-text search index, which would more than double your existing message count. All of that should be addressed in 4.20.6. Re-open this if it's still a problem.

Also, I know there's been some issues with backups this release. We're going to be taking special care in the future to ensure that backups remain stable across releases as we add new features. 

Thank you all for being beta testers and helping find these bugs!

**Comment by jmayday** [comment]
Still doesn't work in 4.20.8 (simply backup is not created). 
Removing SD and triggering the process again results in having the backup created. Once the SD card is inserted no further backups can be saved.

**Comment by haffenloher** [comment]
@jmayday Could you please post a debug log captured right after a backup fails? Otherwise there's no way we can tell what's going on.

**Comment by greyson-signal** [comment]
@jmayday As @haffenloher helpfully suggested, please try to capture and submit a debug log (Settings > Advanced > Submit debug log).

Also, I think this issue may be more closely related to #7845? If so, can you post your information there?

**Comment by jmayday** [comment]
@haffenloher @greyson-signal 
https://debuglogs.org/b1b9966ee5feac519f23b2e5e6d0176cdbb3d964c7e8c3df38eef34db6b90b96

**Comment by jmayday** [comment]
For me problem is still present (updated today to Signal 4.22.4)

**Comment by Woosah** [comment]
Also having thus issue with 4.22.4

Are there any chances to get this fixed? I would like to reinstall my phone, but without a working Signal backup, this would bei desastrous...

**Comment by greyson-signal** [comment]
@jmayday Your problem looks to be the same as/related-to #7845. If so, it'll be fixed in 4.23, which is actively in beta and in the process of rolling out to production. Feel free to [join the beta](https://support.signal.org/hc/en-us/articles/115000269532-How-do-I-join-Signal-s-beta-) if you don't want to wait until early next week for the prod release to fully rollout.

@Woosah If you're having similar problems, they should also be addressed.

Thanks!

**Comment by jmayday** [comment]
@greyson-signal my issue is gone after updating to 4.23.4. Backups are now correctly created but I didn't have a change to test if whole process works... but I assume it does ;)
