### ISSUE TITLE
#8292 still persists (Cropping issues when taking a picture through the app)

### ISSUE THREAD

**Issue by sirlada** [signalapp/Signal-Android#8310]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
 #8292  seems not to be resolved on my device. I hope this behavior is not intended as it breaks the function of editing the picture before sending.

### Steps to reproduce
- open conversation
- take a photo from within the app
- look at the preview screen

**Actual result:** The viewfinder has a narrow field of view compared to the native camera app, and the captured image does not match what is shown in the viewfinder. This bug is present when using either the front camera or the rear camera. As a result only the zoomed-in part of the picture can be edited/viewed.
**Expected result:** The viewfinder shows the entire field of view available to the camera and the captured image matches what is shown in the viewfinder. The whole area of the picture can be edited using the provided tools and it can be checked/viewed before sending.

### Screenshots
viewfinder:
![screenshot_20181026-220414](https://user-images.githubusercontent.com/44510324/47591563-5f1b7680-d970-11e8-89bd-a4bd89bf1dad.png)
preview:
![screenshot_20181026-220433](https://user-images.githubusercontent.com/44510324/47591566-63e02a80-d970-11e8-8f55-8275f2827fa5.png)

### Device info

**Device:** Nokia 6.1 TA-1043
**Android version:** 8.1.0
**Signal version:** 4.29.7

**Comment by MeiRos** [comment]
Samsung Galaxy S8
Android 8.0.0
Signal 4.29.7

Same happens with rear camera. Front camera is working.

**Comment by szuetam** [comment]
Samsung Note 8 seems to have the same problem, sending a document and it crops. Annoying.

**Comment by Roltere** [comment]
Can confirm that it still exists in Signal version 4.30.8.

**Comment by rorymcdaniel** [comment]
Still exists

Nokia 6.1
Android 9
Signal 4.30.8

**Comment by zznidar** [comment]
Apparently it depends on the screen size/ratio – on a device I've just tested it zooms out once the photo is taken. The amount of zoom-out applied is differrent if I have navigation buttons at the bottom of the screen visible (i. e. shorter screen) than if I hide them (i. e. taller screen).
Additionally, taking a photo in-app while in Split Screen (in a way that Signal has the least screen space available) shows a squeezed view through the viewfinder, but the taken picture is zoomed in on a horizontal axis (in a way that it isn't squeezed anymore).

pocophone f1
Android 8.1.0
Signal 4.31.6

**Comment by sbufe** [comment]
Same issue.

Samsung Galaxy Note 8 SM-N950F.

Android 9

Signal 4.24.8

**Comment by greyson-signal** [comment]
I reopened #8292

**Comment by sbufe** [comment]
Today this is resolved on my Note 8. Pics are captured as they appear in the preview. Not only that, but there is two finger zoom.

**Comment by moultonlava** [comment]
I still have this same zoom problem when taking pictures within the Signal app on the Samsung Galaxy S6 rear camera.

https://piunikaweb.com/2019/03/20/samsung-galaxy-s10-front-camera-zoomed-in-heres-what-you-need-to-know/

**Comment by aflogit** [comment]
Still same problem on Huawei P30 on Signal 5.4.12, Android 10

**Comment by mmueller-kaffeeschluerfercom** [comment]
Still same problem on Pixel 5a, Signal 7.32.3.
