### ISSUE TITLE
Backup on "external" storage actually stores on internal storage and silently fails because no space left on device

### ISSUE THREAD

**Issue by pieqq** [signalapp/Signal-Android#8772]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
My internal storage is almost full (Signal database is taking up most of the space), so I would like to create a backup before deleting old messages.

The backup process starts, but never completes. When I go back in the option, the "Create backup" option is greyed out for a while even though no backup is present.

### Steps to reproduce
- go to Settings > Chats and media > Backups
- Activate "Chat backups – Backup chats to external storage"
- Write down the passphrase and click "Got it"
- Click on "Create backup – Last backup: Never"

**Actual result:**
- Signal computes the number of messages to archive (in my case, more than 43000) and put the "Create backup" status to "In progress"
- After a while, the process stops. If I go to another screen (for instance in the Advanced settings to get Signal version number for that bug report) and come back, the “Create backup – Last backup: Never” is shown again.
- No backup is available anywhere. Not on the external storage, nor on the internal one (nothing in `internal storage/Signal/Backups`)

**Expected result:**
- The backup is created and available on the external storage (aka removable storage, i.e. the SD card available that has plenty of space, unlike the Internal storage)

## Suggestions

- Change the wording from “Backup chats to external storage” to “Backup chats to internal storage”. For most users, "external" means "that SD card I inserted and where I store my pictures and music"
- Estimate the required space for the backup. If space on storage is not enough, gracefully stop with an error message.
- I've read the discussion in #8750 and understand that originally, backups were stored on SD card if possible, but that was removed because people lost their backups when they uninstalled  Signal. This is indeed a bad mechanism in Android, but Signal should try to mitigate it by giving the option to the user when creating a backup:
    1. Create backup on internal storage
    2. Create backup on external storage (if there is indeed an external storage available): if user selects this, a popup explaining the potential issue is shown ("Note that this backup will be removed if you uninstall the Signal app, so remember to store it somewhere safe once the process is complete.")

Thanks a lot for reading up to here!

### Device info

**Device:** Samsung Galaxy S7
**Android version:** 8.0.0
**Signal version:** 4.37.2

### Link to debug log
https://debuglogs.org/c018eb8266ab9bf7e4bc258798fc29f7a0013114eb2f5c5958955ff629301901

**Comment by johanw666** [comment]
I have already implemented a user option where to put backups. If the idea is has a chance of getting merged I can create a PR with this code.

**Comment by greyson-signal** [comment]
Hey there, don't have plans to enable backups to external SD cards. We will, however, look into a better description. Thanks!

**Comment by klues** [comment]
It's a pity that this issue still exists, currently I'm losing all of my Signal data while moving to another phone. I would suggest to give this issue more priority since it's really embarrasing to lose all data and have **no chance** of getting it out of a phone with too little internal storage.

**Comment by johanw666** [comment]
If you have root, or can root the device without data loss, you could try this procedure: https://community.signalusers.org/t/wiki-howto-manual-backup-restore-if-full-backup-does-not-work/2462

**Comment by klues** [comment]
Thanks for the hint. However unfortunately won't find the time to try this. In my opinion backup/import/export data is a core functionality and this feature should have priority over so much other things (like new link preview feature that came with the last update). @moxie-signal @moxie0 @greyson-signal don't you agree?! Or is it the intended way that people have to try some complicated user-driven backup methods with root requirements in order to not lose their data?!

**Comment by h0jeZvgoxFepBQ2C** [comment]
Please provide a way to store the backups to the SD card, it's eating all my disk space on my internal storage any my phone stops working because of it!
