### ISSUE TITLE
Crashes on backup restore (missing recipients SQL table)

### ISSUE THREAD

**Issue by dcousens** [signalapp/Signal-Android#9163]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When attempting to restore from backup,  the application crashes.

### Steps to reproduce
- Create a backup
- Clear Signal cache/storage
- Restore on startup

**Actual result:** Crashes
**Expected result:** Backup restored

### Device info

**Device:** Pixel
**Android version:** 10
**Signal version:** 4.49.14

### Link to debug log
> Caused by: net.sqlcipher.database.SQLiteException: no such table: recipient: , while compiling: SELECT _id FROM recipient WHERE phone = ?

```
  java.lang.RuntimeException: An error occurred while executing doInBackground()
   at android.os.AsyncTask$4.done(AsyncTask.java:399)
   at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
   at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
   at java.util.concurrent.FutureTask.run(FutureTask.java:271)
   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
   at java.lang.Thread.run(Thread.java:919)
      Caused by: net.sqlcipher.database.SQLiteException: no such table: recipient: , while compiling: SELECT _id FROM recipient WHERE phone = ?
   at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
   at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:3)
   at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:12)
   at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:18)
   at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:1)
   at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:8)
   at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:5)
   at net.sqlcipher.database.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:4)
   at net.sqlcipher.database.SQLiteDatabase.query(SQLiteDatabase.java:1)
   at net.sqlcipher.database.SQLiteDatabase.query(SQLiteDatabase.java:2)
   at org.thoughtcrime.securesms.database.RecipientDatabase.getByColumn(RecipientDatabase.java:3)
   at org.thoughtcrime.securesms.database.RecipientDatabase.getOrInsertByColumn(RecipientDatabase.java:2)
   at org.thoughtcrime.securesms.database.RecipientDatabase.getOrInsertFromE164(RecipientDatabase.java:1)
   at org.thoughtcrime.securesms.recipients.Recipient.external(Recipient.java:8)
   at org.thoughtcrime.securesms.backup.FullBackupImporter.processAvatar(FullBackupImporter.java:2)
   at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:11)
   at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:7)
   at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:1)
   at android.os.AsyncTask$3.call(AsyncTask.java:378)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)...
```

I checked other issues like https://github.com/signalapp/Signal-Android/issues/9154, https://github.com/signalapp/Signal-Android/issues/9136 - to no avail.

**Comment by bepaald** [comment]
Sounds like #9133, which should be fixed. Maybe try updating to 4.49.15?

**Comment by greyson-signal** [comment]
This should be fixed in 4.49.15.

**Comment by dcousens** [comment]
@bepaald / @greyson-signal thanks!  I'll report back if it isn't resolved.
