### ISSUE TITLE
Adding a contact to a group results in "Failed to update the group" toast

### ISSUE THREAD

**Issue by hiqua** [signalapp/Signal-Android#9768]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Adding a contact to a group results in "Failed to update the group" toast.

I sent a Signal message to this contact and got a confirmation that they received it (double tick), so I think the Signal account still exists.

### Steps to reproduce
- In a group with already 6 members, do "add members"
- add this contact

Note that this is the first time that this happened to me, so I don't think it's easily reproducible. There are exceptions in the debug log that might be worth investigating though.

**Actual result:**

Contact not added.

**Expected result:**

Contact added.

### Link to debug log
https://debuglogs.org/5f5726145d09b10d50135638658f26738aa1ebaa3ff4b108ec4598121533d174

**Comment by DanielNovak** [comment]
Is this maybe a coincidence? I have just tried to add new members to a group with 6 people and I am getting the same error. The second admin tried also - with same result. I have been trying for few minutes with same result.

**Comment by hiqua** [comment]
> Is this maybe a coincidence? I have just tried to add new members to a group with 6 people and I am getting the same error. The second admin tried also - with same result. I have been trying for few minutes with same result.

Were you trying to add the 7th person right after the 6th was added? Or was there a delay in between?

**Comment by hiqua** [comment]
@DanielNovak can you add your debug log?

**Comment by DanielNovak** [comment]
6 members were added yesterday and we are now adding the 7th member. After many tries it now succeeded. The 7th member was a newly registered account. Now I am trying to add the 8th member. It looks like either the backends are overloaded and we have to try several times, or new members can't be added to a group after registering to Signal just few minutes before? I have sent a support request email just now with the debug log (name: Daniel Novak). I would prefer not to attach it publicly.

**Comment by Gugols** [comment]
Yes, having the same problem adding a new member. He recently joined Signal. It seems like the network is under some heavy traffic most likely to to the surge of new users.

**Comment by endofu** [comment]
Similar behaviour when I try to make others admins or try to remove someone.

I get both the "Failed to update group due to network error." message and the shorter one without mentioning the network error. 

Debug log: https://debuglogs.org/d19ca7cb0b72708021da06f35b386b00a31d9e9d398e3e7f8fddc20d3ba2ae01

**Comment by bkqtnte10** [comment]
Same error for me and the 3rd and 4th user.

I tried to check server connectivity (as suggested in https://github.com/signalapp/Signal-Android/issues/10389#issuecomment-757169017) and get this error in 8 of 10 tries:

> Error: Server Error
> The server encountered a temporary error and could not complete your request.
> Please try again in 30 seconds.

These errors are independent of used network (WIFI, mobile internet)

**Comment by IntoAbhi** [comment]
Similar behavior for me. Tried turning off 'disappearing messages' which was initially turned on in a group of 35 people, it threw the toast "Failed to update group due to network error". After 10 mins all of a sudden, while I was sitting idle the disappearing messages got turned off. So yes, I guess its heavy load due to the recent awareness of data theft among users and hence surge in users due to migration from WhatsApp to Signal.

**Comment by DanielNovak** [comment]
In the mean time we can at least use the invitation link - this worked without issues.

**Comment by Gugols** [comment]
> In the mean time we can at least use the invitation link - this worked without issues.

Will try. However, there is similar issue reported for invites as well - https://github.com/signalapp/Signal-Android/issues/10436
It's a matter of server handling the load which it seems fails to achieve.

**Comment by peheje** [comment]
> In the mean time we can at least use the invitation link - this worked without issues.

I can't create an invitation link. Network error.

**Comment by leszekkepa** [comment]
The same - I can't add members and I can't share link - "group update failed" or "network error".

**Comment by greyson-signal** [comment]
I think some of this was because of some server issues we were having at the time, and then we also just pushed another fix last night related to this, so I'm gonna assume that this is fixed for now. Please re-open if you see more issues. Thanks!

**Comment by leszekkepa** [comment]
Still not working. I just removed groups and created new.

**Comment by derWalter** [comment]
Problem persists, Signal Desktop 6.39.0 (throws "something went wrong! please try again or contact support") and on android 6.39.3 (trohws "failed to update the group")

**Comment by bellancaf** [comment]
I had the same issue today
