### ISSUE TITLE
Signal crashes on selecting group image from gallery

### ISSUE THREAD

**Issue by mlsxlist** [signalapp/Signal-Android#9832]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes on setting a photo for a group

### Steps to reproduce
- go to group setting
- edit group
- edit photo
- choose from gallery 

Boom

**Actual result:** Signal crashes
**Expected result:** Signal should not crash

### Device info
**Device:** Huawei P30 Pro, VOG-L29
**Android version:** 10.1.0.123
**Signal version:** 4.65.2

### Link to debug log
https://debuglogs.org/61484b394562b7a1bc6b5bf65e15f67df856fd2aef0dfc7521b89104b03a7132

**Comment by mlsxlist** [comment]
Crash happens around 22:35:12.

**Comment by nine76evil** [comment]
Can confirm same issue on:

Google Pixel 3a
Android 10
Signal 4.67.1

**Comment by 0xTom** [comment]
Same here

Samsung Galaxy S10e
Android 10
Signal 4.68.4

**Comment by phraemer** [comment]
Same

Google Pixel 3a
Android 11
Signal 4.70.5

**Comment by cody-signal** [comment]
@phraemer could you provide a debug log with the crash?

Looking for some help in reproducing this issue, as I'm unable to, so I'm guessing there's something unique/different y'all are doing that I'm not. Some quick questions:

1. Does it always crash?
1. Does it crash for every image you pick? Can you try small and large images.
1. Does it crash when taking a picture?

Thanks!

**Comment by phraemer** [comment]
Hi @cody-signal 

1. I think so yes. It may have on some occasions just gone back one screen but I'm not sure.
2. It crashed when opening the gallery before any image can be selected
3. Yep. Again, while opening the camera.

https://debuglogs.org/3bd57e7b74ea2783254e7a9e08c0ba5becc87b7163175b13ff1a6aaf4c10a5f7

**Comment by shyos** [comment]
This is caused by onSaveInstanceState method of EditProfileFragment. If image size exceeds 1MB it throws TransactionTooLargeException and causas crash. Comment outing this method solves the problem.

**Comment by phraemer** [comment]
>  If image size exceeds 1MB it throws

It crashes before an image is even selected from the gallery or a photo taken.

**Comment by shyos** [comment]
@phraemer It is not about the gallery or photo taken. It is about existing avatar.

Following converts existing avatar to byte array, and [buffer has 1Mb limit](https://developer.android.com/reference/android/os/TransactionTooLargeException), so it throws an exception.

` outState.putByteArray(AVATAR_STATE, viewModel.getAvatarSnapshot());`

To find root cause, I TooLarge tool mentioned on https://stackoverflow.com/a/50162810/1648708

**Comment by PashockACDC** [comment]
I found a 100 % reproducible scenario:

1. (crucial point) create a group **WITH** large photo
2. go to group settings
3. edit photo
4. choose from gallery
...
crash

**Comment by greyson-signal** [comment]
This is fixed in the upcoming 4.72 release, thanks!

**Comment by pr0gg3r** [comment]
I have version 5.0.9 for Android, still crashing every time I select gallery (profile, group and message).

**Comment by grandchild** [comment]
@pr0gg3r Can you open a new issue with a debuglog? After the crash happens, open Signal again and go to Settings > Advanced > Submit debug log.

Without a debug log it's almost impossible to fix.

**Comment by pr0gg3r** [comment]
I just reinstalled Signal and have now version 5.0.10 - problem still exists. Every time I tap on from gallery the gallery opens for a second and than it crashs. Here is my log: [https://debuglogs.org/778731890a5514c316beff2a4055ce05b8160b200110ee76305e13fe9b53be00](https://debuglogs.org/778731890a5514c316beff2a4055ce05b8160b200110ee76305e13fe9b53be00 )

**Comment by grandchild** [comment]
Okay, so it seems to crash doing this: https://github.com/signalapp/Signal-Android/blob/v5.0.10/app/src/main/java/org/thoughtcrime/securesms/recipients/LiveRecipient.java#L127-L131

Still, @pr0gg3r, a separate issue will get this more attention, since I don't know if the devs look into closed issues...

**Comment by pr0gg3r** [comment]
Here is the new bug report https://github.com/signalapp/Signal-Android/issues/10624

**Comment by grandchild** [comment]
Lovely bug report! 👏🏾
