### ISSUE TITLE
X has changed their profile name to Y spam in group chats

### ISSUE THREAD

**Issue by schmeat** [signalapp/Signal-Android#9860]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I have a friend that switched their phone numbers and phones, so they have a duplicate account. This duplicate account is in multiple group chats with me. Every time I enter a group chat, it tells me that this old account has changed their profile name in EVERY group that it's in. I also have this account blocked, so I shouldn't even be receiving alerts for it anyways.

### Steps to reproduce
- Add friend to multiple group chats
- Have friend make a new account and let the previous account go stale
- block old account
- enter any of the group chats that the friend was added in and observe the status message

### Screenshots

![signal-2020-07-17-100554](https://user-images.githubusercontent.com/1139817/87798420-fcd86880-c819-11ea-981e-cb1b1dc5f7c8.jpeg)

### Device info
========= SYSINFO =========
Time         : 1594996542538
Manufacturer : samsung
Model        : SM-G975W
Product      : beyond2qltecs
Screen       : 1440x2730, xxxhdpi (560), 60.00 hz
Font Scale   : 1.1
Android      : 10 (G975WVLU3DTE8, QP1A.190711.020.G975WVLU3DTE8)
ABIs         : arm64-v8a, armeabi-v7a, armeabi
Memory       : 79M (9.88% free, 512M max)
Memclass     : 256
OS Host      : 21HH1G05
Censored     : false
Play Services: true
FCM          : true
First Version: 530
App          : Signal 4.66.7 (6752)
Package      : org.thoughtcrime.securesms (doDiFGKPO1r)

### Link to debug log
https://debuglogs.org/085935c5ee62074562212dc245854419460693f3167e84e2806dc37389f01626

**Comment by greyson-signal** [comment]
Hi there, this should be fixed in 4.66.8

**Comment by ryanbeales** [comment]
This is still occurring in 4.66.8. Not every member of the group chat is seeing it, we only have 1 week of history enabled so can't verify when it started. 

![Screenshot_20200722_180608_org thoughtcrime securesms~2](https://user-images.githubusercontent.com/25877756/88243818-7e7b2c80-cc46-11ea-80d2-1dd6912ddd62.jpg)

**Comment by greyson-signal** [comment]
@ryanbeales Without revealing names, can you tell me about the change message in more detail?

For instance, is it saying there's a change when there doesn't appear to be? i.e.
`Alice changed their profile name to Alice`

Or is it alternating between names? i.e.
`Alice changed their profile name to Alice2`
`Alice2 changed their profile name to Alice`

Is there any pattern among the names themselves? Do they all contain multiple spaces, are they using non-ASCII/Latin characters?

The logic for writing these name change events is pretty straightforward, so mostly just trying to figure out if something more fundamental could be going wrong (like properly detecting string equality).

**Comment by ryanbeales** [comment]
The message is always:
> Name changed their profile name to Name
The characters all look the same, no unicode oddities I can spot.

My background is more server side Java apps, not this, but I see there was a recent change here:
https://github.com/signalapp/Signal-Android/commit/64420ead7c1a76666b57f582fb8c21fd93a3a4d5

It looks like the message we see is added here from the above commit:
https://github.com/signalapp/Signal-Android/commit/64420ead7c1a76666b57f582fb8c21fd93a3a4d5#diff-059a6fbb72a253b84b2791838f4d6155R388

But in `serialize()`
https://github.com/signalapp/Signal-Android/blob/1ce36c10692759f856097aa291b495772eb5c2d1/app/src/main/java/org/thoughtcrime/securesms/profiles/ProfileName.java#L56 it inserts a null between Given and Family names, could there be something in family name that isn't printing to the screen on these messages?

**Comment by ryanbeales** [comment]
A further update: The user hasn't had Signal installed for a while, they installed it then left the group and then uninstalled again. This stopped the messages within the group and within the 1:1 messages with the user - in my case the only content of the 1:1 messages were the name changes. The messages are still in the history but for now we're not getting new ones generated anymore.

**Comment by veteze** [comment]
I have this happening with one friend.

She's on ios. And it's sending these updates to others in the group who are on Android OS.

I dont see them at all. I've asked everyone to update to latest and that has had no effect.

It's doing this style:
Alice changed their profile name to Alice2
Alice2 changed their profile name to Alice

**Comment by kmcnellis** [comment]
I'm seeing that same pattern too, for 3 of my contacts that removed their last names from the profile. It's been going on for a week, and the pattern of the messages is different on my phone (iOS) and my linked iPad and desktop clients.

**Comment by rivanel** [comment]
I've had the similar issue, for me the contact had 3 fields filled in: Name, Surname, Organization
and Signal was posting updates

Name Surname has changed (...) to Name Organization
and then in reversed order
Name Surname has changed (...) to Organization Name

After removing Organization from the contact the problem seems to not occur anymore
Maybe that'll help to solve the issue, or at least provide the workaround

**Comment by patrick-cpka** [comment]
Still an issue

**Comment by kallekruse** [comment]
I have been made aware that Signal is spamming contacts of mine with similar messages regarding myself. In my case it claims that I changed my profile name "from MyName to ." (empty string)

**Comment by greyson-signal** [comment]
For anyone experiencing this, can you please post a log, and if possible, a log from the person who's name is changing?

**Comment by Opa-** [comment]
Hello,

Still experiencing this issue on Android, both using version 5.32.15
Here's a picture and my logs (I'm the one receiving the notification about my contact updating his profile name).

<img src="https://user-images.githubusercontent.com/6153672/159472901-d85c15d2-02fb-414b-baee-9969fe55518c.jpeg" width="300">

https://debuglogs.org/android/5.32.15/178dbae5939d77eba85254ed9c3a5da44e63253486d6726dbb93930d6243d3df

I guess these lines from the log are related to the issue (timestamp match with the message I blacked out on the image):

```
[5.32.15] [2555 ] 2022-03-22 11:56:17.080 GMT+01:00 I RetrieveProfileJob: Profile name updated. Writing new value.
[5.32.15] [2555 ] 2022-03-22 11:56:17.081 GMT+01:00 I RetrieveProfileJob: Writing a profile name change event for RecipientId::11
[5.32.15] [2555 ] 2022-03-22 11:56:17.096 GMT+01:00 I RetrieveProfileJob: No profile name set for RecipientId::11
```

**Comment by greyson-signal** [comment]
Thank you, I've made some changes that will go out in a future release that will hopefully help. Let me know if you're still experiencing this issue after updating to 5.35 (which will likely go to beta in a couple days). Thanks!

**Comment by cody-signal** [comment]
@Opa- has this issue resolved after the changes?

**Comment by Opa-** [comment]
@cody-signal yes we are not experiencing this issue anymore 🙂
