### ISSUE TITLE
Missing SMS messages

### ISSUE THREAD

**Issue by Nylanfs** [signalapp/Signal-Android#9977]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm not receiving all SMS messages in Signal, I have a feeling that this might be an issue with Google Auto and Signal communication. 

### Steps to reproduce
- Getting yelled at by my wife for messages Signal never received
- Check message log, and phone records
- Show them sent and recieved by carrier but NOT in signal.

**Actual result:** Several messages between Chris Grosse and I were never received.
**Expected result:** Me not getting yelled at for missing text messages

### Screenshots
All messages show in Signal for time period
![Screenshot_20200831-090521_Signal](https://user-images.githubusercontent.com/8888950/91726402-29e49e80-eb6e-11ea-9847-be5a3198a11e.jpg)
Provider logs of messages, Note snipped extras messages not between Chris and I.
![SMS_Troubleshooting_Paul ](https://user-images.githubusercontent.com/8888950/91728760-8bf2d300-eb71-11ea-883c-db1589dc4071.jpg)
![SMS_Troubleshooting_Chris ](https://user-images.githubusercontent.com/8888950/91728771-8eedc380-eb71-11ea-8628-43d7d3ff26d0.jpg)

### Device info
**Device:** Samsung Galaxy S9
**Android version:** 10
**Signal version:** 4.70.3

### Link to debug log
https://debuglogs.org/8cdcb023ba70bccbd5e0c7c2a09f83999d41e8bcdf0033278a945edffe52d639

**Comment by Nylanfs** [comment]
I'm almost positive that it has to do with Android Auto now. Here's the time frame when I should have gotten those messages. I was driving so Android Auto would have been active.
![SMS_Troubleshooting_Driving ](https://user-images.githubusercontent.com/8888950/91765283-b14e0400-eba6-11ea-8687-62f7e533410f.jpg)

**Comment by nabrach** [comment]
Seems I am experiencing a similar issue as well. I will see a notification when a message is received. But that message does not show at the bottom of the conversation with the contact (as expected). 

I cleared the cache, restarted my phone and even went as far as to uninstall and reinstall the Signal app. This worked for a little, but the same issue presented itself again today (1 week later).

Samsung Galaxy S10e

**Comment by Nylanfs** [comment]
Sadly still having same issues, I have since switched back to using the samsung Messages till this is resolved. Can't have wife mad at me. :)

**Comment by jnr2820** [comment]
I stopped using Signal with Android Auto as I was getting the behavior that this guy was describing below. (In 2020). It's possible that Signal SMS with Android Auto is still broken:

https://support.google.com/androidauto/thread/11335386?hl=en

Signal seems to work fine for me with Native Signal messages, but SMS is a different story.

**Comment by ben-mathu** [comment]
I have the same issue whenever the Signal process is closed, that is, the app has been destroyed by the Android system.
